### ISSUE TITLE
optimize('uhf') doesn't realize it has analytic gradients

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4#103]
The driver recognizes optimize('scf') has UHF analytic gradients, but not optimize('uhf').  Make sure the driver can catch other ways of specifying the same computation, like optimize('uhf') or optimize('hf') (or else warn the user about the preferred way to specify things).

**Comment by loriab** [comment]
Fixed by 6f6d3aa1d039e4501bc5c5dc4190da1758e1c889 though I rather think now that defining hf/rhf/uhf/rohf/rsch/roscf/uscf for energy() was a bad idea (by me) a few years ago (except for "hf" itself). Nevertheless, as this ticket points out, having defined these names only for energy() confounds the driver logic. These convenience names are now in place for gradient() and property().

I'd be glad to rip out the lot (except for "hf") from energy(), grad(), prop() if others concur with my present assessment.

**Comment by CDSherrill** [comment]
Is the proposal to replace uhf/rhf/rohf -> hf for energy(), grad(), etc?
That sounds ok to me (then reference just has to be defined properly).

What about DFT, do we define functional properly and do energy('dft'), etc.?

David

**Comment by fevangelista** [comment]
The modification sounds fine to me.  Will energy('hf') assume something about reference?  e.g. rhf for closed shells and rohf for open shells.  Or does the user have to always specify reference?

**Comment by loriab** [comment]
Without The-7 (hf/rhf/uhf/rohf/rscf/roscf/uscf), one can do:

# (a) for HF
energy(‘scf’)

# (b) for unrestricted HF
set reference uhf
energy(‘scf’)

# (c) for B3LYP
set dft_functional b3lyp
set reference rks
energy(‘scf’)

# (d) also for B3LYP
energy(‘b3lyp’)

# but this gets you HF (b/c ks reference is the hf/dft toggle control)
set dft_functional b3lyp
energy(‘scf')

# (e) for unrestricted B3LYP
set dft_functional b3lyp
set reference uks
energy(‘scf’)

# (f) also for unrestricted B3LYP
set reference uks
energy(‘b3lyp’)

# (g) also for unrestricted B3LYP (since energy command trumps options, uhf gets translated to uks)
set reference uhf
energy(‘b3lyp’)

But most people do (a), (b), (d), and (f/g) I think. rhf/uhf/rohf let you wrap reference into the energy() call for HF. rscf/uscf/roscf let you wrap reference into the energy() call for HF or DFT (though for the latter you’d have to use dft_functional keyword.

Francesco brings up a related and overdue point. If you specify an open-shell molecule and no reference, it complains at you b/c rhf (the default) is unsuitable. I couldn’t say concretely, but some other programs will switch to an appropriate reference for open-shell. For psi4, it would have to be rhf/rks because we don’t have roks. This would be convenient at times, for instance, running databases of mixed closed/open shell.

Propositions to be considered:

(i) Keeping reference in one place, that is, as a keyword. Consequences: retire rhf/uhf/rohf & rscf/uscf/roscf

(ii) If molecule is open-shell *and* no reference has been specified, switch to uhf. This could be tricky b/c we’re not set up to do this driver-side. Also, there’d still be no way to use r/ro, as appropriate, in a series of molecules w/o explicitly setting reference.

Lori

**Comment by CDSherrill** [comment]
Is there an advantage to doing

gradient('b3lyp')

instead of

set reference rks
set dft_functional b3lyp
gradient('scf')?

I guess the former is certainly shorter.  But primarily I'm wondering
whether one is easier to check than the other regarding whether the
gradient is available.  We need to know on a functional-by-functional basis
whether we have analytic gradients or not.  If that's much easier to handle
with one style vs the other, that would be an argument for doing it that
way.  Then we can decide what to do with the HF cases to make them play
nicely with our desired solution for the DFT ones.

David

**Comment by loriab** [comment]
Either of those dft gradients calls works, though I exclusively use the former. They work b/c all functionals are added to procedures[‘energy’] and all but dh are added to procedures[‘gradient’]. (see snippet below.) (They’re missing from procedures['property’] and that should probably be remedied.

So DFT is generally in good shape: energies work, gradients work (analytic except findif for dh), r/u ks set exclusively by option. You can use ‘scf’ to mean HF, and then it works just the same as DFT. I’d advocate thoroughly adding ‘hf’ (that is not just to energy() like it has been) so it’s on-par with DFT.

The r/u/ro options were a nice thought, but not thoroughly carried out, with disturbing consequences, as you found.

# Integrate DFT with driver routines
for ssuper in superfunctional_list():
    procedures['energy'][ssuper.name().lower()] = run_dft

for ssuper in superfunctional_list():
    if ((not ssuper.is_c_hybrid()) and (not ssuper.is_c_lrc()) and (not ssuper.is_x_lrc())):
        procedures['gradient'][ssuper.name().lower()] = run_dft_gradient

**Comment by psi4** [comment]
From discussion today, the following tasks:

- [ ] In ``driver.py``, delete reference-bearing methods from procedures table (multiple places). Delete ``table:energy_scf`` rst table and its analogies. Salvage ``'hf'`` from them and move it into the main rst table.
- [ ] In ``proc.py``, remove much of ``parse_scf_cases``, maybe drop that fn and move it back into the run_scf* as it was early this year.
- [ ] Inspect test cases for removed functionality and adapt them. Check that the uhf that originally prompted this post is still working. Check that every energy/gradient rhf/uhf/rohf/cuhf/etc scf/hf/b3lyp does something sensible or exits gracefully.
- [ ] Check the docs to see if they reference this functionality and adapt them.

**Comment by dgasmith** [comment]
@loriab I think these are complete? I know quite a few of them are.

**Comment by loriab** [comment]
After reading through all the various tickets and TODOs, I agree. @amjames's #117 did most of the scf work, and #118 is still open to prompt the auto open-shell reference task, so will close this but leave the checkbox on TODO open since that's half 118.
