### ISSUE TITLE
PSIO Error Using ODC after OMP2/OLCCD on UHF Reference

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1288]
The following input file
```
molecule mol {
  0 1 
  units bohr
 O 0 0 -0.143225816552
 H 0 1.638036840407 1.136548822547
 H 0 -1.638036840407 1.136548822547
}

set {
  reference uhf 
  basis sto-3g
  scf_type pk
  mp2_type conv
  dcft_functional odc-12
}

energy('omp2')
energy('dcft')
```
crashes with error
```
PSIO_ERROR: Attempt to write into next entry: 61, MO Ints (OO|OV)
PSIO_ERROR: unit = 61, errval = 18
PSIO_ERROR: 18 (Incorrect block end address)
Traceback (most recent call last):
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/bin/psi4", line 271, in <module>
    exec(content)
  File "<string>", line 33, in <module>
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/driver.py", line 493, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/proc.py", line 1479, in run_dcft
    dcft_wfn = core.dcft(ref_wfn)

RuntimeError: 
Fatal Error: PSIO Error
Error occurred in file: /Users/jonathonmisiewicz/psi4/psi4/src/psi4/libpsio/error.cc on line: 128
The most recent 5 function calls were:
```
Modifying the input file showed the following:

- The error resolves when changing the reference from UHF to RHF
- Both ODC-06 and ODC-12 will trigger the error, but neither DC-06 nor DC-12 will
- Both OMP2 and OLCCD before the ODC will trigger the error, but neither MP2 nor LCCD will

**Comment by andysim** [comment]
If you put a `clean()` between the `energy` calls, it'll work.  The files used to transform ints in the two calls are somehow interfering with each other.

**Comment by loriab** [comment]
yikes.

sounds like part of "Make LibDPD Great Again" (PsiCon 2016) is to make clear how to use DPD.

**Comment by ssh2** [comment]
Since I was the one who wrote a lot of that code along with @andysim, I am happy to discuss this at PsiCon. I think unifying the conventions is OK, but I wonder why the same problem does not appear when a CC computation is run after DCT or vice versa (at least this is my recollection). Are OCC and DCT codes the only codes that are affected?

**Comment by amjames** [comment]
While I'm not sure if OCC/DCT are the only two codes affected, I can explain why the issue does not come when the conventional CC codes is thrown into the mix. 

On the lines that @JonathonMisiewicz linked the MO integrals are sorted but the permuted tensors are stored on the general purpose file `PSIF_LIBTRANS_DPD`. When OO/DCT are run the first one will add records to this file and the other will try to add them again, but apparently their different row/column convention means those psio entries will not be the same size.

The conventional CC code will read transformed integrals on the `PSIF_LIBTRANS_DPD`, but then sorts them onto different files. For example, [here](https://github.com/psi4/psi4/blob/bfc839dd8de959df1b80c1eee974cd5b64a0e9f5/psi4/src/psi4/cctransort/sort_tei_rhf.cc#L94) The `MO Ints (OV|VV)` entry is read from `PSIF_LIBTRANS_DPD`, but the sorted target `F <ia|bc>` goes on the file `PSIF_CC_FINTS`.  Running the CC code before/after either of these modules won't cause a conflict because sorted integrals are written in a different location, so there will be no issues of writing off the end of one entry and onto the next.

**Comment by JonathonMisiewicz** [comment]
I can do some more detailed testing on the scope of this bug next week. (Something has come up that will commandeer the rest of this week for me.)

The thing that I still don't understand is why this bug only afflicts _unrestricted_ references. Perhaps the indexing convention disagreement is limited to only a few integral blocks? I only checked that there was an index disagreement for the case I linked.

**Comment by amjames** [comment]
@loriab This issue isn't so much a problem with not understanding how to use DPD, as I am sure the author of each module was aware of what the code they wrote would do. This is more a fundamental issue with DPD and how it poorly manages shared state. In this case the entry that triggers the psio error already exists and has a smaller size than the data that is being written in its place, but there is no mechanism for gracefully avoiding that situation. 

I am working on a better model that avoids a lot of these problems with shared state. I have so far worked out (on paper) how map objects to the regions where their data is stored on disk and keep everything from overwriting each other.  The last piece of the puzzle is how to allow *some* shared ownership to exist, for example you would like the DCFT module or the OMP2 module to be "aware" if integrals have already been transformed, and then avoid doing the transformation again but because they were given an object that points to a particular location on disk, not because they looked in some predetermined location and found *something* there.

**Comment by amjames** [comment]
@JonathonMisiewicz something to keep in mind, that may help while investigating the bug, The error you are seeing is raised by psio when it checks that a particular write won't extend into the next entry. So there may be differences in the size of other blocks, however if the overwrite is smaller than the old quantity you will never write into the next entry and an error wont occur.

**Comment by loriab** [comment]
Sorry. The row/column discrepancy struck me as dpd having an unwritten convention that would be helped by writing it down somewhere prominent. My comment probably came across as more critical than intended.

**Comment by JonathonMisiewicz** [comment]
@amjames Is this "smaller" dimension by dimension?

I'm lost on what "shared state" has to do with this problem. Because the relevant codes are orbital-optimized, the integrals in file61 when the bug occurs are transformed into the orbitals optimal for MP2. The DCT code starts from a different set of orbitals. (The NSOs of MP2, as I recall?) The orbital state of OMP2 is not supposed to be shared.

As for Lori's comment, _is_ there a row/column convention? I had assumed there was.

**Comment by amjames** [comment]
@JonathonMisiewicz smaller here means the number of bytes in the psio entry. The piso unit (`PSIF_LIBTRANS_DPD`) and the TOC key `MO Ints (OO|OV)` point to a unique entry. Based on the error you are seeing that means that the number of bytes written to that entry by `OMP2` code or by some call made by the `OMP2` was smaller than the number of bytes that the line you linked is trying to write.

I am not familiar with the `ID` macro, but I am assuming it is defined outside each module and that is not the source of the problem, and since the size of the Alpha occupied/virtual space hasn't changed it could be that the entry on file was written in the `OMP2` code with the bra packed?

**Comment by amjames** [comment]
And regarding the shared state issue. I did not realize that we were looking at orbital optimized methods so the example of avoiding work by intentionally sharing state here is a bad one. but the issue is still related. 

The error arises when you run the modules one after the other, because the `DCFT` module is making some assumptions, probably unintentionally about the state of various psio files. However the `OMP2` module has modified that state and the assumptions `DCFT` is making are no longer valid. In this case the assumption is that the `MO Ints (OO|OV)` entry either does not exist, or if it exists it is the correct size to hold `O,O,O,V`

This is not a case of sloppy programing by the authors of either module, it is a consequence of DPD creating global state in a difficult to predict way (due to a lack of documentation), and not providing the means to program defensively around it.

**Comment by ssh2** [comment]
OK, thanks for the analysis, @amjames. I agree that this is a problem of DPD that can potentially cause issues when it is used inconsistently.

**Comment by JonathonMisiewicz** [comment]
@amjames That clears up the shared state issue, thank you.

I have the growing suspicion that I've been leading you all to nowhere. I'll walk you through what I did from the start.

lldb said the error originated from line 362 of dcft_integrals_UHF.cc, so I applied the following:
```
@ -357,8 +357,14 @@ void DCFTSolver::sort_OOOV_integrals() {
     global_dpd_->buf4_sort(&I, PSIF_LIBTRANS_DPD, prqs, ID("[V,O]"), ID("[O,O]"), "MO Ints <VO|OO>");
     global_dpd_->buf4_close(&I);
 
+    global_dpd_->buf4_init(&I, PSIF_LIBTRANS_DPD, 0, ID("[O,O]"), ID("[O,V]"), ID("[O>=O]+"), ID("[O,V]"), 0,
+                           "MO Ints (VO|OO)");
+    global_dpd_->buf4_print(&I, "outfile", 1);
+    global_dpd_->buf4_close(&I);
+
     global_dpd_->buf4_init(&I, PSIF_LIBTRANS_DPD, 0, ID("[V,O]"), ID("[O,O]"), ID("[V,O]"), ID("[O>=O]+"), 0,
                            "MO Ints (VO|OO)");
+    global_dpd_->buf4_print(&I, "outfile", 1);
     global_dpd_->buf4_sort(&I, PSIF_LIBTRANS_DPD, rsqp, ID("[O,O]"), ID("[O,V]"), "MO Ints (OO|OV)");
     global_dpd_->buf4_close(&I);
```

You can see the results of the print statements as pre.txt and post.txt respectively at https://gist.github.com/JonathonMisiewicz/7d4e3ac7eee98b8dcc94d74f2d60f378.

I noticed the row and column indices were transposed but everything else looked fine, suspected the transpose was the problem and checked with @jturney. Maybe there was some miscommunication here? I thought he agreed with me that one of the two codes using the wrong index convention was the problem.

Based on what you've been saying about byte counts, it looks like the problem is elsewhere. Maybe the code is supposed to do the transposing? I'll admit that I'm very shaky on reading this code. The only documentation I've been able to find on LIBPSIO is more than 20 years old, and from that, all I can make out about the purpose of LIBPSIO is that it replaced some other I/O system. On second look, it is strange that the non-zero pqnum/rsnum changes from 25 to 26. Is that supposed to happen?

**Comment by amjames** [comment]
@JonathonMisiewicz [Here](http://vergil.chemistry.gatech.edu/psi/devel/libs/libdpd.html) is a link to the most recent official DPD documentation. You can find a table within that indicates what the significance of the PQ/RS numbers are.

Those two print statements in the diff you showed look exactly as I would expect them too. The row (pq) and coll (rs) numbers flip because you have flipped the arguments to `buf4_init`.
