### ISSUE TITLE
reference_wavefunction() is broken

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#1478]
As discussed in #1475, the wave function returned by ```reference_wavefunction``` appears to return a correlated density. This should not happen: the reference wave function should return the reference density.

**Comment by dgasmith** [comment]
In general, I don't think this is broken for all Wavefunctions. It appears the specific issue is CCSD at the moment.

Short term this can be fixed by creating deep copying the reference function rather than shallow copy. However, there is some thought that we would remove this entirely and we can cache the SCF wavefunction in other ways.

**Comment by amjames** [comment]
If this is only affecting CC wfn's then a full deep copy could be avoided. Instead, just deep copy the density in `ccdensity` before overwriting with the correlated density. 

Note that the signature `psi::ccdensity::ccdensity(std::shared_ptr<Wavefunction> ref_wfn,...)` is misleading because at this point that function is passed the `psi::ccenergy::CCEnergyWavefunction`.

That should work for a short term fix, however I agree that we have to come up with a better way to cache the SCF wavefunction quantities long term.

**Comment by hokru** [comment]
This appears to be specific about the `ccenergy` module reference wavefunction that was fixed by #1962. Closing.
