### ISSUE TITLE
Fails to find libint: it doesn't provide .cmake or .pc files

### ISSUE THREAD

**Issue by yurivict** [psi4/psi4#1589]
```external/upstream/libint/CMakeLists.txt``` has this line:
```
find_package(Libint 1.2.0 CONFIG QUIET COMPONENTS ${MAX_AM_ERI})
```

I have the latest version of libint installed: libint-1.2.1_1 (also see here https://repology.org/project/libint/versions).

I changed this line to the latest version:
```
find_package(Libint 1.2.1 CONFIG QUIET COMPONENTS ${MAX_AM_ERI})
```
but it fails to find it:
```
-- Suitable Libint could not be located, Building Libint instead.
```

libint-1.2.1_1 doesn't provide .pc or .cmake files, so I am not sure how can it even ever be able to find it through a cmake script like this?

It's undesirable to download and rebuild libint when the package is available.

Please also note that the latest generation of libint is libint2, which does provide ```libint2.pc``` .

**Comment by loriab** [comment]
There have been many buildsystem updates to Libint1 since 1.2.0, and it's always an option to build it through libtool _or_ cmake. Psi4 will only detect a CMake build. Libint takes a while to compile, and I definitely agree one would wish to detect a pre-built. I've added the `.pc` file to Libint1 here (https://github.com/evaleev/libint/pull/120) so that a CMake build of Libint is detectable by both downstream CMake or libtool. Normally what packagers do when they've got a libtool-built Libint already packaged and want Psi to detect it is to patch the build so CMake sees it https://src.fedoraproject.org/rpms/psi4/blob/master/f/psi4-b167f473-fedora.patch .

Yes, Libint2 is known to us. As it requires extra dependencies and isn't expected to to be faster, we won't be updating.

**Comment by loriab** [comment]
I agree that a CMake Libint1 build failed to be least common denominator for downstream on two fronts: (1) no `.pc` files and (2) no `libr12` library. I've fixed the first one Libint-side. Second I don't particularly have time for and can't do anyways until someone volunteers to test the resulting `libr12`. The one-line patch on the packager side to use the libtool build with Psi4 is above. Closing.
