### ISSUE TITLE
Molden output for CI not correctly documented

### ISSUE THREAD

**Issue by tovrstra** [psi4/psi4#1638]
I overlooked this when previously checking the documentation. The CI/MCSCF example from the following page does not work: http://www.psicode.org/psi4manual/1.3/molden.html. A minor issue is that `'ci'` is not a valid method. The second problem is that the `wfn.opdm` method should be replaced by `wfn.get_opdm`. (A useful example can be found in the source tree: `tests/molden2/input.dat`).

I believe this is a correct example, but it would be nice if someone more familiar with the CI code could confirm and explain a few questions below. (I would be happy to make a PR with updated documentation.)

```
molecule {
0 1
H 0.0 0.0 0.0
H 0.0 0.0 1.0
}

set basis cc-pVTZ
set opdm true

E, wfn = energy('fci', return_wfn=True)
molden(wfn, 'no_root1.molden', density_a=wfn.get_opdm(0, 0, "A", True))
```

Main questions:
- Is this example correct? It runs and seems to give sensible results.
- Which levels of theory (other than FCI and CASSCF) can be used? (CISD gives an error: `AttributeError: 'psi4.core.Wavefunction' object has no attribute 'get_opdm'`.)
- How can one use the first two arguments to `get_opdm`? They are documented here in the source code: https://github.com/psi4/psi4/blob/880f87f5b2765ed00efaf6dd63c406b574c40157/psi4/src/psi4/detci/ciwave.h#L141 but setting anything else than `0, 0` for the first two arguments does not work: `Fatal Error: CIWavefunction::get_opdm: Requested OPDM was not formed!` I tried to add `set tdm true`, but this had no effect. (Also, I guess writing out a transition density matrix to a Molden file makes little sense.)
- When the last argument is `True`, does this mean the frozen-core is included in the density matrix?

**Comment by dgasmith** [comment]
Yes, I think what you show should work as `molden` excepts a MO matrix.

Since we can compute CISD in multiple ways this gets a little tricky as only the DETCI module returns a CIWavefunction, the best way to check for this is `isinstance(wan, psi4.core.CIWavefunction)` I believe.

By default FCI only computes the ground state, so only the `(0, 0)` OPDM is available. Additional states (roots) can be computed by setting the `num_roots` to a value other than 1 and the `(n, n)` OPDMs will be available via `get_opdm`. `tdm True` creates all possible `(n, m)` OPDMs.

The `True` in `wfn.get_opdm(0, 0, "A", True)` is needed for non FCI wavefunctions as a `False` value will return a matrix of size `nact x nact`. Setting this to `True` will return a matrix the size of `nmo x nmo` with the inactive space set to the diagonal and the virtual space set to zero.

Before coffee has quite kicked in yet, hopefully this makes sense.

**Comment by tovrstra** [comment]
Totally makes sense to me and works well. Thank you for your helpful comments! I'll make a PR with a docu update.
