### ISSUE TITLE
bsse_type='cp' does unnecessary monomer-basis calculations

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1691]
Psi4 1.4a2.dev66,      Git: Rev {master} 6e67529

see topic. Only recently noticed this. It used to do only dimer-basis calculations.

```
molecule ne2 {
    0 1
    Ne 0 0 0
    --
    0 1
    Ne 0 0 2
}
set scf_type pk
energy('scf/3-21G', bsse_type="cp")
```

output:
```   ===> N-Body Interaction Abacus <===
        BSSE Treatment:                     cp
        Number of 1-body computations:     4
        Number of 2-body computations:     1
```

**Comment by alenaizan** [comment]
Yes, I updated this to compute monomer-basis calculations. They are needed for correct counterpoise-corrected total energies. Maybe we should not compute them when the user requests interaction quantities with the option `return_total_data=False`. A new Psi4 driver is coming. It should have better control over which terms of the expansion are computed.

**Comment by hokru** [comment]
Not sure I follow. Monomer-basis results are not needed for CP-corrected interaction energies.
Now it seems the monomer-basis energies are calculated but not used at all in the final output.

**Comment by alenaizan** [comment]
I believe it is used in computing counterpoise-corrected total energies not interaction energies, which is for a dimer `E = E^{AB}_{AB} - E^{AB}_{A} - E^{AB}_{B} + E^{A}_{A} + E^{B}_{B}`. The table at the end of the output which prints counterpoise corrected energies should have the correct interaction and total quantities.

**Comment by hokru** [comment]
The new `bsse_type='cp'` does what `bsse_type=['cp','nocp']` used to do, calculation wise, except the `nocp` interaction energies are not reported. 

To safe computer time it was useful to only calculate the dimer-basis part and get CP-corrected interaction energies directly.

**Comment by alenaizan** [comment]
I agree we should allow the user to drop the computation of monomer-basis calculation. However, total counterpoise-corrected energies are sometimes needed, e.g. when doing geometry optimization, and so they should be computed when needed.

**Comment by dgasmith** [comment]
Before the release of 1.4 we should ensure that these monomer calculations are not included by default and are opt-in only to keep currently released behavior.

**Comment by PeterKraus** [comment]
Alright, I'm having a go at this - fixing the number of calculations is trivial, but knowing what we want to print is not.

For the `bsse_type=["nocp"]` case, we want to calculate `AB in AB`, `A in A` and `B in B`. We can print the total no-CP energy at nbody(1) = `A in A` + `B in B`, nbody(2) = `AB in AB`, and the interaction energy is the difference of the two.

For the `bsse_type=["cp"]` case, we want `AB in AB`, `A in AB` and `B in AB`. We _cannot_ print any total CP energies, because for those we need the monomer terms. But we _can_ print the CP interaction energy. In my view, the table as printed by the driver currently is wrong for `bsse_type=["cp"]` case. Also, the `return_total_data` keyword has no effect on the returned energy, or the "CURRENT ENERGY" in the returned `wfn` object.

For the `bsse_type=["cp", "nocp"]` case, we want to calculate `A in A` and `B in A` in addition to the above. This allows us to calculate the counterpoise corrections to the total energies for A and B, and by extension, to AB.

I think the table should be modified so that only total energies are printed in the total energies column, which means printing an empty column for `bsse_type="cp"`, but a populated column for `bsse_type=["cp", "nocp"]`. Also, it might make sense if `return_total_data="True"` with `bsse_type="cp"` triggered calculation essentially equivalent to `bsse_type=["cp", "nocp"]`, or at least printed an error that total energies are not available with only `bsse_type="cp"`.

Thoughts?

**Comment by loriab** [comment]
I think we do want `return_total_data=True, bsse_type="cp"` to internally convert to `bsse_type=["cp", "nocp"]` in order to satisfy correctly the `return_total_data`.

**Comment by CDSherrill** [comment]
@PeterKraus thanks for this helpful update.  This will eliminate some redundant computations, which is helpful (especially for people who just want a dimer IE).  Thanks also for testing the gradients.

I have one quibble with the user interface.  What happens if a user tries to run an optimization but only uses bsse_type=['cp']?  The monomer energies in the monomer basis sets need to be calculated so that we have total energies... trying to optimize the interaction energy only, without some special constraints in the optimizer to keep the monomers frozen (a capability we do not have automated right now), will give garbage.  99% of users will not be clever enough to realize that if they want the counterpoise-corrected geometry of a dimer, they need to include "nocp" in their bsse_type list.  Can you solve this by forcibly adding monomers (and perhaps option "nocp" internally, if you want) when an optimization is requested?  I would like to head off a lot of posts on the user forum about CP-corrected optimizations that went wrong :)

Minor question about printing.  I agree that things that are not total energies should not be printed in the total energy column.  However, what are you doing if bsse_type='cp'?  Leaving it blank?  That might cause a problem for anyone trying to scrape the output file.  Should there be something there, like "n/a" or something?

Also, when you do print the total energy, it's the same total energy as before your PR, right?  The total energy of a dimer should be E_AB(AB) minus the Boys-Bernardi estimate of the BSSE, which is [E_A(AB) - E_A(A) + E_B(AB) - E_B(B)]

**Comment by PeterKraus** [comment]
Thanks for the feedback, @CDSherrill, I'll fix it tomorrow. One quick point:

There are two ways to fix the geometry optimization issue:
- we can toggle `return_total_data=True` if `ptype != 'energy'` (meaning total G/H are calculated and returned)
- or we can add the monomers-in-monomers if `ptype != 'energy'` (meaning E/G/H are available, but interaction energies are returned).
I don't think either of those is consistent with 1.3.2's behaviour, though!

**Comment by CDSherrill** [comment]
I don't think I understand what the difference in the program behavior would be if you chose one solution over the other, so I'm not sure.  Unless the optimizer needs to get handed the total energies and gradients via a return of the N-body function that happens when return_total_data=True, in which case the first solution would seem to be easier.

**Comment by loriab** [comment]
@psi-rking @AlexHeide ping

I don't know if I've loaded all the details, but a table like below may organize discussion (or at least provide something to write a test against) even if my rightmost column is wrong.

cmd | bsse_type | return_total_data | performs
---- | ---- | ---- | ----
energy | cp | true | 5 ene, return CP tot
energy | cp | false | 3 ene, return CP IE
energy | cp, uncp | true | 5 ene, return CP tot
energy | cp, uncp | false | 5 ene, return CP IE
gradient | cp | true | 5 grad, return CP tot
gradient | cp | false | 3 grad, return CP IE
gradient | cp, uncp | true | 5 grad, return CP tot
gradient | cp, uncp | false | 5 grad, return CP IE

users aren't calling `gradient(... bsse_type)` directly -- either `optimize()` or an optimizer program are making that call, and I think the latter can hard-wire the correct choice they need (5th line?).

**Comment by CDSherrill** [comment]
If the table from @loriab  is how the program is behaving, then yes, it would seem to be ok if optimize() defaulted to return_total_data True.  However, shouldn't we also make this the default behavior with gradient(), just in case anyone did call it with cp?  (or is that somehow not possible)?

**Comment by loriab** [comment]
the CP IE gradient is correct from 3 SP gradients, right? and nothing labeled CP total gradient or CP total energy is printed from line 6. so I'd think line 6 would be ok without altering the defaults.

if the user was interested in total energies/gradients, he'd add `return_total_data=True` for line 5 and get the 5 SP gradients and correct CP total gradient and CP total energy.

maybe I'm supposing incorrectly that users easily notice when IE vs tot_E returned is not what they intended.

**Comment by AlexHeide** [comment]
I know next to nothing about nbody, I just did a quick keyword search to see if there is anything optking could set and didn't find anything. I'll also confess to not entirely following the thread so this could be completely unhelpful.

optking gave up all non schema communication so in order for us to "easily" set `return_total_data` it would either need to be:

1. A keyword we / the user can set in an `AtomicInput`
2. An optional parameter in  `psi4.run_qcschema()` - optking would likely force the user to use the `optking -> psi4` path instead of  the `optking -> qcengine -> psi4` path to make sure this gets set correctly.

Otherwise optking would either need to:
1.  go back to making gradient calls directly - at least if needed
2. Make the user go through `psi4.optimize()` where `gradient(..., bsse_type=[args])` might get called explicitly - I don't know what is envisioned for this.

I would hope a user would figure out that the energy is several orders of magnitude off, but regardless of the solution, the optimizer could certainly do a sanity check of the energy after the first step. I don't think an IE is ever going to be large enough to be mistaken for the total electronic energy. Optking could check the magnitude of the energy, direct the user to the correct way of performing the optimization and quit so as not to waste computer time.

**Comment by loriab** [comment]
fear not, we've got a sol'n for item 1 -- `AtomicInput.keywords["function_kwargs"]` https://github.com/psi4/psi4/blob/master/psi4/driver/schema_wrapper.py#L534 . psi passes these on to the e.g., `energy()` call rather than to `psi4.set_options()`.

**Comment by PeterKraus** [comment]
OK I've checked both energies and gradients. The returned quantities are what they should be, but the number of calcs was not - but it is with #2221. I am attaching the results below:

cmd | bsse_type | return_total_data | should perform | 1.4a2.dev923 | master + #2221
---- | ---- | ---- | ---- | ---- | ---- |
energy | cp | true | 5 ene, return CP tot | 5 | 5 |
energy | cp | false (default) | 3 ene, return CP IE | **5** | **3** |
energy | nocp | true | 3 ene, return tot E | 3 | 3 |
energy | nocp | false (default) | 3 ene, return IE | 3 | 3
energy | cp, nocp | true | 5 ene, return CP tot | 5 | 5 |
energy | cp, nocp | false (default) | 5 ene, return CP IE | 5 | 5 |
gradient | cp | true | 5 grad, return CP tot G | 5 | 5 |
gradient | cp | false (default) | 3 grad, return CP IE G | **5** | **3** |
gradient | nocp | true | 3 grad, return tot G | 3 | 3 |
gradient | nocp | false (default) | 3 grad, return IE G | 3 | 3 |
gradient | cp, uncp | true | 5 grad, return CP tot G | 5 | 5 |
gradient | cp, uncp | false (default) | 5 grad, return CP IE G | 5 | 5 |

I am in favour of switching the default `return_total_data` from `False` to `True` when gradients or Hessians are requested from `nbody_gufunc`. I've checked that this also correctly propagates to finite difference gradients, meaning that:

```
gradient( ..., return_total_data = True)
gradient( ..., return_total_data = True, dertype = 0)
gradient( ..., )
gradient( ..., dertype = 0)
```

all return the gradient of the total energy (CP-corrected, if requested). The interaction energy gradient can be asked for using `return_total_data = False`, and works also for `dertype=0`.
