### ISSUE TITLE
ECP gradient terms failed to converge

### ISSUE THREAD

**Issue by TermeHansen** [psi4/psi4#1704]
this example with Bismuth

```
molecule mol {
 0 1
O          2.92770        0.06060       -0.10810
Bi         2.42590       -1.82250        0.36000
O          1.18530       -0.57340        0.62950
C          0.28120        0.33690        0.82590
C          0.90790        1.68810        0.95220
O         -0.93190        0.11800        0.90030
H          1.58840        1.65300        1.79070
H          0.16190        2.44800        1.16540
H          1.41360        1.98520        0.04650
 }

set reference rks
set scf_type df
set basis def2-SV(P)
E = optimize('pbe')

```
fails to add ECP gradient terms.

from log output:
```
  ==> Adding ECP gradient terms (computed numerically) <==
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
Failed to converge:
```

Which I guess is leading to the failure of the optimization in the end.

**Comment by JonathonMisiewicz** [comment]
What version are you using? I'm running on commit dd6b45b (updated May 7), and I can't reproduce this. Two geometry iterations finish successfully before SCF convergence fails.

The SCF convergence failure appears to the fault of my old "friend", orbital guesses not correcting for changes in the overlap matrix when reading in orbitals for the initial guess... The initial guess from orbital read is terrible, and I see a large change in geometry for the update where the failure happened. The previous geometry, which also reads orbitals but from a much more similar geometry, seems to work fine.

**Comment by loriab** [comment]
I was going to ask the same thing. The ECP code has a primary and a fallback, and it prints that "Failed to converge" in the primary, even when the fallback proceeds to successfully complete. We suppressed that printing because it was misleading around late 2017. So Jonathon's diagnosis is the path to follow.

**Comment by TermeHansen** [comment]
I'm using tags/v1.3.2, and are you sure that line was removed - isn't it this:
https://github.com/psi4/psi4/blob/d7529df57c2815cfb43a88d9b739c94c3a2322c4/psi4/src/psi4/libmints/ecpint.cc#L492

and yes after 2 iterations I get SCF convergens problems on this exact input. Just to be sure, so my problem here is not related to the ECP code, but just standard SCF convergens problems?

**Comment by TermeHansen** [comment]
thanks for the hitn in the rigth direction Jonathon. adding:

```
set intrafrag_step_limit_max 0.5
set DYNAMIC_LEVEL 1
```
makes it converge in 16 steps with no SCF problems (due to too large steps)

**Comment by JonathonMisiewicz** [comment]
Glad to hear you were able to converge the geometry.

I'll leave the ECP logging question to Lori, but I can speak to the orbital reading issue. The issue here is one of the two improvements to the orbital read/guess system that I need for my own research, so the permanent fix is high priority for me. However, the relevant code is intimately tied up with a part of the code that is currently unergoing a large rewrite, so I won't be able to start on the fixes until that's done.

**Comment by JonathonMisiewicz** [comment]
Closed. The geometry convergence issue is really part of #758.
