### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4#1793]
Commits prior to PR 65c0921213e6fe2979733f6c316915f79051f558 seem to have broken some tests that I suspect are not checked by our CI system:
```
	255 - ocepa-freq1 (Failed)
	259 - ocepa2 (Failed)
	260 - ocepa3 (Failed)
	273 - omp3-2 (Failed)
	278 - omp3-grad2 (Failed)
	320 - pywrap-checkrun-rhf (Failed)
	321 - pywrap-checkrun-rohf (Failed)
	322 - pywrap-checkrun-uhf (Failed)
```

The following are known to fail due to poor convergence of the occ module
```
	260 - ocepa3 (Failed)
	263 - omp2-3 (Failed)
	274 - omp3-3 (Failed)
```

The error message for `pywrap-checkrun-rhf` is also consistent with convergence issues:
```
  45     -75.0144633211      0.00e+00       1.85e-05         1.42e-04        3.01e-15
  46     -75.0144633211      0.00e+00       1.85e-05         1.42e-04        1.73e-15
  47     -75.0144633211     -1.42e-14       1.85e-05         1.42e-04        9.95e-16
  48     -75.0144633211      0.00e+00       1.85e-05         1.42e-04        5.65e-16
  49     -75.0144633211      0.00e+00       1.85e-05         1.42e-04        3.27e-16
  50     -75.0144633211      0.00e+00       1.85e-05         1.42e-04        1.88e-16
 ======================== OCEPA IS NOT CONVERGED IN 50 ITERATIONS ============
Traceback (most recent call last):
  File "/Users/fevange/Source/psi4/objdir-Debug/stage/bin/psi4", line 331, in <module>
    exec(content)
  File "<string>", line 54, in <module>
  File "/Users/fevange/Source/psi4/objdir-Debug/stage/lib/psi4/driver/driver.py", line 711, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)
  File "/Users/fevange/Source/psi4/objdir-Debug/stage/lib/psi4/driver/procrouting/proc.py", line 752, in select_olccd_gradient
    return func(name, **kwargs)
  File "/Users/fevange/Source/psi4/objdir-Debug/stage/lib/psi4/driver/procrouting/proc.py", line 2147, in run_occ_gradient
    occ_wfn = core.occ(ref_wfn)
RuntimeError:
Fatal Error: OCC iterations did not converge
Error occurred in file: /Users/fevange/Source/psi4/psi4/src/psi4/occ/occ_iterations.cc on line: 363
The most recent 5 function calls were:
Printing out the relevant lines from the Psithon --> Python processed input file:
    for method in Earray:
       water.reset_point_group(sym)
       water.fix_orientation(True)
       water.update_geometry()
       banner('Testing %s' % (method))
-->    G, wfn = gradient(method, return_wfn=True)
       ans = wfn.energy()
       print('%16s\t%s\t%s\t%s' % (method, water.schoenflies_symbol(), variable('CURRENT ENERGY') - ans, ans))
       clean()
    print('  Checking gradient methods (excited state) ...')
    Earray = [
    Psi4 stopped on: Friday, 31 January 2020 05:10PM
    Psi4 wall time for execution: 0:00:06.47
```

**Comment by JonathonMisiewicz** [comment]
Thanks for making this into a written issue. This was discussed on Slack over a week ago, but not everyone may have seen it.

All those test failures trace back to a "delicate" part of the OCC module. It has very slow orbital convergence. I [updated the default orbital convergence criteria in OCC to be the same as in DFOCC](https://github.com/psi4/psi4/pull/1772/commits/896a7c22be5c72542b8773ca2a1b9164dee1fc2a), and for all the failing test cases, OCC simply can't converge the orbitals that tightly. You can see the issue about the OCC problem [here](https://github.com/psi4/psi4/issues/1777). It traces back to OCC not coupling orbital and T2 amplitude DIIS, when in my experience, coupling them is crucial for good convergence.

I'm in the process of fixing that, but it's slow. A lot of junk in the OCC module needed to be cleaned out to make the code less confusing before I can start making the actual fix. If you want to move that along, you can help by reviewing [the current cleanup PR](https://github.com/psi4/psi4/pull/1789). I wanted to wait to write the next and final PR in the series until that one was accepted, but I may need to start on that now. Until that final PR gets in, we don't have conda builds and certainly can't have the next release.

As you're probably wondering about this, these changes are also necessary for a paper I want submitted before I leave CCQC. While I'm quite unhappy these changes needed to be done, that they are made is useful for me personally.

**Comment by JonathonMisiewicz** [comment]
`dfmp2-4` and `opt-irc-2` are currently failing as well. `dfmp2-4` just needs to adapt to syntax from PR #1789 and is easily fixed. `opt-irc-2` fails because the last IRC point does not have the expected energy. I suspect #1804 instigated this, but the true culprit is that optking cannot accurately say when the IRC converged.

The IRC report when I run the test is

```
@IRC ----------------------------------------------
@IRC            ****      IRC Report      ****  
@IRC ----------------------------------------------
@IRC  Step    Energy              Change in Energy 
@IRC ----------------------------------------------
@IRC    0   -92.810710767266    -92.810710767266
@IRC    1   -92.811778450261     -0.001067682995
@IRC    2   -92.814803984808     -0.003025534547
@IRC    3   -92.819270546903     -0.004466562095
@IRC    4   -92.824389153679     -0.005118606776
@IRC    5   -92.829383508727     -0.004994355049
@IRC    6   -92.833903705977     -0.004520197249
@IRC    7   -92.838018066774     -0.004114360797
@IRC    8   -92.841889747803     -0.003871681030
@IRC    9   -92.845625951635     -0.003736203832
@IRC   10   -92.849260395757     -0.003634444122
@IRC   11   -92.852777598444     -0.003517202687
@IRC   12   -92.856140015989     -0.003362417545
@IRC   13   -92.859308223013     -0.003168207024
@IRC   14   -92.862250220465     -0.002941997452
@IRC   15   -92.864943075409     -0.002692854944
@IRC   16   -92.867368006399     -0.002424930990
@IRC   17   -92.869505711996     -0.002137705597
@IRC   18   -92.871329201900     -0.001823489904
@IRC   19   -92.872798961306     -0.001469759406
@IRC   20   -92.873862613736     -0.001063652429
@IRC   21   -92.874464128325     -0.000601514589
@IRC   22   -92.874561860949     -0.000097732624
@IRC   23   -92.874559174537      0.000002686412
@IRC   24   -92.874584188151     -0.000025013614
@IRC   25   -92.874518478044      0.000065710108
@IRC   26   -92.874584083068     -0.000065605025
@IRC   27   -92.874584016106      0.000000066962
@IRC ----------------------------------------------
```

Compared to the reference from 2017, the first step has an energy difference on the order of 1e-4, and the energy difference remains at or below 1e-4 up to step 22. If I had to guess, this is due to PR #1663, where I fixed an error in the initial displacement for the IRC. At step 22, the geometry is very close to the minimum, so the next step ends up raising the energy. The two IRCs then bounce around, with the reference IRC bouncing in the fourth decimal place and the current IRC bouncing in the fifth. This is enough bounce for the final energies to be outside convergence criteria.

Unless somebody has the time and drive to improve the IRC termination cutoff in C-Optking, I recommend changing the reference value for now and investigating this in Py-Optking, whenever that comes out.

Meanwhile, I have most of the occ tests fixed locally, but `ocepa-grad2` is proving more difficult. My Psi4Numpy converges with no problems, so the issue probably isn't in the coupled-DIIS approach itself... My current guess is that it's the fact that the "residuals" `occ` throws into DIIS aren't the residuals but the residuals divided by the MPPT-like denominators from the standard amplitude update algorithm.
