### ISSUE TITLE
Allow PCM to be set via schema 

### ISSUE THREAD

**Issue by jthorton** [psi4/psi4#1986]
Currently, PCM settings can not be set via QCEngine using the schema interface, passing a task like this from QCEngine results in an error 
```python
{'schema_name': 'qcschema_input',
 'schema_version': 1,
 'molecule': Molecule(name='H2O', formula='H2O', hash='941bd29'),
 'driver': 'energy',
 'model': {'method': 'SCF', 'basis': 'sto-3g'},
 'protocols': {'wavefunction': 'orbitals_and_eigenvalues'},
 'keywords': {'scf_type': 'df',
  'pcm_scf_type': 'total',
  'pcm': {'Units': 'Angstrom',
   'Medium': {'SolverType': 'IEFPCM', 'Solvent': 'Water'},
   'Cavity': {'RadiiSet': 'UFF',
    'Type': 'GePol',
    'Scaling': False,
    'Area': 0.3,
    'Mode': 'Implicit'}}}}
```
as it tries to pass the dictionary of settings to the `core.set_global` function. 

Extending the `set_options` function [here](https://github.com/psi4/psi4/blob/5de566ed7d4bf51816c673c4ea1def449e4e8618/psi4/driver/p4util/python_helpers.py#L423) to handle the `pcm` keyword should fix this issue.

tagging @loriab following the slack discussion.

**Comment by loriab** [comment]
This should be fixed in #2003 in that you can pass the keywords via `PCM__INPUT`. QCFractal runs in psiexe mode (new instance each time), so that's fine. If one wanted to run multiple psi4+pcmsolver in psiapi mode (one `import psi4` or `extras["psiapi"] = True` in qcschema), there's still a problem, filed https://github.com/PCMSolver/pcmsolver/issues/182
