### ISSUE TITLE
frozen core problem for system with Na and I

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#2012]
The following input, given to me via email, gives a 'bad' dMP2 correction for SAPT:
```
      delta HF,r (2)              -18.53850185 [mEh]     -11.63308554 [kcal/mol]     -48.67282991 [kJ/mol]
      delta MP2,r (2)             141.03839795 [mEh]      88.50293088 [kcal/mol]     370.29626281 [kJ/mol]
```

```
molecule {
0 1
 F                  0.00000000    0.00000000    2.96216000
 I                  0.00000000    0.00000000    0.96704400
--
0 1
 C                  0.00000000    0.00000000   -2.52999200
 N                  0.00000000    0.00000000   -1.35165800
 Na                 0.00000000    0.00000000   -4.84283500
units angstrom
no_reorient
symmetry c1
}
memory 20 GiB
set {
    basis def2-TZVP
    freeze_core true
}
energy('sapt2+dMP2')
energy('mp2',bsse_type=['nocp'])
```

The issue is reproducible for MP2/CCSD post-SCF methods. It is not directly `DF` nor `ghost` atom related. (besides a possibly small error due to https://github.com/psi4/psi4/issues/1968). And not a module specific issue.

Using different ECPs (LANL2DZ) or an all electron basis (x2c-SVPall, no rel. effects.) with global `FC=on` seems to give 'better' results in the sense that MP2 interaction energy is negative.

One, and perhaps only, issue is `frozen_core`.
Turning `FC = off` only for the supermolecular MP2 part gives OK results. For the NaCN fragment we are freezing 10 electrons, while e.g. ORCA is freezing only 3. 
At least for this case, freezing the Ne-shell by default for Na is not a good choice.

Tagging @PeterKraus.

`freeze_core -2` makes the SAPT part crash because sth goes wrong for the `IF` fragment (fragment A):
```
    FOCC A     = 18446744073709551611
    FOCC B     =         1
```

**Comment by CDSherrill** [comment]
I think freezing 1s, 2s, and 2p for Na is what we decided on for the
default behavior, but I agree that it is quite iffy and one should really
be freezing only 1s.  Didn't we have a "FREEZE_CORE MIN" option a while
back that understood these kinds of rules?  That makes more sense to me
than this new (to me) "FREEZE_CORE [0,-1,-2, ...]" etc.... I don't see how
that's supposed to be a useful set of options, because the behavior needs
to be different for Na than it is for the other elements.  (The manual
tells me that -1 is supposed to freeze the previous row/noble atom, -2 does
the next-previous row, etc. .... It seems to me that the only time we ever
want to do -2 is for specific elements, never for all atoms in an entire
molecule).

I suppose also providing NUM_FROZEN_DOCC doesn't work because it would need
to be different for fragment A than Fragment B.

**Comment by susilehtola** [comment]
IIRC a common problem with alkali and alkaline elements is that the core levels can lie higher up in energy than the valence electrons in other species. Defining the core levels via e.g. population analysis ([Rassolov et al, Chem. Phys. Lett. 350, 573 (2001)](https://doi.org/10.1016/S0009-2614(01)01345-8) can be used to avoid this problem.

**Comment by PeterKraus** [comment]
I think there are two issues here: there is a bug in the code, and the interface does not allow for useful core freezing.

As for the bug, if we set `freeze_core = FC`:

```
FC | C  N  Na | F  I  (ECP)
-1 |  2  2 10 |  2 36 (28)
-2 |  0  0  2 |  0 18 (28)
```
- for `freeze_core = -1`, the code "correctly" freezes 7 pairs on NaCN, 5 pairs on FI in addition to 14 pairs in I's ECP, and for the dimer it's 12 pairs.
- for `freeze_core = -2`, the code "correctly" freezes 1 pair on NaCN, 0 pairs on FI, but for the dimer it incorrectly freezes 0 pairs as the ECP has 14 pairs and the `-2` option would like to freeze only 10 pairs (1 on Na and 9 on I).

As for the second problem, the most obvious way would be to allow the user to pass in a dictionary with `"element": -shell` and/or `"element": frozen_pairs` to specify exactly what to do.

**Comment by hokru** [comment]
The NBody driver will need a similar fix as the SAPT driver.

**Comment by PeterKraus** [comment]
Hmm, I can reproduce this using just `energy("mp2/cc-pvtz", bsse_type="cp")`. However, I don't think the issue here is the same as for SAPT (where the number of frozen core orbitals for a dimer was not the sum of the frozen core orbitals for monomers): here we freeze 7 orbitals on NaCN (2+2+10 el), 2 orbitals on F2 (2+2 el), and 9 on the dimer. 

The problem is of course freezing those 10 electrons on Na. Currently the only way around that is to use `freeze_core -2`, which only freezes 1 orbital in NaCN and 1 orbital in the dimer, or do the calculations separately, as we have no way of specifying per-monomer numbers of frozen orbitals, yet.

**Comment by hokru** [comment]
True, the number of core orbitals is correct. Just too many are frozen. Opening a fresh PR for the alkali metal issue and closing this one.
