### ISSUE TITLE
PSI4 cmake build does not seem to check if python development is installed.

### ISSUE THREAD

**Issue by AlexB67** [psi4/psi4#2060]
Hello, 

When building psi4 from source and python development packages are not installed compilation fails (Linux Fedora). Once I installed python-dev all complete successfully.
The complaint from source files  was along the lines

#include<Pyhon.h> not found and then aborts during compilation,

Ideally (IMO)  cmake should check during the configuration phase if all relevant and required package are  installed and abort if not. Perhaps there are more dependencies, but I may already have had them already installed. 

I no longer have the build machine to replicate all the steps, but I suspect amending the root cmake adding find_package with python-dev as REQUIRED (or perhaps via pkg_config) 
and abort immediately during the cmake configuration phase if not found, not halfway through the compilation when running make.

Perhaps this will also help.

https://cmake.org/cmake/help/latest/module/FindPython.html

Cheers.

**Comment by jturney** [comment]
I'm kind of surprised this hasn't been caught sooner.  Looks like we're using a decently old version of a file similar to the one that you linked to.  Might be time to upgrade the checks to the modern style.

**Comment by loriab** [comment]
For history, back when Python detection in cmake was very broken (exe and lib weren't matching pair), numpy made their own alternate find python cmake file and pybind11 used numpy's and psi4 used pybind11's. I hear cmake has totally rewritten theirs, and pybind11 is now amenable to either (https://github.com/pybind/pybind11/pull/2370, I think). So, yes, upgrade now reasonable. Note that psi, in turn, installs the python finder module so that plugins can use it.

**Comment by AlexB67** [comment]
I suppose I should add my setup is kind of unusual in that I don't develop with or for python, only C++, so never have that stuff installed. So it caught me out for a minute, but easy to fix. Not critical by any means, but If one were a stickler for good cmake practices code compilation should never fall over because of cmake missing dependency checks, 

Perhaps I'll try and port psi4 build to meson one day .. famous last words. :D
