### ISSUE TITLE
Undocumented `DETCI` Convention

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2075]
**Summary**: `detci` seems to interpret the wavefunction multiplicity as the M_s, which can lead it to returning wavefunctions of a higher multiplicity than the user would naively expected. Is this expected behavior? If so, this needs to be documented.

**Details**:
The `detci` module is a CI solver that uses iterative methods to converge roots of the Hamiltonian on _some space of determinants_. When it receives a reference wavefunction, the determinants it chooses have the same number of alpha and beta electrons and further obey some excitation constraints. So when a user specifies a multiplicity and constructs a high-spin reference, this procedure guarantees that all converged roots have the same M_s as that solution. _However_, there is no mechanism in place to enforce that the root has the multiplicity/S^2 specified by the user. Often, no explicit mechanism is needed. The root with the same M_s also has the same S^2. But @lcyyork has run into cases where it is not enough. [This topic](http://forum.psicode.org/t/detci-finds-an-extra-excited-state/1729) reports `detci` returning the M_s = 0 component of a sextet when asked to find several excited states starting from the singlet with RHF orbitals. A recent [Forte tutorial](https://github.com/evangelistalab/forte/blob/master/tutorials/ForteCon2020/mcscf/basics.ipynb) (see right before Tip 3) reports another state of the wrong multiplicity when studying the dissociation curve of N2+.

This behavior is not surprising to me. With determinants, you'd only expect to be able to control the M_s, not the total spin. @CDSherrill, is my diagnosis correct? Does this seem like a bug to you, or just a drawback of the determinant basis? With your go-ahead, I'd like to include a warning in the documentation about that, as well as the output file.

**Comment by lcyyork** [comment]
Thank you @JonathonMisiewicz for bringing this up. I think Forte also had this problem long time ago. I don't remember how it's been fixed (all old Forte issues are lost due to the project name change) but I think it is related to this [paper](http://linkinghub.elsevier.com/retrieve/pii/000926148485513X).

**Comment by CDSherrill** [comment]
@JonathonMisiewicz, you're right.  Although it is easy to guarantee the root has the desired M_s, by construction of the determinant space, there is no guarantee that the wavefunction will have the correct S^2.  

I wrote some code to try to handle situations like this.  The user can specify the value of S that they desire (default 0.0 for closed-shell systems).  If they want to guarantee that all guess roots have the same spin as this, they can set `CALC_S_SQUARED TRUE`.  This will then toss out any guess roots with different values of S.  (This is only implemented for `ICORE 1`).  Guaranteeing that the guess roots have the correct S will *normally* mean that the final roots have the correct S, but this is not absolutely guaranteed if numerical issues come up.    

As an example, consider this test case
    
    memory 24 gb
    molecule {
      0 1
      O
      H 1 0.9463
      H 1 0.9463 2 104.575
    }

    set {
      S 0.0
      NUM_ROOTS 6
      qc_module DETCI
    }

    energy('cisd/cc-pVDZ')


This yields 5 roots that look like singlets, followed by something that appears to be a quintet or higher.

    CISD Root 5 energy =   -75.086475681512894

    The 20 most important determinants:

    *   1    0.342614  (  435,  462)  1A1X 2A1X 3A1B 1B1X 1B2A 4A1A 2B2B
    *   2    0.342614  (  462,  435)  1A1X 2A1X 3A1A 1B1X 1B2B 4A1B 2B2A
    *   3    0.342614  (  670,  434)  1A1X 2A1X 3A1B 1B1X 1B2B 4A1A 2B2A
    *   4    0.342614  (  434,  670)  1A1X 2A1X 3A1A 1B1X 1B2A 4A1B 2B2B
    *   5   -0.342614  (  923,  913)  1A1X 2A1X 3A1B 1B1X 1B2A 4A1B 2B2A
    *   6   -0.342614  (  913,  923)  1A1X 2A1X 3A1A 1B1X 1B2B 4A1A 2B2B
    *   7    0.151981  (  703,  434)  1A1X 2A1X 3A1B 1B1X 1B2B 4A1A 3B2A


Now if we add the option `CALC_S_SQUARED TRUE`

We get some warnings from the program that it is dropping a guess vector because they seem to have the wrong value of S,

    Simultaneous Expansion Method (Block Davidson Method)
    Using 6 initial trial vectors

    (sem_iter): H0block_->H0b_diag[1][1] - H0block_->H0b_diag[2][1] = -0.681031 - 0.681031 = -1.362062 > 1.0E-8
    ...
    Computed <S^2> not as desired, discarding guess


and then the final root now becomes what looks like a singlet

    ==> CISD root 5 information <==

    CISD Root 5 energy =   -75.024974154652114

    The 20 most important determinants:

    *   1    0.637413  (  435,  435)  1A1X 2A1X 1B1X 1B2X 4A1X
    *   2   -0.307807  (  923,  923)  1A1X 2A1X 1B1X 1B2X 2B2X
    *   3   -0.199774  (  436,  434)  1A1X 2A1B 3A1X 1B1X 1B2X 4A1A
    *   4   -0.199774  (  434,  436)  1A1X 2A1A 3A1X 1B1X 1B2X 4A1B
    
I'll see if I can add a few sentences to the documentation to explain this issue.  Thanks for bringing it up.

**Comment by CDSherrill** [comment]
Yeah that unwanted root mentioned above, E = -75.086475619870, is a quintet apparently.  You can get it directly by running this computation.

    set {
      S 2.0
      NUM_ROOTS 1
      qc_module DETCI
      calc_s_squared TRUE
      r_convergence 3
    }

Going directly for high-lying higher spin multiplicities can cause convergence problems (roundoff can cause the program to start to find lower-energy solutions of lower spin multiplicities).  That is why I dropped the convergence criterion.

**Comment by lcyyork** [comment]
Thank you Professor Sherrill @CDSherrill for clarifying the issue. I did not realize the projection can be achieved via the option `CALC_S_SQUARED` until this post. I think it might be useful to set the option to `TRUE` by default if the procedure is cheap to compute.

**Comment by hokru** [comment]
Closed by #2098.

Please re-open if further discussions is needed or make a new issue for related points.
