### ISSUE TITLE
conda/win/2019.1/libiomp5md.lib is a binary file without source

### ISSUE THREAD

**Issue by mbanck** [psi4/psi4#2116]
I don't think `conda/win/2019.1/libiomp5md.lib` should belong in the git repo and/or the tarballs; it is a binary file without source code.

**Comment by loriab** [comment]
Yes, it's a weird one. It is present so that the Azure Windows CI can build a conda-compatible package. That file was missing from upstream conda packages a couple years ago; I should check again. As such, I don't see an easy way to not have the file in the repo and GitHub automatic tarballs. It should be perfectly harmless if you want to prune the entire `conda/` directory, though.

**Comment by mbanck** [comment]
Yeah, but it means we have to repackage the psi4 tarballs because that one is not okay to distribute from a Debian (and probably Ubuntu/Fedora) perspective.

**Comment by loriab** [comment]
Looks like the `.lib` is still missing from defaults `intel-openmp` channel. I'll check the intel channel. I can probably move it to another repo at worst case.
