### ISSUE TITLE
nmopi() and Ca()->coldim() not consistent when linear dependencies present

### ISSUE THREAD

**Issue by edeprince3** [psi4/psi4#2120]
DF-CC freaks out when linear dependencies are present, and i tracked the issue to an inconsistency between reference_wavefunction_->nmopi() and reference_wavefunction_->Ca()->coldim(). The latter has the correct value when linear dependencies are removed. 

Should nmopi() and Ca()->coldim() be consistent in this case?

Minimal input:
```
molecule { 
o 
h 1 1.0
h 1 1.0 2 104.5
}

set {
  basis 'aug-cc-pvtz'
  scf_type df
  cc_type df
  s_tolerance 1e-3
}
energy('ccsd')
```

**Comment by susilehtola** [comment]
IIRC `nmopi_` is the number of molecular orbitals, so it definitely should account for linear dependencies...

**Comment by JonathonMisiewicz** [comment]
I've been able to track this one slightly further: the two agree after the initial computation, but not after the `c1_deep_copy` call. So, yes, this is incorrect behavior. `c1_deep_copy` is bugged.

**Comment by edeprince3** [comment]
OK, more progress:

1. c1_deep_copy calls the RHF constructor, with ref_wfn as an input. ref_wfn has the correct nmopi_. 

2. RHF derives from HF, so when the HF constructor is called, it copies nmopi_ correctly as part of shallow_copy.

3. HF::common_init(), called after shallow_copy() resets nmopi_ to nsopi_. This is the problem.

**Comment by susilehtola** [comment]
Yes, `nmopi_` should never be set to `nsopi_` since the two are not the same.

**Comment by CDSherrill** [comment]
This could explain some bugs we've been seeing lately.

I don't know who introduced "coldim" and why it is needed if we already
have nmopi.

**Comment by JonathonMisiewicz** [comment]
`coldim` isn't a wavefunction attribute. It's the dimension of the columns of the orbital coefficient `Matrix` and is thus a `Matrix` attribute. Redundancy is not the problem here.

The problem is that `nmopi_` is _wrong_. Why it's wrong is a deeper issue. The `common_init` code is called anytime a wavefunction is initialized, and it initializes all orbital spaces by assuming no linear dependences. This is reasonable if you can rely on the linear dependency checking code to be called later and to re-initialize orbital spaces if necessary. If you cannot (as in this case), you get this issue.

My naive vote would be to move orbital space initialization out of `common_init` entirely. If you're initializing from a reference wavefunction that already has those spaces defined, there's no need to touch those. Otherwise, initialize MO spaces only once you have determined the number of MOs, i.e., after [this line](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libscf_solver/hf.cc#L785).
