### ISSUE TITLE
r2SCAN-3c implementation

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#2121]
Forum feature request: http://forum.psicode.org/t/r2scan-3c-for-biomolecules/2066
paper: https://doi.org/10.1063/5.0040021

Will require:
- [x] new gCP code (see also #1898) (LAB edit: #2791)
- [x] DFT-D4  (see also #1710) 
- [x] new basis set
- [ ] tests and documentation

This is also something I'd like personally.

**Comment by susilehtola** [comment]
Basis tracker at https://github.com/MolSSI-BSE/basis_set_exchange/issues/152

**Comment by awvwgk** [comment]
Tracking native QCSchema support for DFT-D4 here: https://github.com/dftd4/dftd4/issues/67

**Comment by hokru** [comment]
I started to work on this.

**Comment by hokru** [comment]
Actually @awvwgk, i am just trying to set the D4 paramters and notice that also the charge-scaling parameters need to be adjusted. Not sure how to do that with the current setup. The QCEngine supports those parameters?

also `r2scan3c` is not recognized by the dftd4 binary?

**Comment by awvwgk** [comment]
Good point, can you check whether https://github.com/dftd4/dftd4/pull/184 addresses this issue for Psi4?

**Comment by loriab** [comment]
I suspect https://github.com/MolSSI/QCEngine/blob/master/qcengine/programs/empirical_dispersion_resources.py#L884 in qcng will need expansion to the extra parameters. And https://github.com/MolSSI/QCEngine/blob/master/qcengine/programs/empirical_dispersion_resources.py#L904 might need populating with the defaults like the `_get_d3_definitions` below since the changes aren't in parameters.toml in dftd4 project. Please let me know if it's not behaving rationally -- the approach made sense for flexibility once upon a time, but I fear the logic is tangled nowadays.

**Comment by awvwgk** [comment]
Seems reasonable to me. We can inject the default parameters for the model parameters (``ga``, ``gc``, ``wf``) when we transform the parameters provided from *dftd4* to the qcng format. It might make sense to add them in the ``parameters.toml`` file in *dftd4* as well, not sure about that yet.
