### ISSUE TITLE
Psi4 1.4rc1 in-core DF is very sensitive to linear dependencies

### ISSUE THREAD

**Issue by jminuse** [psi4/psi4#2211]
Setup: Install Psi4 rc1 for Linux with python 3.9 via the installer from https://psicode.org/installs/v14rc1/

Result: This installation appears to work fine for most molecules, but then has an issue with systems with linear dependencies, specifically when running the in-core DF algorithm. The provided file, `psi4_issue.py`, when run with sufficient memory to run in-core (~40 GB), gives an energy that is low by more than 2 Hartree (should be -1145.943, but gives -1148.711). With scf_type DF and less RAM (thus causing the disk algorithm to run), the energy is correct. Setting s_tolerance to 1e-4 also fixes the problem, at the cost of a little accuracy loss (5e-4 Hartree). I have reproduced this error on several computers, both CentOS and Ubuntu.

The next version, psi4 rc2, does not show this problem. It would be nice to know whether this was deliberately fixed, or might still be around.

`psi4_issue.py`: https://drive.google.com/file/d/1RTSVVfmXwJNpS4CHtvMYOTBU63J8Z85j/view?usp=sharing

**Comment by jminuse** [comment]
I encountered this problem with wB97X-D3BJ/def2-TZVPD, but PBE/def2-TZVPD shows the same, with the added problem that the erroneously low energy is also oscillatory. The psi4=1.4rc2 energy is -1144.303 Hartree, and the psi4=1.4rc1 energy oscillates between -1146.416 and -1146.534 Hartree. 

Once again, this problem is specific to the algorithm that uses in-core AOs. If scf_type DF is provided with less RAM (say 10 GiB) such that it uses disk, the energy is correct (-1144.303 Hartree). I note that PBE requires only 20 GiB to run in-core, and thus might be easier for testing.

**Comment by zachglick** [comment]
Hi @jminuse, thanks for the informative bug report. I'm almost certain that this suspicious 1.4rc1 behavior was fixed in 1.4rc2 by #2139, which tightened the integral screening after we switched integral engines from `libint` to `libint2`. 

Your observations are consistent with what we saw: very wrong and/or oscillatory SCF energies. I also checked that your test case gives a reasonable energy with 1.4rc1 when I set the keyword `INTS_TOLERANCE` to 0, which was the temporary workaround for that bug.

**Comment by jminuse** [comment]
Thank you, I am glad to hear that the issue is known and fixed. For the future, though, I am troubled that this issue exists without warning in a build that looks safe (marked "Stable Release"). How can I be more confident in Psi4 results? Is there a test suite including issues like SCF instability (more exhaustive than `psi4 --test`), that I could use to verify a Psi4 build before running large workflows?

**Comment by loriab** [comment]
Sorry for the unsettling results. For a more extensive test suite, one can run `psi4 --test full` (or long). If building from source, one can also run `ctest` from <objdir>. Unfortunately, this test evaded both of those suites due to showing up for big systems/basis sets.

**Comment by JonathonMisiewicz** [comment]
Disclaimer: There's also a known bug in 1.4rc1 and 1.4rc2 gradients for density-fitted _correlated_ methods. DF-SCF is unaffected. That one slipped through the test suite because we run it in serial (but this is a reminder that we should it set up to automatically run in parallel...) This is fixed in the current developer version.

**Comment by jminuse** [comment]
To avoid bugs of this kind, is it recommended to go back to Psi 1.3.2, or forward to 1.4rc2?

**Comment by JonathonMisiewicz** [comment]
"This kind" is ambiguous.

If "this kind" means the originally reported numerical problems, then either 1.3.2 or 1.4rc2 will work.
If "this kind" means the originally reported numerical problems _and_ the correlated DF analytic gradient threading problem, then 1.3.2.

**Comment by loriab** [comment]
If you can, wait a day or two for rc3.

**Comment by JonathonMisiewicz** [comment]
Since 1.4 is released, I intend to close this after two days if there isn't still an actionable item here.
