### ISSUE TITLE
C++11 support for release 1.0

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#238]
We have [discussed](http://forum.psicode.org/t/c-11-is-it-time/43/3) C++11 support in the past without really finding a resolution. A couple quick points about C++11 support:

Pros (from best to least):
- We already use some C++11 (nullptr, range for, inline class init, etc) 
- Clang/GCC/ICC have fully supported C++11 for a few years
- Initializer lists make quite a few things easier and are heavily featured in Ambit/Tiled Array
- With effort we can remove some of boost (`boost::shared_ptr` -> `std::shared_ptr`)
- Some new std containers like `std::tuple` and `std::array`
- Defaulted constructors and destructors
- _Some_ people use veridic templates
- Remove some custom macros to be a bit more standard (`ULI` -> `uint32_t`).

Cons:
- Not everyone has upgraded their ICC recently
- We might find `auto` everywhere

---
The biggest issue I can see is the older ICC versions will no longer compile Psi4. To mitigate this, there are several options:
 - Use Clang/GCC
 - Use a pre-compiled Psi4 (we offer ICC/MKL versions)
 - If you are a Psi4 contributor you can obtain the Intel Studio suite (linux) for [free](https://software.intel.com/en-us/qualify-for-free-software/opensourcecontributor).
 - If you are a student you can obtain the Intel Composer suite for [free](https://software.intel.com/en-us/qualify-for-free-software/student).

---

Feel free to add to the pro/con list as you see fit.

**Comment by jturney** [comment]
Pros:

- Using ```std::unique_ptr``` to handle memory management instead of pointers directly.
- Aliases instead of ```typedefs```. For example, ```using Dimension = std::vector<size_t>;```

**Comment by bennybp** [comment]
For me the biggest pro of C++11 is that is reduces the amount of code I have to write/maintain/debug.

- Defaulted (and deleted) constructors and assignment operators (mentiond by @dgasmith)
- Liberal use of STL containers and `unique_ptr` means you should rarely have to write a destructor, and often don't have to write a copy constructor
- Constructor delegation


Cons:
- Template programming results in nasty compiler error messages that take experience to figure out
- Overuse of templates, auto, decltype, etc, can result unreadable code
  - This can somewhat be fixed in the new PR workflow. Don't accept PRs which are a mess
- Some C++11 patterns can be intimidating to people who are still learning basic C++

As more libraries require C++11 (I think Ambit, TiledArray, and Cyclops all do), it should generally be embraced, with some reservations.

**Comment by CDSherrill** [comment]
Fewer compilers working is less of an issue as we push more users towards
the binary distribution.  And is only a temporary problem, anyway.  Is icpc
15.0 recent enough to support all the standards we need?

**Comment by ryanmrichard** [comment]
@cdsherrill yes 15.0 is recent enough.  14.0 is the minimum for full C
++11 support based on the internets.

**Comment by bennybp** [comment]
Intel uses GCC libraries, though, so that version has to be taken into account also.

I've only run into a few compiler bugs with Intel 15 and C++11, and those are far from what would be put in Psi4.

**Comment by dgasmith** [comment]
This has been up for awhile now and comments seem very positive. Does anyone have any strong opinions against requiring C++11?

I have been writing new changes to CIWavefunction using C++11 syntax so please speak up soon!

**Comment by robertodr** [comment]
I fully support this. And I suppose that the contribution guide should mention which features of C++11 are **not** welcome (`auto` seems to be one of those).

**Comment by fevangelista** [comment]
I fully support the switch to C++11.  I would not go as far as to ban the use of certain features (e.g. `auto`).

**Comment by wpoely86** [comment]
Outright banning `auto` is excessive. It can make your code actually more clear to understand. Of course, it should be used economically and with care. But in a lot of cases, the exact type is not that important.

**Comment by dgasmith** [comment]
Yes, banning certain features is not really what we want to do. I would simply add caution to the use of `auto`, maybe a rule of thumb: If you are using auto for something besides an iterator its *likely* not a good idea.

We tossed around a C++11 user guide, but didnt really get anywhere. I can start a wiki article if others will contribute as my personal list of do's and dont's is quite short.

**Comment by bennybp** [comment]
A wiki article sounds good to me, and I will add to it. Although my personal list of "don'ts" is pretty short also.

One C++11 feature to be careful about would be `shared_ptr`, since it doesn't play well with boost::python. I suppose there's no problem using internally in some places, but it should be scoped since that could be very confusing to other developers.

**Comment by ryanmrichard** [comment]
I added to the [wiki page](https://github.com/psi4/psi4/wiki/BestPractices) a bunch of stuff and suggest someone with higher authority close this thread.

**Comment by dgasmith** [comment]
Good place to start, closing this for now.

**Comment by loriab** [comment]
Nice, thanks.

**Comment by jgonthier** [comment]
@ryanmrichard : I am reading through the guidelines you wrote and I see that for unique_ptr, the C++14 syntax for construction will be:
`std::unique_ptr<Type> MyPtr=std::make_unique<Type>();`
whereas the syntax for shared_ptr is reported as:
`std::shared_ptr<Type> MyPtr=std::make_shared();`
Should it be `make_shared<Type>()` ? Or are the two really different ?

Thanks for these notes, by the way. I'm going to try to apply that to the new PK integral code.

**Comment by ryanmrichard** [comment]
It should be `make_shared<Type>()` that's what happens when you write code and then don't have a compiler compile it.
