### ISSUE TITLE
conv-mp2 gradients need conv-hf gradients

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#245]
What is needed to get around this constraint of the simple input snippet below not working b/c scf is DF, @bozkaya ? The conventional integrals have already been computed and are ready. Is there some other data transformation needed? As a last resort, I suppose we can go ahead and compute the non-DF scf instead when this call is made. But I think we need this input to work.

Related (user-experience-wise) to https://github.com/psi4/psi4private/issues/48

```
set mp2_type conv
gradient('mp2')
```

```c++
        // SCF TYPE
        if (options_.get_str("SCF_TYPE") == "DF" || options_.get_str("SCF_TYPE") == "CD") {
            if (dertype != "NONE") {
                throw PSIEXCEPTION("Analytic gradients are NOT available for SCF_TYPE=DF/CD !");
            }
```

**Comment by bozkaya** [comment]
Hi Lori,

The problem is that the OCC module is responsible for the conventional MP2 gradient, and in the OCC module we do not use DF integrals. Further, I am not sure why one should use conventional MP2 as a post DF-HF computation. However, the reverse situation (DF-MP2 after conventional SCF) is commonly used and called as RI-MP2. If we really need it I can implement a hybrid approach, but not soon. However, If think we have two options for now. The first option is calling DFOCC module and use DF-MP2 gradients when DF-SCF was set. The second one is just run the conventional SCF and then conventional MP2. In the proc.py you may arrange it in the select_mp2 group since I do not have the latest version yet. @loriab  @andysim

**Comment by loriab** [comment]
I agree that df-hf + conv-mp2 is an odd thing to request (except in psi4, where it's strangely easy). And I concede that occ doesn't deal in DF integrals. But if the conventional integrals were all pre-computed by the time `psi4.occ()` is called, I'm just wondering if there's anything *else* that was needed for conv-mp2 grad that cannot be extracted from the df-hf calc. I'm not trying to launch an involved project, just seeing if a little data shuffling can't get around some of these NYI alerts. I agree that of the two between df-hf + conv-mp2 and conv-hf + df-mp2 in psi4/psi4private#48, that this is the less pressing. (Though for the thoughtless user, they'd occur at equal frequency.)

**Comment by bozkaya** [comment]
In case of energy the situation is as simple as you suggested. However, in case of gradients the situation is much complicated. The DF-SCF orbitals are optimized at DF-SCF level, and these are different than that of conventional SCF. Hence, after DF-SCF if I try to compute gradients for conventional SCF I need to an extra term to MP2 Lagrangian to account for the orbital relaxation for SCF MOs. It may sound odd, but it is. Since the MOs of SCF are different than that of DF-SCF, we need to re-optimize orbitals for SCF or we need to modify our Z-vector equation sin SCF-MO gradient is not zero, but DF-SCF orbital gradient is zero. Hence, we need to modify MP2 Lagrangian for DF-SCF ref and add another term to account for orbital relaxation for SCF wfn.  In summary, I recommend to use the conventional SCF for conventional MP2 gradients even though user asks a DF-SCF ref. @loriab @andysim @CDSherrill

**Comment by loriab** [comment]
Thank you, Ugur, for the detailed explanation. That really helps me understand what's going on in this case and in psi4/psi4private#48 . I gather that the situation we've got now is the following:

`scf_type` | `mp2_type` | `qc_module` | outcome
---|---|---|---
conv | conv | occ | works
df | df | occ | works
df | df | dfmp2 | works
df | conv | occ | NYI error; psi4/psi4#48 (this); not too useful to implement
conv | df | dfmp2 | NYI error; psi4/psi4private#48; would be useful to implement
conv | df | occ | works or not?, @bozkaya

Barring implementing many orbital response terms in this or psi4/psi4private#48, sounds like the above is fixed for the time being for when the user specifies `scf_type` and `mp2_type`. But when `scf_type` is only implied "(df)", I can add the below.

`scf_type` | `mp2_type` | `qc_module` | outcome
---|---|---|---
(df) --> conv | conv | occ | works as above


If you *did* implement cd-mp2 gradients, @bozkaya, do you anticipate them only working upon a cd-hf reference?

**Comment by bozkaya** [comment]
Hi Lori,

I am sorry for my late response. I have just seen your question about cd-mp2. Unfortunately, we do not have analytic gradients for any CD based method. cd-mp2 and other cd-methods can work with HF, CD-HF, and DF-HF. In case of non CD-HF reference, we should set "READ_SCF_3INDEX FALSE" then dfocc module will compute CD integrals for post-HF method. Therefore, it is possible to use conventional HF and even DF-HF for cd-mp2, but the mentioned option must be used in case of HF and DF-HF. @loriab

**Comment by bozkaya** [comment]
Further, df-mp2 with conventional HF works for energy if user set the "READ_SCF_3INDEX FALSE" option. However, for analytic gradients it does not work. @loriab

**Comment by loriab** [comment]
@bozkaya, so if one runs a df-mp2 gradient that effectively but not explicitly does conventional HF, as through the input below, which yields the output pattern below, then this is actually a bad error of routing, which I should correct?

```
molecule hf {
H
F 1 0.917
}

set basis cc-pvdz
set mp2_type df
set qc_module occ

gradient('mp2')
```

```
...
  @RHF Final Energy:  -100.01941126902265
...
	Computing DF-MP2 energy using SCF MOs (Canonical DF-MP2)... 
	======================================================================= 
	Nuclear Repulsion Energy (a.u.)    :     5.19366944090513
	DF-HF Energy (a.u.)                :  -100.01941126902265
	REF Energy (a.u.)                  :  -100.01941126902265
	DF-MP2 Correlation Energy (a.u.)   :    -0.20376310280949
	DF-MP2 Total Energy (a.u.)         :  -100.22317437183214
	======================================================================= 
...
                         DFGRAD   
            A General Analytic Gradients Code   
               for Density-Fitted Methods       
...
  -Total Gradient:
     Atom            X                  Y                   Z
    ------   -----------------  -----------------  -----------------
       1       -0.000000000000     0.000000000000     0.002795941505
       2        0.000000000000    -0.000000000000    -0.002795941505
...
```

**Comment by loriab** [comment]
@bozkaya, so DFOCC can do frozen core/virt for gradients but OCC can't?

**Comment by loriab** [comment]
@bozkaya, sorry to bombard, but any thoughts on why occ analytic doesn't want to match occ findif?

```

mp2totg = psi4.Matrix(2, 3)
mp2tot_vals = [[   0.0000000000,       0.0000000000,       0.0028301835],
               [   0.0000000000,       0.0000000000,      -0.0028301835]]
mp2totg.set(mp2tot_vals)

molecule hf {
H
F 1 0.917
}

set basis cc-pvdz
set scf_type pk
set mp2_type conv

set qc_module detci
fdgrad = gradient('mp2', dertype='energy')
compare_matrices(mp2totg, fdgrad, 5, 'detci fd')
clean()

set qc_module fnocc
fdgrad = gradient('mp2', dertype='energy')
compare_matrices(mp2totg, fdgrad, 5, 'fnocc fd')
clean()

set qc_module occ
fdgrad = gradient('mp2', dertype='energy')
compare_matrices(mp2totg, fdgrad, 5, 'occ fd')
clean()

set qc_module occ
realgrad = gradient('mp2')
compare_matrices(mp2totg, realgrad, 5, 'occ analytic')
clean()
```

```
Performing finite difference calculations
 3 displacements needed ... 1 2 3
	detci fd..........................................................PASSED
Performing finite difference calculations
 3 displacements needed ... 1 2 3
	fnocc fd..........................................................PASSED
Performing finite difference calculations
 3 displacements needed ... 1 2 3
	occ fd............................................................PASSED
	occ analytic: computed value (0.0028301835) does not match (0.00281933825282).
	occ analytic: computed value (-0.0028301835) does not match (-0.00281933825299).
Check your output file for reporting of the matrices.
```

**Comment by bozkaya** [comment]
Hi Lori,

Let us start with your first question for the HF molecule. I run your job, and it terminates "normally". Since it is a gradient job I do not simply grab integrals from SCF, but I compute both JKFIT and RI basis DF integrals. Hence, it does not matter to start with the conventional integrals the df-mp2 code proceeds. However, the gradient is not correct because the MO coefficients are from conventional SCF, but it should be from DF-SCF. I think in the case df-mp2 gradients, if user set the conventional SCF, then we should throw an error. Alternatively we may change the reference to DF-SCF and throw a warning for user to explain what we did. Both solutions are okay for me.

DFOCC uses frozen cores properly in energy and gradients. I did not add the froze virtuals yet. But I will add them soon for FNO-DF-CCSD gradients. However, OCC does not use frozen cores in the energy and gradients. In case of OCC the problem is that you need to define different MO class with libtrans, which is not obvious how to do it. I know it is possible now. Andy explained it for me. As a result, there is no plan for OCC module. However, frozen virtuals will be added to DFOCC. In fact, I am waiting for RC1 release, then I will implement add it to Psi4.

For the final question, your reference gradient is wrong (mp2tot_vals). This is a very good example how 3-point numeric gradients are unreliable for challenging systems. I reproduce problem with your input. However, if I use "points 5", all numeric gradient computations give the same result with the analytic gradients. I also run the same job with gausssian 09 with analytic gradients, which gives the same result with our analytic gradient. Here is the G09 result:

 -------------------------------------------------------------------
 Center     Atomic                   Forces (Hartrees/Bohr)
 Number     Number              X              Y              Z
 -------------------------------------------------------------------
      1        1           0.000000000    0.000000000   -0.002819339
      2        9           0.000000000    0.000000000    0.002819339
 -------------------------------------------------------------------

and our analytic gradients:

  -Total gradient:
     Atom            X                  Y                   Z
    ------   -----------------  -----------------  -----------------
       1        0.000000000000     0.000000000000     0.002819338251
       2        0.000000000000     0.000000000000    -0.002819338251

@loriab

**Comment by CDSherrill** [comment]
My feeling is that gradient('mp2') should probably default to DF in the SCF
and the MP2, so that we have a nice user experience.  We know very well by
now that the DF errors are essentially zero, and the DF algorithm is way
faster.

We should print some warning to the user to explain what we did, because
admittedly this solution will cause some degree of confusion.

For more advanced users, they should be able to specify where they want
conventional integrals for the SCF and/or MP2.  And if they pick an
unsupported combination (conventional SCF plus DF MP2 gradients) we should
print an error message explaining that's not available.

Are we still defaulting to DF for SCF?  (at least when there is no post HF
module that wants the conventional ints)?  Probably should until / unless
we get efficient conventional SCF, and arguably even then.

David

**Comment by loriab** [comment]
@CDSherrill , good to hear as I quite agree. This is just what the dfmp2 module does presently for gradients: switches `scf_type` to `df` unless the user has reqested _not_ `df`, in which case it reveals its cause of death. I'm imitating this behavior now for the other mp2 gradient routes. My Q1 for Ugur was that a conv+df gradient was proceeding, and I wanted to confirm that failing it was the correct thing to do. The complication/confusion (it even caught me last night) is that although all scf calculations _run df by default_ (handled in the driver), the `scf_type` keyword _does not default to df_ (since there's a lot more post-scf than scf out there, it's easier to handle the latter as the exception), so setting solely `mp2_type df` in a `gradient('mp2')` leads to that conv+df case (even though someone knowing psi's df-philia might expect that to lead to df+df). But don't worry about that– for mp2, at least, I'll try all combinations and arrange that only good ones get through and that the advanced defaulting is handled right.

By the way, back to energies, would you expect OCC's conventional ROHF mp2 energy to match DETCI's? It doesn't, and that's the only check remaining commented out in my great mp2 cross-module comparison (https://github.com/psi4/psi4/blob/master/tests/mp2-module/input.dat#L191) OCC's df ROHF mp2 _does_ match DFMP2's.

**Comment by loriab** [comment]
@bozkaya, thanks for all the feedback!

Q1: Good, I'm going the latter route so it behaves just like the DFMP2 module. I just wanted to confirm that it was finishing cleanly in error, and it seems we agree on that.

Q2: Ok, just confirming that this was a difference btwn OCC & DFOCC. I'll go ahead and check fc & non-fc independently for df and leave in a commented check for fc w/conv in case you ever get around to that.

Q3: Yay! I had tried up-ing the convergence but not the findif scheme. Will do this routinely in future. Thanks for finding the problem.

**Comment by bozkaya** [comment]
Hi Lori,

For the conv+df gradient case, the failing is okay. However, we may change the conv-SCF to DF-SCF and throw a warning for user to explain what we did and why we did. I prefer the latter alternative, it is better than changing input and resubmitting a job.

I think we may find a way to connect scf_type option to mp2_type/mp_type/cc_type options in the case of post-HF methods. Then if user set cc_type df than we should automatically set scf_type df. How about this?

I think DETCI ROHF-MP2 will not match with OCC ROHF-MP2. Because the former one uses a spin-free approach based on unitary group generators, but the latter one uses a spin-orbital approach. David may confirm me. However, you should match OCC ROHF-MP2 results with the CFOUR for example. @loriab @CDSherrill

**Comment by loriab** [comment]
On the first item, yes, that's what DFMP2 module does now, and that's what DFOCC will do when I get through with it.

In effect yes, but there's enough combinations of scf_type/higher_type and variation among modules (some may be equipped to handle mixed df&conv) that I'm not going to reset the types bluntly. Let's see how mp2 goes first.

Ok, good to know there's a plausible reason. Here's the magnitude of the error (for BH3+), if that helps, @CDSherrill .

```
	mp2 rohf conv: 2 occ*.............................................PASSED  # HF
	mp2 rohf conv: 2 occ*: computed value (-0.0594063) does not match (-0.0609392) to 6 decimal places.  # MP2 corl
	mp2 rohf conv: 2 occ*: computed value (-26.0030128) does not match (-26.0045457) to 6 decimal places.  # MP2 tot
```

**Comment by loriab** [comment]
@bozkaya, regarding `READ_SCF_3INDEX` for CD calcs, I'll just believe you. For this (https://github.com/psi4/psi4/issues/245#issuecomment-186302823) comment, though, for DF calcs, I'm not seeing that that keyword can make a difference. Toggling its presence and value in the below makes no difference to the energies. So fyi, I'm not implementing the advice in your comment for now.

```

mp2totg = psi4.Matrix(2, 3)
mp2tot_vals = [[   0.0000000000,       0.0000000000,       0.0028301835],
               [   0.0000000000,       0.0000000000,      -0.0028301835]]
mp2tot_vals = [[   0.0000000000,       0.0000000000,       0.0028193375],
               [   0.0000000000,       0.0000000000,      -0.0028193375]]
mp2totg.set(mp2tot_vals)

molecule hf {
H
F 1 0.917
}

set basis cc-pvdz
set scf_type pk
set mp2_type df
set points 5
set freeze_core false
set reference rhf
set READ_SCF_3INDEX true #FALSE  # TOGGLE

set qc_module dfmp2 #occ  # TOGGLE
energy('mp2')

compare_values(-100.0194112690226973, get_variable('scf total energy'), 6, 'scf')
compare_values(-0.203779972647527, get_variable('mp2 correlation energy'), 6, 'mp2corl')
compare_values(-100.2231912416702215, get_variable('mp2 total energy'), 6, 'mp2tot')
```

**Comment by CDSherrill** [comment]
@loriab, I would have thought DETCI ROHF MP2 would agree with other codes,
but I can think of at least a couple little reasons it might not.  I should
check into this next couple weeks (help me remember).

David

**Comment by bozkaya** [comment]
Hi Lori,

I was testing the new call name conventions for a while. Now, we have MP2_TYPE, MP_TYPE, CC_TYPE, CEPA_TYPE to switch between DF/CD/CONV. I guess it will be somewhat confusing for users to remember all of these options. 

I think we can merge all this options into a global option. For example, we may define CORRELATION_TYPE as a new option (or POST_HF_TYPE), and instead of MP2_TYPE/MP_TYPE/CC_TYPE/CEPA_TYPE we will have a global option which will switch between DF/CD/CONV. Hence, with this definition we will just need to set SCF_TYPE and CORRELATION_TYPE options. What do you think? @loriab @CDSherrill 

Ugur

**Comment by loriab** [comment]
Actually, we have CI_TYPE but not CEPA_TYPE now (or will once https://github.com/psi4/psi4/pull/306 merges in), so 5: SCF_TYPE, MP2_TYPE, MP_TYPE, CC_TYPE, CI_TYPE. The first has many algorithms, the others just DF/CD/CONV. There's also a few strays: DCFT_TYPE and OPT_TYPE.

For simple calculations, a SCF_TYPE and CORRELATION_TYPE, as you suggest, works. But I'm concerned about targeting a complete options set for composite jobs (e.g., SCF + extrapolated MP2 + CCSD(T) delta correction). There, you might want the first two terms DF and the last CONV.

When I started going crazy with _TYPE keywords, I had one for each method (e.g., MP4SDQ_TYPE). The current lineup is a compromise between broad (CORRELATION_TYPE) and specific (LCCD_TYPE), and I think I'd like to see how the use-cases develop along that spectrum. Thanks for thinking about this, though!

**Comment by CDSherrill** [comment]
Hm wonder if we could do as Lori suggests as the bulletproof way to do it,
but allow CORRELATION_TYPE as the quick and easy default that will usually
work for most things.

**Comment by bozkaya** [comment]
We can abbreviate it to CORR_TYPE. :-)

**Comment by CDSherrill** [comment]
Hmm, good point about the defaults

**Comment by loriab** [comment]
Thanks to all the good discussions on this thread, I think we agree that df+conv mp2 gradients are not going to materialize and for good reason. With 16ccace5b87e92334e3ff7a6ca9a5a536cc1ecaf and test case https://github.com/psi4/psi4/blob/master/tests/mp2-module/input.dat and independent tests that show auto switching scf_type to conv when conv mp2 gradients requested and scf_type unspecified working. So closing this out with #306 . The detci rohf mp2 is moved to #311 .
