### ISSUE TITLE
`psi4.so` segfaults

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#251]
Build the shared library with `make psi4so`, and it builds just fine but then segfaults when you try to set options. @bennybp, Boost/fpic notwithstanding, I know you've got a shared library of psi4 in working order. Could you send me or post the `src/bin/psi4/CMakeLists.txt` and any changes to the `MAKE_PYTHON_MODULE` sections? I didn't see that you had a fork of psi4 with changes.

```python
Python 2.7.10 |Anaconda 2.1.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import sys
>>> sys.path.insert(1, '/Users/loriab/linux/psihub/publicface/psi4/objdir/bin')
>>> import psi4
>>> psi4.set_global_option('BASIS', 'CC_PVDZ')

Error: option BASIS is not contained in the list of available options.
Assertion failed: (px != 0), function operator->, file /Users/loriab/linux/psihub/publicface/psi4/objdir/boost/include/boost/smart_ptr/shared_ptr.hpp, line 648.
Abort trap: 6
```

**Comment by bennybp** [comment]
I added the branch psi4sofix to psi4/psi4private (didn't know if I should have used public or not).

There's not too many changes. Since the goal was to use if from other C++ code, I didn't try it directly from python, so I don't know if this will fix the problem.

This also has a change to the boost find_package, so it probably shouldn't be merged.

**Comment by loriab** [comment]
This should be fixed by https://github.com/psi4/psi4/commit/03ebca599af71744c0f494e13bd7ac75a648d3c0
