### ISSUE TITLE
seg.fault with dft and soscf

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#256]
version: Rev {master} 0d10de8

After entering the SOSCF psi4 exists with a segmentation fault. It prints the soscf header if soscf_print true. Occurs e.g. when I run soscf1 test case with PBE instead of HF.

I don't know if SOSCF should work with DFT or not.

**Comment by dgasmith** [comment]
SOSCF is not implemented for DFT as we do not have exact DFT Hessians yet. That's odd that it seg faults however, it should call the base HF SOSCF method and throw an error. I'll see if I can fix this. 

-Daniel Smith

**Comment by dgasmith** [comment]
I put in a patch so that this should soft fail now.

SOSCF is quite a new module, out of curiosity have you used it for any other systems?

**Comment by hokru** [comment]
Thanks for putting in a soft fail!

I used it for cytosine with a minimal basis set (Grimme's MINIX). It did work with HF and obviously failed for wPBE. Tried it because ip_fitting had convergence issues somewhere (nothing to worry about i think).

I initially though it is similar to the approx. SOSCF in ORCA and not the full SOSCF. Otherwise I would not have bothered.

**Comment by dgasmith** [comment]
Yea, Psi4's SOSCF is an exact Newton update if you let the equations fully converge; however, it makes implementing SOSCF for KS a bit rough since we need to compute all possible KS Hessian vector products (which is actually on a todo list somewhere!).

If it is a desired feature we can add an approximate SOSCF update. Either through BFGS or just some kind of clever diagonal approximation.

**Comment by hokru** [comment]
The DIIS solver is usually more robust than approx. SOSCF, at least ORCA's implementation had and still has troubles sometimes. Not sure if it is worth the time.

**Comment by dgasmith** [comment]
Good to know, I will close this out.
