### ISSUE TITLE
Failed v1.5 install from Conda in Docker

### ISSUE THREAD

**Issue by coltonbh** [psi4/psi4#2596]
Hi all. I've been using psi4 inside of a docker container for over a year. Suddenly, the same build process fails to produce a usable psi4 install. I get the following exception when trying to run `psi4 --version` (or any other psi4 command) inside the container: 
```sh
(base) root@3434e5974c7f:/# psi4 --version
Traceback (most recent call last):
  File "/opt/conda/lib//python3.9/site-packages/psi4/__init__.py", line 55, in <module>
    from . import core
ImportError: /opt/conda/lib//python3.9/site-packages/psi4/core.cpython-39-x86_64-linux-gnu.so: undefined symbol: __intel_sse4_strlen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/psi4", line 183, in <module>
    import psi4  # isort:skip
  File "/opt/conda/lib//python3.9/site-packages/psi4/__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: /opt/conda/lib//python3.9/site-packages/psi4/core.cpython-39-x86_64-linux-gnu.so: undefined symbol: __intel_sse4_strlen
```

The simplest repro can use the following `Dockerfile`:

```
FROM continuumio/miniconda3:4.10.3
RUN conda install psi4=1.5 -c psi4
```

Then:
`docker build -t psi4-test .`

Then to enter the container:

`docker run -it psi4-test bash`

Then inside the containter run:

`psi4 --version`

Has something changed on the conda repos that now results in missing libraries, specifically those containing `__intel_ss34_strlen`? Strange that this very simple build processes worked for one year+ and now fails... Have repro'd on multiple systems.

Thanks so much!

**Comment by loriab** [comment]
Acknowledged. Two problems, one solved, one not.

* First issue is for v1.5 you have to grab a certain libint2 build as described here: https://github.com/psi4/psi4/issues/2593#issuecomment-1145503791 Probably you didn't get to the segfault the "newest" L2 would cause because the missing symbol got in the way. :-(
* Second issue is the missing symbol. I've seen it myself with py38. (It can incidentally be solved by preloading `libirc` if you've an Intel installation lying around (`LD_PRELOAD=/psi/gits/software/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libirc.so python -c "import psi4"` is clean), but that's not a worthy solution. But clearly the missing symbol wasn't happening in the earlier issue. Current theories:
  * some newer version/build of a package got uploaded in the past week or so that throws off this env
  * py37 _did not_ get updated versions of packages on the psi4 channel with the 1.6 release, so it's getting old, compatible versions of some psi4-channel based package and is fine, while py38 and py39 got a fresh package and got broken.

**Comment by coltonbh** [comment]
Appears specific to `psi4v1.5` as bumping version to `1.6` works fine, same with `1.7`.

Ideas on what happened? Guessing it was a minor bump to a `1.5` version that has issues.

**Comment by loriab** [comment]
looks like pcmsolver is the culprit. add `psi4::libint2=*=hc9558a2_9 pytest=5 psi4::pcmsolver=*=py38h6d17ec8_2` to the env specs. py38 passes with that. note that you'll have to adjust the python version in the pcmsolver buildstring.

Yes, v1.5 would be the primary victim. v1.6 is latest, so the newest-solving packages from `-c psi4` are built to work with it. Like wise v1.7.dev* and `-c psi4/label/dev`. In this case, v1.5 could have benefitted from more pins.

For solid reproducibility, the psi4conda installers have the advantage.

I'll have to add the add'l packages to the psicode download page command matrix.

**Comment by coltonbh** [comment]
For `conda` n00bs like myself who want a speclfic command to execute, your `Dockerfile` would now look like the following (using python3.9 since that is what comes with `miniconda3:4.10.3`). Can confirm this works. @loriab if you suggest any changes to the command below just let me know.

```docker
FROM continuumio/miniconda3:4.10.3
RUN conda install psi4=1.5 -c psi4 && \
    conda install psi4::libint2=*=hc9558a2_9 pytest=5 psi4::pcmsolver=*=py39h6d17ec8_2 -c psi4
```

> For solid reproducibility, the psi4conda installers have the advantage.

What exactly do you mean by this? Is there a preferred way to install psi4 other than `conda install psi4=1.5 -c psi4`? Pardon my lack of depth with the nuances of conda distributions.

**Comment by loriab** [comment]
> For conda n00bs like myself who want a speclfic command to execute, your Dockerfile would now look like the following (using python3.9 since that is what comes with miniconda3:4.10.3). Can confirm this works. @loriab if you suggest any changes to the command below just let me know.

You can do it all at once (in fact for new conda environments, it's always slightly preferred to use a single command line so that the solver knows all the requirements at once. so, `conda install psi4=1.5 libint2=*=hc9558a2_9 pytest=5 pcmsolver=*=py39h6d17ec8_2 -c psi4` should do nicely.

>> For solid reproducibility, the psi4conda installers have the advantage.

> What exactly do you mean by this? Is there a preferred way to install psi4 other than conda install psi4=1.5 -c psi4? Pardon my lack of depth with the nuances of conda distributions.

oh, there's a single-file installer ("installer" off https://psicode.org/installs/v16/) that fits the analogy `miniconda:"conda install python"::psi4conda:"conda install python psi4"` . Not what you'd want if psi4 is one of many changing envs, but it'd be fine for docker.

**Comment by coltonbh** [comment]
Much thanks for the investigation and thorough response! I have a few projects pegged on psi4 v1.5 so I'd like my build to continue working. This will do the trick :)
