### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#266]
Dear Developers, 

I compiled successfully psi4-0.5 but obtain an error when running psi4 :

          Psi4: An Open-Source Ab Initio Electronic Structure Package
                              Psi4 (no tag) Driver

                          Git: Rev {detached?} 8e01b1f 

    J. M. Turney, A. C. Simmonett, R. M. Parrish, E. G. Hohenstein,
    F. A. Evangelista, J. T. Fermann, B. J. Mintz, L. A. Burns, J. J. Wilke,
    M. L. Abrams, N. J. Russ, M. L. Leininger, C. L. Janssen, E. T. Seidl,
    W. D. Allen, H. F. Schaefer, R. A. King, E. F. Valeev, C. D. Sherrill,
    and T. D. Crawford, WIREs Comput. Mol. Sci. 2, 556-565 (2012)
    (doi: 10.1002/wcms.93)

                         Additional Contributions by
    A. E. DePrince, M. Saitow, U. Bozkaya, A. Yu. Sokolov
    -----------------------------------------------------------------------

    Psi4 started on: Thu Feb 18 17:21:00 2016

    Process ID:  63254
    PSI4DATADIR: /home/LUCA/psi-master/psi4public/lib
    Memory level set to 256.000 MB

  ==> Input File <==

--------------------------------------------------------------------------
#! Sample UHF/6-31G** CH2 computation

memory 250 mb

molecule ch2 {
  0 3
  C 
  H 1 R
  H 1 R 2 A

  R = 1.075
  A = 133.93
}

set basis 6-31G**
set reference uhf
energy ('scf')

--------------------------------------------------------------------------

  Memory set to 250.000 MiB by Python script.

An error has occurred Py-side
Traceback:
<class 'Boost.Python.ArgumentError'>: Python argument types in
    psi4.scf(NoneType, NoneType)
did not match C++ signature:
    scf(boost::shared_ptr<psi::Wavefunction>, _object*, _object*):   File "<string>", line 29, in <module>

  File "/home/LUCA/psi-master/psi4public/lib/python/driver.py", line 576, in energy
    procedures['energy'][lowername](lowername, **kwargs)

  File "/home/LUCA/psi-master/psi4public/lib/python/proc.py", line 932, in run_scf
    scf_helper(name, **kwargs)

  File "/home/LUCA/psi-master/psi4public/lib/python/proc.py", line 1138, in scf_helper
    e_scf = psi4.scf(precallback, postcallback)

Best wishes
LUCA

**Comment by loriab** [comment]
Any chance you're still running an earlier driver (`PSIDATADIR` set)? If your new exe is at `$PSI/bin/psi4`, try executing as `$PSI/bin/psi4 -l $PSI/share input.in`

**Comment by lucamontana** [comment]
Thanks a lot, it now works for scf calculation.

now i try to do a dmrg-scf  as explained here :   http://sebwouters.github.io/CheMPS2/interfaces.html 
but end up with 

An error has occurred Py-side
Traceback:
<type 'exceptions.RuntimeError'>: 
Fatal Error: PSIO Error
Error occurred in file: /home/LUCA/psi-master_18_02.2016/psi4-0.5/src/lib/libpsio/error.cc on line: 123
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::open(unsigned int, int)
psi::Matrix::save(psi::PSIO*, unsigned int, psi::Matrix::SaveType)
psi::Matrix::save(boost::shared_ptr<psi::PSIO>&, unsigned int, psi::Matrix::SaveType)
 (/home/LUCA/psi-master_18_02.2016/psi4-0.5/src/lib/libpsio/error.cc:123):   File "<string>", line 48, in <module>

  File "/home/LUCA/psi-master_18_02.2016/psi4-0.5/share/python/driver.py", line 586, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)

  File "./../dmrg/pymodule.py", line 51, in run_dmrg
    scf_helper(name, **kwargs)

  File "/home/LUCA/psi-master_18_02.2016/psi4-0.5/share/python/proc.py", line 1020, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)
 


LUCA

**Comment by loriab** [comment]
Looks like the plugin didn't get the infrastructure changes update. If you change the signature and return according to http://forum.psicode.org/t/wavefunction-passing-update/139 , does that fix it? @SebWouters, did your latest changes cover the plugin signature change?

**Comment by lucamontana** [comment]
no idea where to do this :  

A consequence of this is we broke all of the plugins! Don't worry the fix is very simple please change your C++ signature from: 
PsiReturnType skeleton(Options& options)
to:
SharedWavefunction skeleton(SharedWavefunction ref_wfn, Options& options)

**Comment by loriab** [comment]
Nevermind, that did get done. I was looking at the wrong portion of code. In that case, I'd need to try it out myself, which I can't do immediately. You are at tags 1.5 or 1.6 of CheMPS2 (which work) not at master or 1.7 (which doesn't)?

**Comment by lucamontana** [comment]
CheMPS2 is the latest version released today, since i need CASPT2.
Sorry, no idea how to verify tags of CheMPS2.

I separately compiled psi4.0.5 and latest version of CheMPS2.

**Comment by loriab** [comment]
Ah, I think @SebWouters said CASPT2 is only in 1.7, and there's a CheMPS2 API change between 1.6 and 1.7. But according to https://github.com/SebWouters/CheMPS2/issues/20, a new plugin from today should be such that the CheMPS2/Psi4 interfacing code is 1.7/HEAD compliant. So I don't see that what you're doing *shouldn't* work. Would have to try it out.

**Comment by SebWouters** [comment]
A couple of remarks:
 - chemps2 v1.7 is not yet released and will not be until I do a few applications and write a paper myself. The recommended version to use is still v1.6 in the meantime and CASPT2 is therefore not supported yet. But that doesn't mean it shouldn't work.
 - One important thing is that I haven't made CASPT2 parallel yet. You will have to wait forever when the number of virtuals is modest / large.
 - A second important remark is that I also currently use only pseudocanonical orbitals for DMRG-CASPT2, so for elongated molecules you will waste your time at the moment, because the virtual dimension is way smaller by using localized orbitals. But for that I need to implement the full 4-RDM instead of the diagonal one, and that is not for the very near future. The cumulant approximation is also ready on the other hand, but will only be used in conjunction with the CASPT2 interface at one point in the future.
 - I don't use the current HEAD of psi4/psi4, but use the tagged version https://github.com/psi4/psi4/releases/tag/0.5, but from the git commit tag in your input above, I gather you use this version as well. @loriab : good thing psi4 prints the commit tag!
 - The compiler with which I compiled psi4 and chemps2 is gcc/g++ 5.2.1 and I am on Ubuntu 15.10. I also tried the intel compiler 16.0.0 20150815 and mixtures of both, but only by compiling everything with the GNU compiler I was able to make things work thus far. This means that before releasing v1.7 I also need to check several compiler combinations and make things work, but because compilers get updated at regular times, I will wait with that.
 - That all being said, I don't know what is going on. You clearly use the right git commit of psi4 (8e01b1f), but the plugin API is clearly wrong.

The following is copied from a message above:

      An error has occurred Py-side
      Traceback:
      : Python argument types in
      psi4.plugin(str)
      did not match C++ signature:
      plugin(std::string, boost::shared_ptrpsi::Wavefunction): File "", line 48, in  
      
      File "/home/LUCA/psi-master_18_02.2016/psi4-0.5/share/python/driver.py", line 586, in energy
      wfn = procedures['energy']lowername
      
      File "./../dmrg/pymodule.py", line 52, in run_dmrg
      returnvalue = psi4.plugin('dmrg.so')

For the record I copy my file 'pymodule.py' here:

      import psi4
      import re
      import os
      import inputparser
      import math
      import warnings
      from driver import *
      from wrappers import *
      from molutil import *
      import p4util
      from p4xcpt import *


      def run_dmrg(name, **kwargs):
          r"""Function encoding sequence of PSI module and plugin calls so that
          dmrg can be called via :py:func:`~driver.energy`. For post-scf plugins.

          >>> energy('dmrg')

          """
          lowername = name.lower()
          kwargs = p4util.kwargs_lower(kwargs)

          # Your plugin's psi4 run sequence goes here
          #psi4.set_global_option('BASIS', 'sto-3g')
          psi4.set_local_option('MYPLUGIN', 'PRINT', 1)

          # Compute a SCF reference, a wavefunction is return which holds the molecule used, orbitals
          # Fock matrices, and more
          print('Attention! This SCF is density-fitted.')
          ref_wfn = kwargs.get('ref_wfn', None)
          if ref_wfn is None:
              ref_wfn = scf_helper(name, **kwargs)

          # Call the Psi4 plugin
          # Please note that setting the reference wavefunction in this way is ONLY for plugins
          dmrg_wfn = psi4.plugin('dmrg.so', ref_wfn)

          return dmrg_wfn


      # Integration with driver routines
      procedures['energy']['dmrg'] = run_dmrg


      def exampleFN():
          # Your Python code goes here
          pass

As you can see it calls

      dmrg_wfn = psi4.plugin('dmrg.so', ref_wfn)

instead of

      returnvalue = psi4.plugin('dmrg.so')

So have you generated the files __init__.py, pymodule.py etcetera with the right version of psi4 (psi4-0.5)? It doesn't suffice to run the plugin with the right version of psi4, you also need to do

      psi4 --new-plugin dmrg

with the right version of psi4.

Best wishes,
Sebastian
