### ISSUE TITLE
Python modules are installed into a wrong path

### ISSUE THREAD

**Issue by yurivict** [psi4/psi4#2800]
@loriab 

Python modules are installed into ```lib/psi4``` when the correct location is ```lib/python3.9/site-packages```.

I believe the correct location can be read from the python executable.

Then there is some logic in ```psi4/__init__.py``` calculating paths which is completely wrong when the modules are installed into proper location.

**Comment by loriab** [comment]
Please use `PYMOD_INSTALL_LIBDIR` https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L94-L95 to adjust the path.

Since Linux build conventions and Python build conventions can't both be fully adhered to, Psi4 prefers the former, especially as one doesn't always want an install into Python's site-packages. I suspect the `__init__` logic will heal if this cmake var is used.

**Comment by yurivict** [comment]
This works, thank you, @loriab .
