### ISSUE TITLE
Vector Setting Error

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2853]
The following input file raises the error: `Cannot set element 12 since there are only 12 elements.` Somewhere, Psi is trying to set a non-existing vector element. I'm very curious why tests didn't catch this.

```
memory 2 GB

molecule {
0 1
C           1.741722       -1.200108       -0.733703
C           1.723351       -1.235440        0.673033
C           1.741208       -0.034341        1.406196
C           1.720430        1.201594        0.733472
C           1.738484        1.236058       -0.673301
C           1.720301        0.035400       -1.407211
H           1.811924       -2.125930       -1.299462
H           1.810840       -2.187236        1.191603
H           1.810814       -0.061176        2.490913
H           1.805598        2.126733        1.298598
H           1.806257        2.188975       -1.192470
H           1.805027        0.062415       -2.491005
--
2 1
Ba         -1.306490       -0.000406        0.000195
}
basis {
assign  jun-cc-pVDZ
assign Ba GENECP

[GENECP]
cartesian
****
Ba     0 
S   3   1.00
      0.8699000             -2.2549747        
      0.6676000              2.5145786        
      0.1982000              0.5775184        
S   4   1.00
      0.8699000              2.0391383        
      0.6676000             -2.3717712        
      0.1982000             -1.2758006        
      0.0823000              1.1703346        
S   1   1.00
      0.0231000              1.0000000        
P   3   1.00
      1.6050000             -0.1626403        
      0.4790000              0.6971289        
      0.1818000              0.4505107        
P   2   1.00
      0.1804000             -0.2642537        
      0.0476000              1.1347212        
P   1   1.00
      0.0192000              1.0000000 
****
}

energy('sapt0')
```

**Comment by JonathonMisiewicz** [comment]
Konrad [suggests](http://forum.psicode.org/t/sapt-calculation/2698/2) the basis set should be flagged as not-containing-enough-basis-functions during validation.

**Comment by JonathonMisiewicz** [comment]
Is there ever a legitimate reason for an atom to have fewer basis functions than it has active electrons? My intuition is no, but I don't want to attempt any code to enforce that before at least checking for reasons.

@susilehtola

**Comment by susilehtola** [comment]
> Is there ever a legitimate reason for an atom to have fewer basis functions than it has active electrons? My intuition is no, but I don't want to attempt any code to enforce that before at least checking for reasons.

On a purely mathematical ground, there is no reason not to allow calculations where some nuclei do not have any basis functions; after all, all that matters is the flexibility of the whole basis set. I would therefore recommend against a hard error here, or there should at least be a flag to control whether an error is raised or not.

Not having sufficiently many basis functions to hold the electrons is, however, a major error and should always result in an error termination. Here, Ba is indeed given a 3s3p basis set, which has 12 spatial orbitals and can thereby hold  24 electrons, whereas Ba has 56 electrons.

The error `Cannot set element 12 since there are only 12 elements` arises from exactly this; it seems that the size of the fragment basis is not checked, or not checked early enough!
