### ISSUE TITLE
psi4 forum error: 502 Bad Gateway

### ISSUE THREAD

**Issue by pranavkubc** [psi4/psi4#2868]
Hi, I was wondering if anyone is facing any problems accessing ps4 forum webpage. Anytime I try to open any link on psi4 forum it shows me this error. I have used multiple devices and internet connections to access this.
<img width="1646" alt="Screen Shot 2023-01-31 at 12 27 09 PM" src="https://user-images.githubusercontent.com/96807514/215875127-ef6dcd14-6e27-480f-a31e-860c85ac0bce.png">

**Comment by JonathonMisiewicz** [comment]
Yes. The forums have been down since Thursday of last week. @lothian is working on getting it restored, but that involves a rather time-consuming backup and an operating system update.

In the meantime, ask questions on forums or [on Slack](https://join.slack.com/t/psi4/shared_invite/zt-5s36s4rb-SQH6_AWyfWOqlKYN3cFs4Q).
