### ISSUE TITLE
Add a way to produce a full output file when using PsiAPI

### ISSUE THREAD

**Issue by mskblackbelt** [psi4/psi4#2893]
I'd like to be able to use Psi4 in a Jupyter notebook, but part of my workflow involves feeding the output into `cclib` for conversion to CJSON. Unfortunately, the truncated output from PsiAPI can't be parsed by the `cclib` parsers. Is there (or can there be) a way to toggle a "full" output using `psi4.set_output_file()`?

**Comment by loriab** [comment]
Is it the header info (psi name, version, authors text) that's tripping cclib up? If so you can run the fn that prints that stuff and concatenate. Fn is in header.py iirc

**Comment by mskblackbelt** [comment]
The initial issue was that cclib looks for the first line of the header ("Psi4: An Open-Source Ab Initio Electronic Structure Package") to decide which parser to use. I pasted this into one of the outputs and tried parsing it, but still threw an error. I just ran the same molecule with psithon and tried to parse the output, found the same error. Looks like adding the header text to the start of my output file would fix the issue. Would it be reasonable to add a `header=True` option to the `set_output_file()` function, such that the contents of `header.py` are automatically included?

As for the cclib issue, it looks like the structure of the Convergence Check section has changed since their code was written. I'll file an issue over there to fix that matter.

**Comment by loriab** [comment]
Yes, adding a header=true is possible. What conv crit changed so you know? Geom opt, scf, cc, other? I suspect geom opt since we switched that out in Dec. 

So in your Jupiter notebook, you're importing psi4, setting an output file (soon to incl header), running a single job(cclib consumable) closing that output file, processing or storing it, setting another output file, running another single job?

I ask b/c the Jupiter route usually amalgamates lots of outputs (that cclib won't like). Another route would be to have a node that prints the header at each energy/gradient/Hess/opt/freq call.
