### ISSUE TITLE
opt-irc-2 test case adjustment

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#290]
I've made changes and then had only the opt-irc-2 test case fail. Now I notice that others are having problems: https://testboard.org/cdash/testSummary.php?project=3&name=opt-irc-2&date=2016-02-27 . This is only a slight discrepancies at the end of a long IRC. In my case, at least, the number of IRC steps is the same. Do convergence keyword need tightening to preserve the reference progress of the IRC? Or does the compare_values check just need loosening to account for variance after many many optimization cycles? @avcopan, could you investigate?

Energy of last IRC point: computed value (-92.869134) does not match (-92.868907) to 5 decimal places.

**Comment by avcopan** [comment]
Yeah, I'm looking into it now -- thanks for letting me know.

**Comment by avcopan** [comment]
Okay, I think (hope) I sorted it out.  My test was checking the last computed energy, not the last converged IRC point.  The latter should be more robust.  The mechanism that checks for a minimum runs on the first step of the next IRC-point optimization -- that was the energy being compared.  Since the gradient is small so near the minimum, I guess it isn't surprising that that step direction isn't well-defined.  My changes are [here](https://github.com/avcopan/psi4/commit/ab07fd3e1c5242ca58bba12230ce7f1077392102).  If tests pass on my machine and you approve (@loriab), I'll do a pull request.
