### ISSUE TITLE
pywrap-opt-sowreap test failing

### ISSUE THREAD

**Issue by avcopan** [psi4/psi4#291]
The test `pywrap-opt-sowreap` is failing for me with the following error message:
```
Performing finite difference calculations
 5 displacements needed ...
An error has occurred Py-side
Traceback:
<type 'exceptions.TypeError'>: 'float' object is not iterable:   File "<string>", line 25, in <module>

  File "/home/avcopan/Documents/code/github/psi4/share/python/driver.py", line 1158, in optimize
    G, wfn = gradient(name, return_wfn=True, molecule=moleculeclone, **kwargs)

```

I did some poking around and it looks like the problem is that this code (see [here](https://github.com/psi4/psi4/blob/master/share/python/driver.py#L1153)):
```
def optimize(name, **kwargs):
        # ...
        G, wfn = gradient(name, return_wfn=True, molecule=moleculeclone, **kwargs)
        psi4.set_gradient(G)
        thisenergy = psi4.get_variable('CURRENT ENERGY')
```
breaks when gradient is called in sow-reap mode because it returns `0.0` rather than a matrix-wavefunction tuple (see [here](https://github.com/psi4/psi4/blob/master/share/python/driver.py#L843)):
```
def gradient(name, **kwargs):
    # ...
    if dertype == 1:
        # ...
    else:
        # ...
        if (opt_mode.lower() == 'sow'):
            optstash.restore()
            return 0.0
```

**Comment by loriab** [comment]
Thanks for the analysis. After the wavefunction pass, I haven't revisited sow/reap operation at all, and I don't actually expect any of them to be working. Since you've obliged with an official ticket, I'll make a list of things to do :-)

* [ ] grad by fd energy s/r
* [ ] freq by fd energy s/r
* [ ] freq by fd gradient s/r (new capability)
* [ ] in opt by fd energy, make sure optdata is being carried along, rather than opt restarting from step 1 everytime.

**Comment by avcopan** [comment]
Gotcha -- the analysis was to make sure I hadn't broken something myself :)
