### ISSUE TITLE
docker and apptainer (formerly singularity) containers for psi4

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#2951]
@hokru, @jturney, @AlexHeide, @susilehtola, @bennybp, and anyone else interested/knowledgeable about containers:

I've got a proof-of-principle building in GHA at https://github.com/psi4/docker-expt . It seems to be successful at building a linux docker container from a conda environment.yaml, uploading it to dockerhub (https://hub.docker.com/repository/docker/psi4/clockbox/general), running smoke tests on the image, building an apptainer from the docker, and doing nothing with the sif file.

This is all based on a tutorial https://docs.docker.com/build/ci/github-actions/ (hence the `clockbox`es) and modeled on some files that Ben is using (operational docker file is the `Dockerfile-BPP` one). So far it's gone remarkably smoothly for me not knowing what I'm doing. At this point, other than cleaning up names, what else shall I do to improve it? If anyone wants edit access to the repo to fix it up, just let me know. A few points:
* I think we can stick with just Linux for the v1.8
* Where should the apptainer image be sent?
* Should there be a container for each py version or do ppl not care since layers are independent?

Thanks for any guidance and edits.

**Comment by AlexHeide** [comment]
Yeah sylabs would definitely work but only allows for storing .sif images. We could consider only offering `docker` containers and having `apptainer` users pull from `dockerhub`. See https://apptainer.org/docs/user/main/docker_and_oci.html#docker-hub. I know Jet loves using docker dev containers and I'm guessing others on the dev team do too. 

As an explicit example from apptainers docs: 
pull tensorflow and run with the host's amd gpu libraries loaded into the container. MPI is essentially the same.
```
$ apptainer pull docker://rocm/tensorflow:latest
$ apptainer run --rocm tensorflow_latest.sif
```

As described in the link I referenced there are a few peculiarities that we would have to work through so that our docker containers will run properly with `apptainer`. Off the top of my head the two main things would be:

* making sure nothing is being installed in `/root` or `/home` by default (easy)
* making sure that a writable filesystem is being mounted (The user would ultimately need to ensure that a scratch directory is available or that they're running from a directory/volume with disk space available)

If we wanted, it might be nice to convert the docker containers explicitly to apptainer format and upload to sylabs?  A new user at a super-computing institute probably wouldn't check dockerhub. For building apptainer containers, I normally start by pulling base iamges from dockerhub to work with. I haven't tried pulling and running docker containers directly though.

**Comment by jturney** [comment]
Yep, I love me some docker devcontainers 😀

**Comment by AlexHeide** [comment]
This also seems like a good time just to point out that if anyone has plans for portions of psi4 to use mpi parallelism, we would want to avoid having the psi4 executable explicitly call mpirun or similiar like `xcfour` does. The ideal mpi setup would be for the user to use the host's `mpirun / mpiexec` executable to run the container. Then, the host mpi and container mpi either need to use the same PMI library or the user would need to bind the mpi libraries into the container. GPU support only requires the `--rocm` and `--nv` flags that I referenced above.

**Comment by loriab** [comment]
Ok, I've secured `psi4` login at sylabs. I'm for storing them where they can be found. The "install apptainer" GHA only had two stars, so I bet there isn't a ready-made "upload to sylabs GHA".  I'm not sure if it's doing no root or writeable filesys or anything. Do you want repo access to play with it?

**Comment by AlexHeide** [comment]
That'd be great!
