### ISSUE TITLE
Calculation runs without molecule set

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#3115]
The input
```
set basis pcseg-0
energy('scf')
```
runs even though a molecule has not been set. It appears that Psi4 defaults to the hydrogen dimer. I don't think this functionality is a feature, since the behavior is unexpected.

**Comment by loriab** [comment]
Yes, it's [here](https://github.com/psi4/psi4/blob/master/psi4/driver/inputparser.py#L749). Rob Parrish added that long ago so that `database()` calculations, where a molecule isn't defined, could run. Now that I think on it, though, the other half of the necessity was because back then, one had to to set a molecule, then a basis set (reverse wouldn't get applied).

I think we can probably drop it now, unless there's other reasons I'm not thinking of. That H2 has caught me before, and I know about it. It's only active for PSIthon, not PsiAPI. And I've been surprised when other programs have a default basis set.

**Comment by susilehtola** [comment]
Yes, the program that shall not be named still defaults to STO-3G.
