### ISSUE TITLE
Make properties work for something besides CC

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4#40]
check other methods

**Comment by dgasmith** [comment]
OEProp will work on anything with a density matrix which is either passed through from SCF or explicitly set in a derived method. I am planning to close this for now and combine the OEProp cleanup into a single thread unless anyone has objections.

**Comment by CDSherrill** [comment]
Hm, I think the intent of this ticket was to have unified handling of
Daniel Crawford's properties[] keywords

**Comment by dgasmith** [comment]
Effectively we have quite a few tickets relating to properties and OEProp. I would very much like to consolidate most of these tickets into one so we can figure out what actually needs to be done. In many ways we probably should not propagate the current way the `cc` codes are handling the properties internally (the syntax is great), especially with regard to properties through OEProp.

**Comment by CDSherrill** [comment]
I agree that we don't want properties computations done internally --- we
want them done in a unified way through OEProp.  However, we do (I guess?)
want the user syntax properties = [ ... ] or whatever Daniel C. cooked up.
My understanding is that the CC properties user input syntax only works for
CC modules, which is not good.

Here's an example from cc52:

property('ccsd',properties=['roa_tensor'])

The reason Daniel developed this is because different modules need to be
run depending on the requested property.  This is not usually the case for
non-CC codes, but it is confusing to users to have this mechanism available
for CC properties but not for other properties.

I am fine with moving this over to some other more unified github issue, so
long as it is tracked somewhere.

**Comment by dgasmith** [comment]
I have overhauled this interface in #365  for SCF/DFT/MP2/CI so that the following now works:

```python
prop('above_method', properties=['any_opdm_func'])
```

See [here](http://www.psicode.org/psi4manual/master/oeprop.html?highlight=oeprop) for full OEProp functionality; this documentation and the `property` documentation also had a facelift in the PR.

Full tests suites can be found in the following test cases:
- ci-properties ('transition_dipole', etc, works here)
- mp2-properties
- scf-properties

I did not touch occ/dfocc/cc due to how they integrated their OEProp calls, but I would assume that this will eventually be deprecated.
