### ISSUE TITLE
Build psi 1.0rc with PCMSolver 1.1.2 fails

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4#417]
Both PCMSolver (in `pcmsolver.h`) and psi (in `src/lib/libpsipcm/psipcm.cc`) defined a `extern "C"` function called:
```c++
extern "C" void host_writer(const char * message, int message_length);
```
The fails to build of course (icpc 16.0.1):
```
error: more than one instance of overloaded function "host_writer" has "C" linkage
```
Please rename or adjust the function.

**Comment by loriab** [comment]
There was an issue for a little while where the latest pcmsolver tag (1.1.2 and current HEAD) had `int` for the second argument to `host_writer` while psi4 HEAD had `size_t`. This has since be reconciled. Any possibility that this is what you're seeing? Since that fix, psi4 + pcmsolver has been building ok for me with intel 16.0.3.

**Comment by wpoely86** [comment]
tested with 1.0rc2 and pcmsolver 1.1.3 and works fine again.
