### ISSUE TITLE
If I take a converged SCF calculation and run the SCF again with those orbitals, SCF won't converge.  

### ISSUE THREAD

**Issue by kannon92** [psi4/psi4#419]
Hey PSI4 developers,

I am writing a plugin to test a JK algorithm.  I want to run SCF in my plugin and test the new JK algorithm. 

Even though I pass a converged scf wavefunction to the plugin, the SCF procedure doesn't converge.  It seems that the wavefunction passing is messed up here.  

Here is the basic structure of the plugin:

    SharedWavefunction kevin_plugin(SharedWavefunction ref_wfn, Options& options)
    {
        boost::shared_ptr<Wavefunction> scf(new scf::RHF(ref_wfn, options, PSIO::shared_object()));
        double scf_energy = scf->compute_energy();
    } 
I run the plugin as follows:

    import kevin_plugin

    molecule H20 {
       0 1
       H
       O 1 1.08
       H 2 1.08 1 107.5
        units bohr
     }

     set globals {
     basis sto-3g
     df_basis_scf cc-pvdz-jkfit
     df_basis_mp2 cc-pvdz-ri
     scf_type     df
     reference    RHF
    }
    refenergy, refwfn = energy('scf', return_wfn=True)
    energy('kevin_plugin', ref_wfn=refwfn)

Here is the first scf:

         ==> Iterations <==

                           Total Energy        Delta E     RMS |[F,P]|

        @DF-RHF iter   0:   -75.66716318225211   -7.56672e+01   7.87344e-01
        @DF-RHF iter   1:   -73.90687341477560    1.76029e+00   2.74191e-02
        @DF-RHF iter   2:   -73.91391789759025   -7.04448e-03   3.08278e-03 DIIS
        @DF-RHF iter   3:   -73.91403288011436   -1.14983e-04   4.69651e-04 DIIS
        @DF-RHF iter   4:   -73.91403606558048   -3.18547e-06   5.07365e-05 DIIS
        @DF-RHF iter   5:   -73.91403611477740   -4.91969e-08   6.26518e-06 DIIS
        @DF-RHF iter   6:   -73.91403611547619   -6.98790e-10   5.20238e-09 DIIS

Here is the scf after my plugin is called:

    @DF-RHF iter   1:    15.38889387804263    1.53889e+01   0.00000e+00
    @DF-RHF iter   2:   -72.40376803946150   -8.77927e+01   3.34064e-01 DIIS
    @DF-RHF iter   3:   -72.40376803946153   -2.84217e-14   3.34064e-01 DIIS
    @DF-RHF iter   4:   -72.40376803946151    1.42109e-14   3.34064e-01 DIIS
    @DF-RHF iter   5:   -72.40376803946153   -1.42109e-14   3.34064e-01 DIIS
    @DF-RHF iter   6:   -72.40376803946153    0.00000e+00   3.34064e-01 DIIS
    @DF-RHF iter   7:   -72.40376803946148    4.26326e-14   3.34064e-01 DIIS

**Comment by andysim** [comment]
I can't explain why the second instance is not reading the orbitals.  A couple of quick tests that would be useful: a) does adding `set guess read` before the call to your plugin (and after the SCF call) change the behavior? and b) does the same thing happen if you call SCF instead of your plugin on the second function call?

**Comment by kannon92** [comment]
To answer your first question: `set guess read` does fix this problem.  

I can not pass a wavefunction to a second scf call.

     refscf, refwfn = energy('scf', return_wfn=True) 
     energy('scf', ref_wfn=refwfn) 
I get an error that scf_helper can not take a wavefunction.  Not sure if this is what you wanted me to do.

If I run two scf calls
     refscf, refwfn = energy('scf', return_wfn=True) 
     energy('scf')
This works fine.  This has the same effect as set guess read, so I guess there is a check to see if a previous scf has ran.   

So it seems that there is no problem with reading the orbitals, but passing them seems to be off.

**Comment by loriab** [comment]
Just like the error message warns, SCF is not set up to restart from a wavefunction because there's need-to-project?, need-to-orthogonalize?, etc. issues that have to be handled. The wavefunction passing is set up to the level that the old `bypass_scf` kwarg handled. That is, a _completed_ scf_wfn can be passed into CC, CI, etc.

**Comment by kannon92** [comment]
So the main reason why I feel that it may be important to have SCF take a wavefunction is if SCF guesses the orbital occupations wrong.  This tends to happen quite often in open-shell and transition metals.

How could I force PSI4 to guess an occupation that I believe is correct?  I tried to pass a modified wavefunction (swapped columns) to pass to SCF, but this is not allowed.  Is there another way to modify the SCF solutions if the occupation is wrong?   

I do not mean that the number of electrons is wrong, but mainly that there are orbitals that should be virtual but are included in the occupied space.

**Comment by dgasmith** [comment]
Mostly fixed in #481. As SCF is a special case of Wavefunction its not as easy as passing in a new Wavefunction as the order of precedence for occupations is not entirely clear (multiple user defines, options, and reference wavefunction). 

For now you can use the new HF setter `guess_Ca/Cb` to set the occupied "guess" orbitals before SCF iterations. See `scf_helper` in proc.py for examples. Orbitals ordering can be modified using the Matrix rotate_columns command. You can force occupations by setting DOCC/SOCC as they will now be respected in all instances. I will open a ticket shortly detailing the issues with the current SCF occupation scheme to see if anyone would like to come up with a better way.
