### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4#424]
I'm trying 1.0rc on a system with 128 GB of RAM. I've put `memory 90 gb` in the input file (meaning 70% of the memory) and started a calculation. What I see is that the memory usage indeed doesn't go above 70% but lots of swap is being used. This is not what I want: how do I avoid PSI of using more memory and starting swapping?

**Comment by dgasmith** [comment]
I don't quite follow, your system controls virtual memory paging not Psi.

**Comment by wpoely86** [comment]
Yes, I know but that's not what I mean. When I start the PSI calculation, the system has 122 GB of free RAM. Yet PSI causes it to start swapping (nothing else is running on it) and I want to avoid that.

So, how does PSI handle the `memory` line? What does it do when opening its large files? Do you use the `POSIX_FADV_DONTNEED` flag on those files?

**Comment by dgasmith** [comment]
There are very few algorithms in Psi4 that have pure in-memory algorithms. Almost all dump files to disk at one point or another.

**Comment by wpoely86** [comment]
And that's fine. But if it causes a system to go swapping, it's an issue. Either PSI should use `POSIX_FADV_DONTNEED` or pin the memory pages.

**Comment by dgasmith** [comment]
Can you define what you mean by swapping precisely? The POSIX flags should not be needed.

**Comment by loriab** [comment]
File handling in psi4 is managed through [psio](https://github.com/psi4/psi4/tree/master/src/lib/libpsio) which has served us well since psi3 days but hasn't received much development attention. Eventually, we hope to transition to HDF5 or similar. Is `POSIX_FADV_DONTNEED` worth trying to back-incorporate? I don't see any posix_advise calls in CheMPS2.

**Comment by bennybp** [comment]
When you say that the memory usage doesn't go above 70%, what do you mean precisely, and how is it measured? `vmstat -S M` during a run may help us see the breakdown of memory usage a bit.

I think the concern is that when using large files, the OS will try to keep (parts of) the files in memory for faster access later. Then these pages may get swapped (or just having them in memory causes other things to get swapped).

I'm not sure if/why the kernel would choose to swap rather than free some memory from the page cache (cached data is already on a disk...), but I'm far from a kernel memory expert.

Last note: Psi4 is mostly written in C++, and therefore can't always use `posix_fadvise`, since there's no (standard) way to get a `FILE*` or file descriptor from an `std::fstream`. Others can comment about how memory management in psi4 works, but I think it is pretty rudimentary and doesn't interact with the OS at all.

**Comment by dgasmith** [comment]
Will close this out soon unless there is further comment.

**Comment by wpoely86** [comment]
I don't have access any more to large memory systems and I haven't found the time to look at more recent version of PSI4. Yet the concern remains: you want to avoid that a system starts swapping.
