### ISSUE TITLE
Upcoming Psi4 changes

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#468]
Greeting friends,
As you may have heard we are in the process of several fundamental Psi4 change. These include: rewriting the build system, removing Boost from Psi4, the "inversion", and a history rewrite. Read below for summaries of each step and where to find more detailed information. If you have any questions please ask them here or email us directly.
## Steps

**Build system:**
The build system has moved to a "super build" strategy which reduces total compilation time and makes it much easier to add additional external libraries in the future. Developers will also see a reduction in the amount of time it takes to compile internal Psi4 changes and Psi4 can now link all external dependancies (libint for examples). Note that much of the github wiki on building psi4 is now plain wrong. Consult the top-level CMakeLists.txt to get building again. See [here](https://github.com/psi4/psi4/pull/442) for more information. 

**Boost:**
Much of the Boost functionality that we have depended on in Psi4 has been implemented in C++11. In order to keep Psi4 up to date with best C++11 practices, reduce complexity, and generally remove several headaches, Boost has been removed from Psi4. The C++ Python bindings have been moved to PyBind11. See [here](https://github.com/psi4/psi4/issues/450) for more information.

**Inversion:**
Currently the hybrid Python/C++ architecture of Psi4 is in an odd spot where Psi4 itself is a C++ program that calls an input file as a Python executable. This circular process will be removed and Psi4 itself will become a Python library capable of being imported just like any other module. This will allow Psi4 to be used in a normal python workflow with other scientific python programs like OpenMM, iPython, MolDesign, etc. In addition, python-based error messages will be more expressive and accurate. For users who enjoy the current Psithon interface the current Psi4 Psithon parsing equipment will be moved to a script named "psi4" in the binary location. This will allow all current Psi4 input files to be run normally.

**History rewrite:**
Over time the Psi4 git repository has accumulated many large files (mostly boost binaries) that are not currently used; however, they still exists within the repository and are downloaded every time the repository is cloned. This has caused Psi4 to balloon to approximately 650MB, while only about 65MB of that is currently used. In order to reduce the repository size, these files will be removed from history. When this occurs **_all_** current Psi4 clones **_and_** forks will become invalid. These will need to be deleted and reforked/recloned. 
## Schedule

We are currently planning to merge in the Boost removal and build system changes in the next day or so. It should be noted that while core Psi4 is stable, external projects such as ChemPS2 and EFP may not work. The build systems has also only seen compilation on half a dozen architectures and setups, you may encounter errors in the build process. A new branch named 1.0.x maintenance has been created that contains a stable and updated version of the 1.0 release. In effect, this means that the master branch will no longer be 100% stable for anything beyond "core" Psi4 as defined by quicktests. 

If you have changes to the Psi4 source code you will either need to rebase the CMake/build system change (hint: this is _not_ the occasion to learn to rebase) or rewrite these files by looking at a diff between the new version and your current version. A rebase of this patch is a considerable time investment with many small technical details, please contact us to help you if you decide to go this route. We will be contacting the authors of all current PR’s to help them with the transition.

The inversion and history rewrite will take place on October 17th. Again, all forks and clones will need to be removed at this point as they will no longer be valid. Let us know if you need additional time to rebase in a change.
## Summary

Changes for developers:
- **WARNING!** All clones and forks will need to be removed when the history rewrite occurs on October 17th. This means any current work on Psi4 will no longer be able to be merged. If you need additional time let us know ASAP!
- The build system has not been extensively tested, please try it out and report bugs.
- There is a completely new directory structure.
- No more Boost in core Psi4.
- Some external libraries may not work at current.
- Plugin structure is still fluid.
- GCC 4.9 is required due to C++11 regex. Keep in mind that ICC requires GCC.

Changes for users:
- If you use any of the pre-compiled options nothing will likely change in your everyday workflow.
- If you compile Psi4 yourself, these changes will require a completely fresh compile. The build script has moved away from setup.py to a pure CMake input.
- After the inversion you will still have the option to use standard "Psithon" inputs or to import psi4 as a Python module.
## Progress (master branch)
- [x] CMake Rewrite
- [x] Kill the boost
- [x] Inversion
- [x] History rewrite
- [x] Official 1.1 release
## 

Sincerely,
- Lori, Jet, Andy, and Daniel

**Comment by kannon92** [comment]
So I've been working on a mostly MPI things in my fork (Distributed CASSCF,  Distributed DFJK).  I have no idea how this workflow is going to be implemented in the future, so I am not not ready to merge this into the main branch before late October.  Unfortunately, I also used quite a bit of the now defunct (I think) libparallel2, so I am not sure where this will go.  If I have a fork of PSI4, will this fork be deleted in October?  

I also am not ready to merge any of this into a steady branch as it requires quite a bit of finesse (and various libraries) to run, so I would not want to release this yet.  

I realize that I will probably have to work with you all in order to merge these  changes at some point in the later future.  As long as my fork will not get deleted, I am perfectly fine waiting for this time to occur.

**Comment by loriab** [comment]
Your fork is safe. It'll just look something like 8000 commits behind master and 8050 commits ahead and quite un-PR-able against psi4/psi4 master. Yes, consulting us when you're ready to merge will be the thing to do.

**Comment by ryanmrichard** [comment]
@kannon92 libparallel2 is completely deleted.  The majority of that functionality now resides in [LibTaskForce](https://github.com/ryanmrichard/LibTaskForce), which admittedly has only been tested on a few MPI processes at the moment (hopefully, within the next few weeks I'll get a chance to try it on an actual supercomputer).  If you're interested in moving over to LTF I'd be happy to help; it could use a lot more stress tests (and honestly some code cleanup and documentation) that I've been putting off in favor of working on Pulsar and writing papers.

**Comment by jgonthier** [comment]
So once history is re-written, your advice is to delete all forks/local copies, and then re-fork, correct ?
In principle, if I have some changes in specific files, I should then be able to re-write these changes as well by just looking at the relevant diff ?

**Comment by kannon92** [comment]
@ryanmrichard My changes were mostly to allow GTFock to work on separate processor subgroups.  I used libparallel2 (or maybe libparallel) just to create communicators.  I did not really try any of the task schedulings.  I guess I really only use boost::mpi, but it should be a simple change to just normal MPI.

**Comment by ryanmrichard** [comment]
The biggest change between boost::mpi and normal MPI is the lack of templated calls.  In normal MPI you always need to specify the type of the data you're passing to MPI, but aside from that you're right it's a pretty simple change between the two.

**Comment by dgasmith** [comment]
@jgonthier Effectively yes, when we rewrite the history no merging can take place so its best to simply remove all old history. Git will throw some pretty strange errors at you if you try. You can use the git merging tool without history (will throw conflicts at every change however), or other merging tools to help out.

Since its fairly difficult to rebase through the CMake changes it was thought that this would be a ideal time to do the history rewrite. Git should be setup correctly with the external projects so a similar history rewrite should not be needed again.

**Comment by dgasmith** [comment]
The build system and kill the boost steps have been merged in. Give it a try!

**Comment by loriab** [comment]
Yes. As far as add-ons:

**Working:** `libint`, `libefp`, `liberd`, `dkh`, `gdma`, `CheMPS2`
**Unknown:** `GTFock`
**Not Working:** `PCMSolver` (this is in progress, but if you need it, it's within a few path hacks of working, so contact us)

All of these can be compiled once and detected by the Psi4 superbuild, so possibly you need only compile libint/deriv one more time.

Again, much of the build wiki is no good anymore. A mini compilation guide is at the top of the (main CMakeLists.txt)[https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L13-L102]

**Comment by kannon92** [comment]
Alright, I'll pull it and give it a try.  

@loriab what about ambit?

**Comment by loriab** [comment]
Regarding Ambit, Jet did a lot of the CMakeRewrite stuff, but I don't thing the Psi4 build system has been prepped to detect it. More importantly, I think KillTheBoost has to be done for Ambit before it's worth finializing the CMake for it.

**Not Working:** `Ambit`, `v2rdm_casscf` (where not working means you'd have to do some real build work to get them running)

**Comment by jturney** [comment]
I'm working on Ambit and should be done in another day or so.

**Comment by kannon92** [comment]
Oh alright.  Thank you, @jturney.

I was able to compile this on my mac with clang 4.0.0.  I am running the quick test suits, but it seems that everything works pretty smoothly.  However, you do have to specify -DENABLE_AMBIT=off.  If I don't specify this, I get a CMAKE_ERROR about boost and ambit.

**Comment by loriab** [comment]
That's odd, everything's [off by default](https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L59). You should definitely be doing a fresh build directory, if not a fresh clone, after those 250+ commits.

**Comment by kannon92** [comment]
Yes, I re-cloned everything.  All quicktests passed on my laptop.

**Comment by robertodr** [comment]
@loriab What's the problem with PCMSolver? The nonstandard install paths?

**Comment by loriab** [comment]
The primary problem with PCMSolver is that I was only partially through its CMake refresh. I went ahead and [opened a PR](https://github.com/PCMSolver/pcmsolver/pull/31) with the changes thus far. The two primary items are (1) pcm_placeholder lost its configuration step, so you have to manage the PATHs yourself and (2) I'd like to do an inversion of the PCMSolver install so that it becomes a more natural python module to import (installed to site-packages) rather than the involved bin/configure/write-to-source-dir business. It is runable at the moment, though, if you're determined (I included an outline of steps at the PR).

**Comment by amjames** [comment]
How do we want to be brining up problems in the new build system? Are we opening new issues, or posting them here? 

Also should we direct people seeking help to the forum or should we post questions here?

**Comment by loriab** [comment]
Hmm, good question. This issue has a nice generic title, so let's call this the CMakeRewrite-KillTheBoost triage issue. If the question/problem is going to lead to changes in code, it can be converted to a separate issue. 

For generic (not particularly related to CMakeRewrite-KillTheBoost-TheInversion) help seeking, I'd refer people to the forum, but the crossover line is blurry.

**Comment by amjames** [comment]
Well in that case: 
So far everything is going smoothly on my end, but I did notice a couple of inconsistencies in detecting python/complier versions and incorrectly using a different library. On one of our clusters using the module system I have loaded gcc-5.2.0 and Anaconda with python 2.7.10. (these modules define envars $ANACONDA_LIB  and $GCC_LIB, which I will refer to below. They also modify the $LD_LIBRARY_PATH variable when they are loaded.) 

If I set the python executable and don't do anything to `CMAKE_PREFIX_PATH` the executable is set up correctly but the `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY` find the ones that live in the system paths `/usr/lib/python2.6.so` and `/usr/include/python2.6` which causes problems in the linking step with undefined references to some python stuff. 

Also if I set the C/CXX compiler, but again don't do anything to the ` CMAKE_PREFIX_PATH` I can build + link fine, but at runtime I will get errors like this:

```
/usr/lib64/libstdc++.so.6: version ``GLIBCXX_X.X.XX'  not found 
```

Which seems to be that cmake is linking to the libstdc++ version for the system gcc which is 4.7.2, instead of the correct library version for the compiler I am using. 

If I add `-DCMAKE_PREFIX_PATH=$GCC_LIB:$ANACONDA_LIB` to my cmake command it will fix both issues are corrected. The python library is detected as `$ANACONDA_LIB/python2.7.so` and I don't have any problems with linking. And there is no errors at runtime either.

In both cases cmake seems to detect the versions correctly since it has the correct executable. 

So when it comes time to document the new build system for users, it may be prudent to mention they should either use the `CMAKE_PREFIX_PATH` argument, or check that cmake has detected the correct library paths for the python/compiler they actually meant to use if they are working in a environment where multiple python/compilers installed. Most clusters will have some way of swapping these out with a system default installed globally.

**Comment by loriab** [comment]
That's interesting, @amjames. I'm definitely familiar with the ``GLIBCXX_X.X.XX`` runtime error (https://github.com/psi4/psi4/wiki/8_FAQ_Contents#how-to-satisfy-the-gcc--49-requirement-without-updating-the-os). What I think is going on is that it is building and linking correctly to the >=4.9 `$GCC_LIB` libraries. But then at runtime, it doesn't know where to find them, as that particular aspect wasn't baked into `rpath`. `ldd -v psi4` will likewise show runtime environment incorrectly using system gcc. I hadn't ever tried manipulations of `CMAKE_PREFIX_PATH` for solving this. _Without recompiling_, can you turn your failing `GLIBCXX_X.X.XX not found` into a working compilation by just manipulating `LD_LIBRARY_PATH` as in the final line of that FAQ? That will help confirm we're talking about exactly the same issue.

**Comment by andysim** [comment]
Just to let you know, I updated to Mac OS Sierra and the new build system works great with Apple Clang 8.0 right out of the box.

**Comment by amjames** [comment]
@loriab I am re-creating the broken build now and I will look at what `ldd -v psi4` gives me, but I did try modifying the `LD_LIBRARY_PATH` to fix the `GLIBCXX_X.X.XX` runtime error with no luck. Actually loading the GCC_5.2 module would modify it for me, but I removed /usr/lib64 from it just to be sure.

**Comment by amjames** [comment]
@loriab I must have made a mistake while I was playing around with this. The error does not appear if I have `LD_LIBRARY_PATH` set correctly at run-time and if I don't have the correct compiler module loaded then cmake errors out in the configure step.

**Comment by loriab** [comment]
Ok, @amjames, I'm glad to hear that it's behaving according to my expectations. I wonder if setting `CMAKE_PREFIX_PATH` is still an alternate solution. The thing is, CMake detects GCC libraries implicitly, so it's hard to `rpath` them. 

Ugg, python detection. That issue remains, I presume. That's interesting that `CMAKE_PREFIX_PATH` will help python detection; I had never tried that. I agree, there should be some advice to just set all three python variables, if you're going to set any. And an example for anaconda python. You're welcome to add such to [here](https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L39-L41), but try to stay compact. Otherwise, I'll add something later. A lot of these python detection problems should be eliminated by The Inversion, because we won't be _embedding_ python, just _linking_, so python can use its own `python-config` tech to load its library.

**Comment by amjames** [comment]
@loriab I think setting `CMAKE_PREFIX_PATH` can help with detecting anything usinga `find_package` call. 
Setting `CMAKE_PREFIX_PATH` has the search to prioritize the directories listed in that variable. I actually have no python detection problems if I set `-DCMAKE_PREFIX_PATH=${ANACONDA_LIB}:${ANACONDA_INC}`, but only setting one or the other means either the wrong headers or the wrong library is found instead. Just slightly less typing than setting two separate `PYTHON_…` variables

-------

Also worth mentioning: It looks like [here](https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L110) we are only setting the major python version as a requirement, so I am not getting any cmake errors if I remove anaconda from my env, and let the system python be detected (in my case 2.6.9, which is okay I think).  But in the cmake output I see a message like: 

```
— Found PythonInterp: /usr/bin/python (found version "2.6.9)
— Found PythonLibs: /usr/lib64/libpython2.6.so (found sutable version 2.6.9, minimum required is "2")
```

Is that going to go ahead and build if the python version is `2.(anything)`? Last I remember we needed python 2.6.9 or later.

**Comment by loriab** [comment]
Good to know on the `CMAKE_PREFIX_PATH` for python detection. That should probably become the preferred way to detect Anaconda python. To have multiple items in that var, use something like `-DCMAKE_PREFIX_PATH="${PFXE}/install-libefp-so;${PFXE}/install-libint-6-so;${PFXE}/install-pcmsolver"`, in case you hadn't already worked that out.

Quite right about 2.7. At some point I stopped adapting my dictionary comprehensions for the 2.6 folks. I'm guessing it will build/link, but you'd get driver errors at runtime. Should be detecting a 2.7 minimum in cmake. One thing we want to do really soon is allow/switch to 3.5, switch to pythonlibsnew cmake module, and probably to offload python library detection to pybind11, so don't spend too much time playing around with the current python cmake, except for your own edification. Do feel free to switch that line you linked to to 2.7 .

**Comment by dgasmith** [comment]
For those interesting in the `inversion` step you can check out the `inversion` branch [here](https://github.com/dgasmith/psi4/tree/inversion). It is reasonably stable at this point. Feel free to comment, try it out, and take on any issue under "Projects".

**Comment by jgonthier** [comment]
@loriab I now have the same problem than @amjames regarding libstdc++.so. Quick context:
I installed my own GCC 5.2 using my own conda, then gave cmake the necessary info (through ``-DCMAKE_CXX_FLAGS`` and modified ``LD_LIBRARY_PATH``. I also installed Python 3.5 in conda and gave the paths to CMake using the ``PYTHON_LIBRARY`` and ``PYTHON_INCLUDE_DIR`` variables.

With that, I could build and link (after a few tries) but a bunch of tests failed, seemingly Python-related. I thus tried to re-build, but giving the system Python (2.7) and Python libraries. For that, I modified my PATH environment variable so that Python 2.7 would be default and not the conda Python 3.5. I could build and link successfully, but now for some reason psi4 is associated with the wrong gcc headers.
My CMakeCache.txt contains the appropriate ``gcc-name`` options described in the FAQ, the first line of ``echo $LD_LIBRARY_PATH`` reads
``/theoryfs2/ds/gonthier/software/miniconda3/envs/gcc52/lib:/theoryfs2/ds/gonthier/software/miniconda3/lib:/theoryfs2/common/software/intel2016/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64``
and ``ldd psi4`` gives:
``libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fe059a33000)``

I haven't tried using ``CMAKE_PREFIX_PATH`` yet. I'm going to do that now and report the results.

**Comment by loriab** [comment]
@jgonthier, if you can build successfully, then it's getting the `-gcc-name`/`-gxx-name` – no more recompile necessary. It would have failed to build libmints if that part wasn't right. 

You're right that your `ldd psi4` will cause trouble – in fact it should have given you `CXXABI` and `GLIBCXX` errors just in the `ldd psi4`. Your `$LD_LIBRARY_PATH` should have fixed it, though. Any chance that's not in effect in the terminal you're running the `ldd psi4` in? If the gcc52 was in ld_library_path, your ldd psi4 should switch immediately to `libstdc++.so.6 => /theoryfs2/ds/cdsgroup/miniconda/envs/sgcc5/lib/libstdc++.so.6`.

Alternatively, you can delete `stage/......../bin/psi4` (that file only) (or lib/psi4/core.so if you're on inversion) and edit w/i objdir `psi4_core-prefix/src/psi4_core-build/src/CMakeFiles/psi4-bin.dir/link.txt` (psi4-lib.dir if you're on inversion) and stick your gcc5 path first behind the `rpath` at the end, then rebuild (will only relink).

I named my env `sgcc5`. Looks like you named yours `gcc52`. Could there be name mixing?

**Comment by jgonthier** [comment]
@loriab Thanks for the tips. ``LD_LIBRARY_PATH`` is in effect in my terminal, here are the results of commands directly issued in the same terminal:
``>> echo $LD_LIBRARY_PATH``
``>> /theoryfs2/ds/gonthier/software/miniconda3/envs/gcc52/lib:/theoryfs2/ds/gonthier/software/miniconda3/lib [...]``
then:
``>> ldd stage/usr/local/bin/psi4``
``>> stage/usr/local/bin/psi4: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by stage/usr/local/bin/psi4)``
``stage/usr/local/bin/psi4: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by stage/usr/local/bin/psi4)``
``stage/usr/local/bin/psi4: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by stage/usr/local/bin/psi4)``
[...]
``        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fd93dcba000)``
``        libiomp5.so => /theoryfs2/ds/gonthier/software/miniconda3/lib/libiomp5.so (0x00007fd93d970000)``
[...]

As you can see, the correct path is in ``LD_LIBRARY_PATH``, yet ``ldd psi4`` does not find the correct ``libstdc++.so.6``, yet ``libiomp5.so`` finds the miniconda path that is in ``LD_LIBRARY_PATH``

Finally, I tried your suggestion to directly modify the ``link.txt`` file with explicit specification of the ``gcc52`` path. Sure enough, this worked ! Psi4 finds the correct gcc library and runs like a charm (well, I barely started the tests so let's keep the fingers crossed).

I don't see with what ``gcc52`` could mix, since I don't have any other environments defined. Plus, I'm never using ``source activate gcc52`` because this command does not work any more, at least on ``ds3`` (can you tell the software has been quite hostile to me on this build ?)

Thanks for everything anyway. Should I report back with possible test failures here again or open a new issue ?

**Comment by loriab** [comment]
Hmm, I wonder if some other dependency was detected in /usr such that it got baked into rpath at a high position. Depending on rpath/runpath, LD_LIBRARY_PATH may or may not trump it. Otherwise, I quite agree that you are typing sensibly and the computer is behaving not. `source activate` only works with bash– could that be the problem with that command? If you're on psi4/psi4 (CMR-KTB) and anything besides `psimrcc-fd-freq2` fails, yes, post it here. If you're on dgasmith/psi4 inversion (CMR-KTB-INV), then we're only up to 92% passing anyways.

**Comment by jgonthier** [comment]
In my case, there is a dependency on Python 2.7 library in /usr/lib64. It might be the problem since when using Python 3.5 out of my miniconda, I had no problems with GCC. The only other thing that changes is my ``PATH`` variable where ``/usr/bin`` has a higher priority so that Python 2.7 is default instead of 3.5, but that should not change the library paths.

My problem with ``source activate`` was indeed because of the ``tcsh`` shell.

Finally, Psi4 with Python 2.7 compiled and tested successfully, only ``psimrcc-fd-freq2`` fails. With Python 3.5, there are more test failures, namely:
The following tests FAILED:
          9 - cbs-delta-energy (Failed)
         10 - cbs-xtpl-energy (Failed)
         12 - cbs-xtpl-gradient (Failed)
         13 - cbs-xtpl-opt (Failed)
         14 - cbs-xtpl-func (Failed)
         15 - cbs-xtpl-wrapper (Failed)
        118 - dfmp2-1 (Failed)
        168 - freq-isotope (Failed)
        170 - fnocc2 (Failed)
        175 - gibbs (Failed)
        192 - mp2-def2 (Failed)
        202 - nbody-he-cluster (Failed)
        203 - numpy-array-interface (Failed)
        255 - psimrcc-fd-freq2 (Failed)
        259 - psithon2 (Failed)
        260 - pubchem1 (Failed)
        261 - pubchem2 (Failed)
        262 - pywrap-alias (Failed)
        263 - pywrap-all (Failed)
        265 - pywrap-cbs1 (Failed)
        270 - pywrap-db1 (Failed)
        271 - pywrap-db2 (Failed)
        273 - pywrap-freq-e-sowreap (Failed)
        274 - pywrap-freq-g-sowreap (Failed)
        275 - pywrap-molecule (Failed)
        276 - pywrap-opt-sowreap (Failed)
        287 - sapt6 (Failed)
        307 - tu6-cp-ne2 (Failed)
        312 - options1 (Failed)
        317 - psi4numpy-rhf (Failed)
        318 - psi4numpy-dfmp2 (Failed)
        319 - dftd3-energy (Failed)
        320 - dftd3-grad (Failed)
        321 - dftd3-psithon2 (Failed)
        322 - dftd3-version (Failed)

I looked at one of them and the problem was the formatting of some printing command. I didn't investigate further.

**Comment by dgasmith** [comment]
@jgonthier The driver has been in an out of Python 3 compatibility, considering the recent changes im not surprised that quite a few fail.  

Probably a good TODO item after the inversion goes through is to update the driver to Python 3 standards and add a Travis case to ensure it stays there. From SciPy this year it appears that there is quite a bit of momentum to actually get everyone on board with Python 3, so its probably a good time to officially support it.

**Comment by loriab** [comment]
Glad rpath behavior is making more sense, @jgonthier . Unless all dependencies are isolated behind one environment (conda strategy) or each dependency is isolated in its own environment (a programming-using-conda strategy, but hard when `/usr/` involved), it can be impossible for cmake to predict a safe `rpath` path. I regularly have to edit mine to get the right HDF5 linked. As I don't know a winning strategy, I think we can't guarantee the built exe/lib will run, only that the conda ones will. This does show we need better notes on the matter so people can diagnose and correct.

**Comment by CDSherrill** [comment]
Do we need to break down and insist that people specify the python to use
via some kind of flag?  It seems that cmake picking up the wrong one is a
problem that just won't go away.  And/or perhaps a little test script that
might check the settings and verify that they will work with the user's
PATH?

At the very least, we do certainly need updated documentation on the latest
iteration of the build system, if we don't have it yet.

**Comment by ryanmrichard** [comment]
CMake already declares those variables and they are in the build 
documentation (which is inside the top

level CMakeLists.txt at the moment).


The relevant variables are PYTHON_EXECUTABLE, PYTHON_LIBRARY, and 
PYTHON_INCLUDE_DIR


	

	

on 10/11/2016 10:10 AM, David Sherrill wrote:

**Comment by loriab** [comment]
There's temporary build docs linked off README: "Downloading and Installing" on the main GH page.

It's not the specification of Python that's the problem– CMake detection and build are going just fine in these cases. CMake knows the exact, absolute path location to everything Psi4 or its build needs. The problem is conveying that info to the runtime environment. This is done by baking in all those absolute paths into the executable/library rpath. _But_, when a path (e.g., `/usr/lib`) has both a useful thing like `libpython.so` and a bad thing (for Psi4) like old gcc or hdf5, then CMake has no way of knowing that it needs to place /usr/lib into rpath _behind_ the path to new gcc or new hdf5. Thus, we end up with runtime path problems, solvable only by `LD_LIBRARY_PATH` or rpath adjustment and relinking.

This problem is controllable with conda, because it isolates just what Psi4 needs into its own namespaced path and stuffs that into rpath. For the general developers CMake build, there's no robust solution that I can see.

**Comment by CDSherrill** [comment]
Sounds like some of these problems are hard to detect at compile time, but
perhaps they could be diagnosed by some simple little program that's
designed to look for these kinds of problems and prints out verbose output?

**Comment by loriab** [comment]
I think there's more variations and potential collisions, even within one user's environment, than can really be predicted and caught. In the inversion branch, we've started catching the gcc <4.9 error signature and printing a this-is-probably-what's-wrong message. Expanding that error catching and printing the customized path to the `link.txt` file is probably the best bet.

[This](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/scripts/setenv.py) is a runtime env diagnosis script I wrote once. It didn't catch on, but it could be expanded for rpath.

**Comment by kannon92** [comment]
I had no problems with compilation on my laptop (clang 4.0.0) and on our cluster (gcc-4.9, g++-4.9).  However, I am not able to generate plugins.

This command gives the following error:

    $PSI4HOME --new-plugin-makefile psi4_inversion
    raise KeyError("The file %s does not exist." % args["input"])
    KeyError: 'The file input.dat does not exist.'

If I create a blank input.dat file, it does not quit without an error, but it doesn't read the --new-plugin-makefile option.

**Comment by loriab** [comment]
That sounds about right, @kannon92, plugins haven't made the CMR-KTB-INV leap. The writing thereof will be converted to py-side, and the building thereof will be converted to CMake. But neither done yet.

**Comment by kannon92** [comment]
Oh, thank you @loriab.

**Comment by dgasmith** [comment]
As a heads up, we are currently in the process of rewriting the history.

**Comment by dgasmith** [comment]
The history rewrite is complete, at this point please remove all forks and clones and refork/clone respectively.

**Comment by jgonthier** [comment]
Any plan on what's going to happen to the private branch ?

**Comment by loriab** [comment]
We want to kill it off. I think there'll be a survey at the developers conference. Do you have an opinion, @jgonthier?

**Comment by jgonthier** [comment]
@loriab: Killing it off is fine with me. My only concern was the ability to work on a private project, but Github allows us to create our own private copy of the repository (through duplication, I believe). So if that's right, there is no reason to get through the hassle of maintaining private for everyone.

**Comment by CDSherrill** [comment]
Can the average github user create a handful of private projects and then
invite certain collaborators to have access?  If so, then I think this
would suffice as a replacement for the centralized private repo.

David

**Comment by dgasmith** [comment]
GitHub users with valid '.edu' email address can receive unlimited private repositories through the GitHub Education site.

**Comment by loriab** [comment]
Concur with @dgasmith. Lasts for two years and renewable.

**Comment by andysim** [comment]
I use the $7 a month option on GitHub.  Those without a .edu can also use local GitLab servers, or BitBucket to develop private features, and push them to GitHub when they're ready to see the light of day.

**Comment by dgasmith** [comment]
Closing this out as the 1.1 release is imminent. Several places link back to this thread for reference.
