### ISSUE TITLE
scale down dmrg/caspt2-n2 test case

### ISSUE THREAD

**Issue by mbanck** [psi4/psi4#474]
The ```dmrg/caspt2-n2``` is quite large compared to the quicktests.

I am no expert in DMRG, but maybe scaling down the active space to 6 orbitals would be ok for code-coverage?

I use the following patch in Debian:

```
--- ./tests/dmrg/caspt2-n2/input.dat.orig       2016-09-23 21:52:13.874684018 +0200
+++ ./tests/dmrg/caspt2-n2/input.dat    2016-09-23 21:58:45.226670772 +0200
@@ -13,8 +13,8 @@

 set dmrg_irrep                0
 set dmrg_multiplicity         1
-set restricted_docc           [ 1 , 0 , 0 , 0 , 0 , 1 , 0 , 0 ]
-set active                    [ 4 , 0 , 1 , 1 , 0 , 4 , 1 , 1 ]
+set restricted_docc           [ 3 , 0 , 0 , 0 , 0 , 3 , 0 , 0 ]
+set active                    [ 1 , 0 , 1 , 1 , 0 , 1 , 1 , 1 ]

 set dmrg_sweep_states         [   500,  1000]
 set dmrg_sweep_energy_conv    [ 1e-10, 1e-10]
@@ -41,6 +41,6 @@

 energy("dmrg-caspt2")

-compare_values(-109.15104350802, get_variable("DMRG-SCF ENERGY"), 6, "DMRG-SCF Energy")   #TEST
-compare_values(-109.2680229921, get_variable("CURRENT ENERGY"), 6, "DMRG-CASPT2 Energy")   #TEST
+compare_values(-107.2576689206, get_variable("DMRG-SCF ENERGY"), 6, "DMRG-SCF Energy")   #TEST
+compare_values(-107.5036855148, get_variable("CURRENT ENERGY"), 6, "DMRG-CASPT2 Energy")   #TEST
```

**Comment by loriab** [comment]
Yes, `dmrg/caspt2-n2` is long compared to quicktests, but it's not in quicktests. Are you concerned about the length of the full test suite or about there being no caspt2 representative in quicktests?

**Comment by mbanck** [comment]
Hrm, I was under the impression that none of the dmrg tests are being exercise by ```quicktests``, so I run the dmrg tests in addition. Granted, this does not strictly have anything to do with ```quicktests``` I guess, but I think the dmrg tests shoudl either interface with ```quicktests``` or at least be of the same order of magnitude.

**Comment by loriab** [comment]
Ah, so what happens is _if_ CheMPS2 is enabled, then its four tests get added, and one of those (`scf-n2`) gets added to quicktests (https://github.com/psi4/psi4/blob/master/tests/CMakeLists.txt#L113-L118, https://github.com/psi4/psi4/blob/master/tests/dmrg/scf-n2/CMakeLists.txt#L3). So there's some coverage at both levels. Admittedly, I need to check if other add-ons follow that scheme. I certainly agree that if any add-on is enabled, its failure needs to be caught at the quicktest level of testing.

**Comment by mbanck** [comment]
Ah ok. In that case I think you're right that I was concerned about no CASPT2 representative in quicktests. As a wishlist, it would be nice to split up that case in a quick and long one I guess

**Comment by loriab** [comment]
Ok, sounds sensible. I want to keep the existing caspt2, but I'll add another that runs with quicktests.

**Comment by loriab** [comment]
BTW, we design quicktests so that they pass with `MAX_AM_ERI=4`, so if you're building the integrals internally, that's a possible time savings. Just in case you hadn't noticed and were sensitive to testing time.

**Comment by mbanck** [comment]
Thanks for the hint, but we're using an external libint

**Comment by loriab** [comment]
I'm glad to hear you're using an external libint; I hope everyone will be soon. If you've switched from the [patch](https://anonscm.debian.org/viewvc/debichem/unstable/psi4/debian/patches/system_libint.patch?view=markup) to the [new external repo](https://github.com/psi4/libint) and it gives you any problems, please let us know.

**Comment by mbanck** [comment]
I didn't know about the new external repo - we are using the upstream libint-1.1.5 package, as it is required by several other codes as well, most notably CP2K.

Did you officially take over maintainership of the libint-1 branch from evaleev? Do you plan to make regular releases? Is there a big code-difference between the new repo and the last libint1 tarball from Sourceforge and/or https://github.com/evaleev/libint/releases/tag/release-1-1-6 ? 

I'll take a look at that repo once I have time, thanks.

**Comment by loriab** [comment]
No, we haven't taken over maintainership of libint-1 from Valeev. There's a bit of history at the README of https://github.com/psi4/libint . We'll probably mirror any bugfixes that Valeev implements. The new external repo is based on libint as extracted from Psi4, not on https://github.com/evaleev/libint/releases/tag/release-1-1-6 . I did a grand diff at one point, and there were very many little changes; so many that I did not examine them further, yet they were mostly line tweaks, not insertions/deletions. That's actually interesting that you've been using Valeev's libint-1 with Psi4, and it's presumably been working just fine. I don't think any of the Psi4 development people have tried that in years.

The main purpose of the psi4/libint repo has been to get libint built with CMake and to get it switched over to exporting CMake targets through `libintConfig.cmake` rather than detecting the installation through `Findlibint.cmake`. In that, we may have broken your ability to use your upstream libint-1.1.5 package, as the Psi4 build system expects to link to a `libint::int` target. If there are things we can do to make your life easier in not dealing with two libint-1's, let us know. Our external repo does respect `GNUInstallDirs`. 

Psi4 will probably switch over to libint-2 when we get the time. But once again, we'll want a CMake build and exported targets. Hopefully, we'll be able to contribute those changes upstream to evaleev/libint, as we have with other projects (e.g., CheMPS2).
