### ISSUE TITLE
Mac binary

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4#49]
Can we create a portable Mac binary for binary distribution?

**Comment by loriab** [comment]
Converting this ticket over to "Make a conda binary for Mac". A monolithic package with boost baked in shouldn't be tricky. I've had some trouble with lib linking of hdf5 or gsl when building conda CheMPS2 on Mac, but a binary w/o CheMPS2 would be a leap forward and sufficient to close this ticket. Note that conda packages are relocatable, and I've finagled PSIDATADIR so that it doesn't need to be reset. Bonus: use intel compilers/mkl.

**Comment by loriab** [comment]
Ok, this exists. It's only compiled to AM=5, uses Apple native accelerate framework blas and lapack, and probably only runs on 10.10 and 10.11. But it can:

* run for casual purposes, if not production
* useable with plugin commands `--new-plugin` and `--new-plugin-makefile` (more at [manual](http://psicode.org/psi4manual/master/plugins.html#creating-a-new-plugin-using-a-conda-pre-compiled-binary))

Could use more reports at http://forum.psicode.org/t/mac-binary-testing/209/2
