### ISSUE TITLE
restart

### ISSUE THREAD

**Issue by pren** [psi4/psi4#51]
It would be nice to have restart capability for SAPT and other expensive calculations.

**Comment by similt** [comment]
I am running expensive SAPT calculations and psi4 dies due to time limit.
My calculations reached upto "  CHF Iterations converged " and then killed due to teh 
time limit of my queue system. It is possible to add restart option to sapt ?

**Comment by CDSherrill** [comment]
@jgonthier  is there any easy way to turn on or off different components of the SAPT computation?  That is, compute only the electrostatic and induction terms, or only the dispersion terms, etc.  That might be easier to do than (and/or an initial step towards) full restart capability.

@loriab it would be interesting to debate this as a use-case for more general restart capabilities.  Where do we log the info about how far the computation has gotten?  And what information is going to be available for the restart calculation?  In a cluster computing environment, the scratch files are going to be gone.  We could save the orbitals (although that's probably not the rate-determining step of most SAPT computations, regardless of the SAPT order).  Other stuff is probably too large to save anywhere for a restart.

**Comment by jgonthier** [comment]
@CDSherrill It depends on which SAPT computation. For SAPT0, it should be pretty straightforward as there is no intermediate reuse. If we go to higher SAPT order, it may require a little bit more work as I believe Ed's code is preparing integral files and writing them to disk at some point. In any case, it's probably the easiest way to implement a restart, yes.
@similt : Which SAPT level do you need ?

**Comment by similt** [comment]
@jgonthier I am interested in SAPT0.

**Comment by jgonthier** [comment]
@similt I just added options to compute only specific SAPT0 terms (e4070d0024742579a445e084da9dde078310094d). You should be able to use it if you pull Psi4 latest version from Github. I will update the manual shortly, but in the meantime, here is how it works.
The three options are
- sapt0_e10
- sapt0_e20ind
- sapt0_e20disp
If none of these options is specified, SAPT0 proceeds as usual. If one or more of these is specified, only the specified terms are computed. Be aware that the driver will still perform the 3 SCF computations for the monomers and the dimer, and that all preparative work (computing integrals) will always be done.
Also, the \delta_{HF} term is computed from first- and second-order terms, so if some of them are not computed, \delta_{HF} will be wrong. Similarly, exchange scaling is computed from first-order exchange, so it will not be valid if first-order exchange is not computed. However, you can easily compute these terms (see the manual for their definition) from gathering all SAPT0 data from different output files.

Simple example to compute only dispersion terms:
molecule dimer {
0 1
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000
--
0 1
O   1.350625   0.111469   0.000000
H   1.680398  -0.373741  -0.758561
H   1.680398  -0.373741   0.758561
}

set {
basis jun-cc-pvdz
scf_type df
e_convergence 10
guess sad
sapt0_e20disp   true
}

energy('sapt0')

Finally, if redoing the 3 SCF is too much of a hassle, you could write the final orbitals and feed them to the SCF so that they converge in 1 iteration. It's not really ideal but it works.

**Comment by similt** [comment]
@jgonthier Thanks a lot for your effort. Now I could calculate each sapt0 term separately. 
But when I tried to use restart option ( energy('sapt0',restart_file=['f1','f2'])), programs runs as usual, scf doesn't finish in 1 step. How to fix this problem ?

**Comment by jgonthier** [comment]
@similt Right now, the driver is doing a lot of work behind the scene by running the 3 SCF and handling all relevant files. If you want to feed orbitals into the SCF, you need to do all of that directly in the input file. That is not really pretty, and right now we are changing some things in Psi4 infrastructure, which means the same input file might need tweaking in future versions. Below is an example with the molecule you had above. The symmetry c1, no_reorient and no_com options *must* be there, I also assumed you had the orbital files at hand already.

molecule dimer {
0 1
O -1.551007 -0.114520 0.000000
H -1.934259 0.762503 0.000000
H -0.599677 0.040712 0.000000
--
0 1
O 1.350625 0.111469 0.000000
H 1.680398 -0.373741 -0.758561
H 1.680398 -0.373741 0.758561
symmetry c1
no_reorient
no_com
}

set {
basis jun-cc-pvdz
scf_type df
e_convergence 10
guess read
}

dimer = psi4.get_active_molecule()
psi4.IO.set_default_namespace('dimer')
psi4.set_local_option('SCF', 'SAPT', '2-dimer')
psi4.set_global_option('DF_INTS_IO', 'SAVE')

energy('scf',restart_file='./psi.15065.dimer.180')

psi4.set_global_option('DF_INTS_IO', 'LOAD')

monomerA = dimer.extract_subsets(1, 2)
psi4.IO.change_file_namespace(97, 'dimer', 'monomerA')
psi4.IO.set_default_namespace('monomerA')
psi4.set_local_option('SCF', 'SAPT', '2-monomer_A')

energy('scf',restart_file='./psi.15065.monomerA.180')

monomerB = dimer.extract_subsets(2, 1)
psi4.IO.change_file_namespace(97, 'monomerA', 'monomerB')
psi4.IO.set_default_namespace('monomerB')
psi4.set_local_option('SCF', 'SAPT', '2-monomer_B')

energy('scf',restart_file='./psi.15065.monomerB.180')

psi4.IO.change_file_namespace(p4const.PSIF_SAPT_MONOMERA, 'monomerA', 'dimer')
psi4.IO.change_file_namespace(p4const.PSIF_SAPT_MONOMERB, 'monomerB', 'dimer')

activate(dimer)
psi4.IO.set_default_namespace('dimer')
psi4.set_local_option('SAPT', 'E_CONVERGENCE', 10e-10)
psi4.set_local_option('SAPT', 'D_CONVERGENCE', 10e-10)
psi4.set_local_option('SAPT', 'SAPT_LEVEL', 'SAPT0')

psi4.sapt()

**Comment by similt** [comment]
@jgonthier SAPT0 restart is working now. Thanks a lot.

**Comment by jgonthier** [comment]
You're welcome!
