### ISSUE TITLE
CASSCF from DFT reference

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#556]
Hi,

I'm trying to run some CASSCF calculations for systems where the HF reference is terrible. What I'd like to do is use e.g. BP86 orbitals to run CASSCF. However, when I use

energy('bp86')
set guess read
set maxiter 0
set fail_on_maxiter 0
energy('casscf')

it still runs a single HF iteration even though maxiter=0.

Would it be possible to change the behavior of maxiter so that maxiter=0 only recomputes the energy and orbital eigenvalues, but does not update the orbitals? (Pseudocanonization should be OK.)

**Comment by dgasmith** [comment]
Hi Susi,

Yes, SCF will always complete at least one iteration. This is mostly due to the fact that `guess read` may pass in junk orbitals and it is not considered a "real" iteration, hence `iteration 0`. You can accomplish what you want with the following:

```
scf_e, scf_wfn = energy('bp86', return_wfn=True)
energy('casscf', ref_wfn=scf_wfn)
```

Here, we completely bypass SCF and go directly into the `CASSCF` procedure with the `BP86` orbitals. This will work with any reference, including smaller CAS spaces or a MP2 natural orbital procedure.

**Comment by susilehtola** [comment]
Awesome! Thanks for the tip.

**Comment by susilehtola** [comment]
Btw, how can I get mp2 natural orbitals (or CAS natural orbitals)?

**Comment by dgasmith** [comment]
For CI you can do:

```
set NAT_ORBS true
cas_wfn, cas_e = energy('CASSCF', return_wfn =True)

# Set new active space
energy('CASSCF', ref_wfn=True)
```

MP2 is a bit of a toss up as its difficult to get MP2 densities out of Psi4 at the moment. With the current version of Psi4, DF-MP2 Natural Orbitals are the default guess. A stop gap would be to use OMP2 guess orbitals.

**Comment by susilehtola** [comment]
I'm a bit puzzled by CAS. The following input
```
molecule {
0 1
symmetry c1
C
C 1 1.0
}

set basis cc-pVDZ
set scf_type pk
set restricted_docc [2]
set restricted_uocc [16]
set active [10]
set wfn detci
set NUM_DETS_PRINT 40000
set e_convergence 1e-10
set r_convergence 1e-10
set ci_maxiter 1000
set mcscf_maxiter 100
set nat_orbs true

cas_e, cas_wfn = energy('casscf', return_wfn=True)

energy('casscf', ref_wfn=cas_wfn)
```
should do what you suggest, but when I look at the determinants output
```
    *   1    0.817064  (    1,    1)  3AX  4AX  5AX  7AX  
    *   2   -0.477071  (    2,    2)  3AX  4AX  6AX  7AX  
    *   3   -0.081234  (   15,   15)  3AX  4AX  5AX  9AX  
    *   4   -0.079478  (   10,   10)  3AX  5AX  7AX  8AX  
    *   5    0.075356  (    3,    9)  3AX  4AB  5AA  6AA  7AX  8AB  
```
the Aufbau determinant has a tiny weight: -5.602591646315e-03. If it's really using NOs, the Aufbau determinant should have significant weight, right?

**Comment by CDSherrill** [comment]
I'm not sure why the Aufbau determinant has such a small weight, so that's
a bit of a mystery.  But I'm a little surprised you would want to run this
particular procedure.

If you ran a CASSCF and got its natural orbitals, and then fed those
orbitals to a CASSCF, you should get exactly the same energy, because the
natural orbitals of a CAS just rotate the active space orbitals amongst
themselves, and the CAS energy is (by definition) invariant to rotations
within the active space.  I suppose you could do this if you just wanted to
see how the CI coefficients changed if you used natural orbitals as the
one-particle basis.

More typical, if you had trouble converging the CASSCF, would be to run an
initial MP2 or CISD (with no frozen virtuals) and get natural orbitals out
of that, and then do a CAS with those starting orbitals.

As Daniel says, we may not have a great mechanism right now to do this with
MP2 NO's (we'll have to work on that).  But, if it's a small molecule,
running a CISD initially and getting NO's from that should work.  Although,
again, you'd need to be sure to change the keywords ... something like this:

set restricted_uocc [0]
ci_e, ci_wfn = energy('cisd', return_wfn=True)

set restricted_uocc [16]
energy('casscf', ref_wfn=ci_wfn)

Regarding the original question, though, do you get the same energy out of
the 2nd CASSCF (within convergence criteria)?

**Comment by susilehtola** [comment]
The Aufbau determinant is the same and has pretty much the same weight as in a HF calculation, and from the looks of commit 90cbafb2ad1e7a0a70780b26e5caa15c1ed02a60 it wasn't really doing the NOs.. which I also was wondering for FCI, but I guess that also got solved.

And yes, the reason why I want to rotate my orbitals is just to get a prettier CI wave function.
