### ISSUE TITLE
detci diag_method=olsen not working

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#559]
```
molecule {
symmetry c1
He 0.0 0.0 0.0
He 0.0 0.0 1000.0
}

set basis 6-31G
set GUESS_VECTOR UNIT
set NUM_DETS_PRINT 4000000000000
set e_convergence 1e-10
set r_convergence 1e-10
set diag_method olsen
energy('fci')
```

gives either a segfault or
```
*** H0 Block Eigenvalue =  -5.71032085

Find the roots with Olsen's single vector algorithm
init_array:  trouble allocating memory 
size = -1465995312
```

**Comment by dgasmith** [comment]
Also fails with `set diag_method mitrushenkov`.

Not completely surprised as the `olsen` and `mitrushenkov` methods have not been tested since this was integrated into Psi4 from Psi3 as far as I know. Its a bit of strange error in debugging as it looks like the H0 block was not initialized even though it was.

Ill look into when I have time, but thats not likely to be soon. Do you really want something besides Davidson iterations or is this just a report that it doesn't work?

**Comment by susilehtola** [comment]
Davidson should be fine for my purposes, this was just a heads-up. I'm more worried about issue #558, which runs but gives the wrong result!
