### ISSUE TITLE
Container format for archiving and exchanging results with other codes

### ISSUE THREAD

**Issue by tovrstra** [psi4/psi4#562]
This is the continuation of a discussion that started in another issue (#504)

Formatted checkpoint files or Molden files are not great as a container format. It makes sense to have them as an output format (because some other programs can already read them.) However, they are not suitable as an extensible container format:

1) They lack an open way of extending/improving the format in future.
2) They are just defined ad hoc as the file format that is being produced by some code.
3) There is no unambiguous document specifying these formats.

A format based on HDF5 would make more sense. It has its deficiencies too unfortunately: the format specification is very complex, with only one (open source) library implementing it. Something simpler would be nice, e.g. a ZIP file containing the following would make a lot of sense:

- An index file (XML?) with metadata for all the data in the archive.
- One file per (big) array: binary data with some header to specify byte order, data type, ... e.g. the npy format. (See https://docs.scipy.org/doc/numpy-dev/neps/npy-format.html)
- Other text or log files.

This similar to the opendocument specification, where it seems to survive for many years now. The main disadvantage of such a zip file, compared to HDF5, is that you cannot easily access a part of an array without unzipping the entire array. You can however access one entire array without unzipping the other ones.

**Comment by dgasmith** [comment]
I do like HDF5, but it would add an extra dependency to Psi4 for something relatively simple. We use NumPy to write arrays [here](https://github.com/psi4/psi4/blob/master/psi4/driver/p4util/numpy_helper.py#L445), it should be noted the resulting data is in binary form and readable by anyone. Our Wavefunctions are written as `npz` objects for the SCF `GUESS READ` machinery [here](https://github.com/psi4/psi4/blob/master/psi4/driver/procedures/proc.py#L1340) using the above machinery. A JSON write would be equivalent and probably much more general.

The above snippet is specific to Psi4's SCF Wavefunction, but I have been wanting to generalize this function for some time so that a user could read/write a general Wavefunction on command. We would be happy to work on the underlying data structures to make them more general.

**Comment by dgasmith** [comment]
This comment has been superseded by the MolSSI QC JSON Schema. Please have further information on the schema's [repo](https://github.com/MolSSI/QC_JSON_Schema).
