### ISSUE TITLE
1.1.0 release eta

### ISSUE THREAD

**Issue by mj-harvey** [psi4/psi4#608]
Hi,

Hope you don't mind me asking if there's an ETA for the 1.1.0 release?
I ask only because I'd like to co-ordinate with the release schedule of our own software that has a dependency on Psi4.

Thanks,

Matt

**Comment by loriab** [comment]
Good question. The todo list is [here](https://github.com/psi4/psi4/projects/3). Except for a couple things (basis set and dkh changes), it's mainly a task of finishing up the interfacing of other software that works with Psi4, rather than Psi4 itself. I'd venture a RC w/i 3 weeks. What's your software release?

**Comment by mj-harvey** [comment]
Thanks @loriab , I'll make a note to schedule that against our March release. We're using psi4 as part of a force-field parameteristion tool (see https://github.com/Acellera/htmd ). It's Python 3  only and distributed via conda so we have to do some nastry tricks to ship the py2 psi4.

**Comment by loriab** [comment]
Sounds good. You've noticed that there _is_ as py3 conda package for Mac and Linux (https://github.com/psi4/psi4/issues/466#issuecomment-272589229)? It's stable, just not on the main channel until the 1.1 release.
