### ISSUE TITLE
Access to terms in the MP2 energy from Python

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#642]
With the df-mp2 wavefunction object in Python, is there any way to get access to the content of the  `energies_` map other than through the global process state (`core.get_variable()`)?

https://github.com/psi4/psi4/blob/master/psi4/src/psi4/dfmp2/mp2.cc#L792-L800

**Comment by dgasmith** [comment]
Not currently. The plan is to move all internal variables to the [`variables` dictionary](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/wavefunction.h#L547) on the Wavefunction which is exposed to Python.

For DFMP2 this is rather straight forward, you could find and replace all `energy_` variables with `variables_` and pop the `energy_` dictionary from the MP2 header. Other classes are more difficult which is why this is on the TODO list, but feel free to do this one if needed.

**Comment by loriab** [comment]
The plan in future is to collect those quantities on the wavefunction [here](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/wavefunction.h#L233) instead of/addition to in globals. But for now, `psi4.get_variable()` is the place to go.

**Comment by rmcgibbo** [comment]
This sounds easy. I'll submit a PR to do this for df-mp2.

**Comment by dgasmith** [comment]
Fixed by #643. Closing.
