### ISSUE TITLE
simint-scf5 failing

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4#738]
I am having some trouble with test case simint-scf5 failing, specifically in the singlet CUKS PK case.  In principle, my changes should not have affected this test case, and so I wonder if it is a problem with the test case.  I recall that at one time we had removed testing of CUKS because we found it to be numerically unstable and Rob wasn't able to remove the numerical instability.  But we decided to leave in CUKS as a feature because it worked most of the time and therefore could be helpful to users.

This particular test case is a bit strange ... we are testing O2 for a singlet with CUKS?  While one *can* run CUKS on a singlet, this seems like a really odd thing to do...

What seems to be happening is that the guess orbitals are core Hamiltonian, and they are high-spin open-shell.  This being the case, the CUHF runs and happily leaves the computation high-spin open-shell.  Then obviously the triplet state obtained has a different energy than the singlet state energy that is being compared.  I am not sure why we are getting a high-spin open-shell guess, since the computation knows it's a singlet.

  Charge       = 0
  Multiplicity = 1
  Electrons    = 16
  Nalpha       = 8
  Nbeta        = 8

  ==> Algorithm <==

  SCF Algorithm Type is PK.
  DIIS enabled.
  MOM disabled.
  Fractional occupation disabled.
  Guess Type is CORE.

...

    Occupation by irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u
    DOCC [     3,    0,    0,    0,    0,    2,    1,    1 ]
    SOCC [     0,    0,    1,    1,    0,    0,    0,    0 ]

   @CUHF iter   1:  -129.99407460698782   -1.29994e+02   3.58550e-01
   @CUHF iter   2:  -138.94369344094056   -8.94962e+00   1.91667e-01 DIIS
   @CUHF iter   3:  -149.19229734982372   -1.02486e+01   5.23276e-02 DIIS
   @CUHF iter   4:  -149.61401801756168   -4.21721e-01   8.25602e-03 DIIS
   @CUHF iter   5:  -149.62784456434520   -1.38265e-02   7.20728e-04 DIIS
   @CUHF iter   6:  -149.62803800931584   -1.93445e-04   1.87787e-04 DIIS
   @CUHF iter   7:  -149.62804359068420   -5.58137e-06   2.42248e-05 DIIS
   @CUHF iter   8:  -149.62804290255499    6.88129e-07   3.86408e-06 DIIS
   @CUHF iter   9:  -149.62804316316681   -2.60612e-07   2.79748e-07 DIIS

  ==> Post-Iterations <==

  @Spin Contamination Metric:  1.00000
  @S^2 Expected:               0.00000
  @S^2 Observed:               1.00000

In the reference [correct] output, the Occupation by irrep is closed shell.

Perhaps there is a bug in the Core Hamiltonian guess routine not respecting the multiplicity, and/or experiencing some small numerical instability.  This problem seems intermittent for me, I thought I ran essentially the same code yesterday without this case failing.

Attempting to attach test output.

David

[output.txt](https://github.com/psi4/psi4/files/1066053/output.txt)

**Comment by loriab** [comment]
You're right that scf5 is nondeterministic, sometimes affecting `scf5`, `simint-scf5`, `erd-scf5`. Restarting the Travis run will usually fix the immediate problem.

**Comment by CDSherrill** [comment]
Ah, in that case, perhaps we should remove at least the CUHF singlet test from scf5, if it is known to be nondeterministic?

**Comment by fevangelista** [comment]
I looked into this recently. The issue is that O2 has two degenerate orbitals. The issue begins when psi4 guesses the correct occupation. To determine which orbital is occupied we sort the orbitals and then populate them with electrons. If the alpha and beta orbitals end up being sorted in the same way we get a closed-shell det, if their order is switched (as it sometimes happens) then we get an open shell determinant (say pi_a pi'_b). Here is some debug info that I printed about a week ago. It shows the iterations through the sorted eigenvalues. You can see that in the second set the orbitals are picked in a different order and we get an open shell configuration.

```
 nalphapi_ -> 0, 0, 5
 nalphapi_ -> 0, 1, 0
 nalphapi_ -> 1, 2, 0
 nalphapi_ -> 1, 3, 5
 nalphapi_ -> 0, 4, 6 // <
 nalphapi_ -> 0, 5, 7 // <
 nalphapi_ -> 2, 6, 0
 nalphapi_ -> 0, 7, 2
 nbetapi_ -> 0, 0, 5
 nbetapi_ -> 0, 1, 0
 nbetapi_ -> 1, 2, 0
 nbetapi_ -> 1, 3, 5
 nbetapi_ -> 0, 4, 6 // <
 nbetapi_ -> 0, 5, 7 // <
 nbetapi_ -> 2, 6, 0
 nbetapi_ -> 0, 7, 2    Occupation by irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u
    DOCC [     3,    0,    1,    0,    0,    2,    1,    1 ]
    SOCC [     0,    0,    0,    0,    0,    0,    0,    0 ]
```

```
 nalphapi_ -> 0, 0, 5
 nalphapi_ -> 0, 1, 0
 nalphapi_ -> 1, 2, 0
 nalphapi_ -> 1, 3, 5
 nalphapi_ -> 0, 4, 7 // <
 nalphapi_ -> 0, 5, 6 // <
 nalphapi_ -> 2, 6, 0
 nalphapi_ -> 0, 7, 3
 nbetapi_ -> 0, 0, 5
 nbetapi_ -> 0, 1, 0
 nbetapi_ -> 1, 2, 0
 nbetapi_ -> 1, 3, 5
 nbetapi_ -> 0, 4, 6 // < order is flipped here
 nbetapi_ -> 0, 5, 7 // < order is flipped here
 nbetapi_ -> 2, 6, 0
 nbetapi_ -> 0, 7, 2    Occupation by irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u
    DOCC [     3,    0,    0,    0,    0,    2,    1,    1 ]
    SOCC [     0,    0,    1,    1,    0,    0,    0,    0 ]
```

I am not sure what's the origin of the different ordering. I would assume that the sorting algorithm is deterministic. Perhaps the diagonalization step is not in the case of degeneracies.

In my opinion this is not a good test case. Perhaps it should be replaced with one where there is no issue with exactly degenerate orbitals.

The puzzling aspect is that at one point during my debugging if I printed more information I was always getting the right answer.

**Comment by fevangelista** [comment]
Just realized that the debug info is not very clear. The numbers printed are (MO index in irrep, orbital count, irrep). As you can see the last alpha/beta orbitals are different in the two runs.

**Comment by fevangelista** [comment]
One fix may be to set ` DOCC = [3,0,1,0,0,2,1,1 ]` in the input file.

**Comment by dgasmith** [comment]
Kind of an interesting edge case, since the SOCC orbitals area always assumed to be of the same spin the sorting breaks the multiplicity. This could be widely considered a "bug" as the sorting *should* be aware of this in a perfect world.

At the same time, CUHF for closed shell doesn't make a ton of sense so perhaps the other way to do it is have CUHF complain if a closed shell molecule is given? We can likely find similar errors when running UHF in singlet mode. Some logic to switch between RHF and UHF can be added if a user doesnt specify a reference.

**Comment by dgasmith** [comment]
For this I plan on setting the `DOCC` keyword in the test case and then printing a warning in `UHF` and `CUHF` that if a singlet is requested these things *can* go wonky in the presence of degeneracies. There are better solutions that range greatly in time, but I think this at least covers it.  Ill update #736 unless anyone has objections.
