### ISSUE TITLE
conda + install_name potential problem?

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#749]
In the process of debugging $#748 I noticed that after following the install instructions [here](http://www.psicode.org/psi4manual/master/conda.html#how-to-use-conda-to-compile-psi4-faster-and-easier), that some of the install_name_tool / placeholder / rpath'y stuff for some of the dependencies looks wrong.

I don't know if this is causing any issues or not, but it looks potentially incorrect.

```
$ otool -L /Users/mcgibbon/miniconda/envs/p4dev/lib/libdkh.dylib
/Users/mcgibbon/miniconda/envs/p4dev/lib/libdkh.dylib:
	@rpath/libdkh.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by loriab** [comment]
The `/usr/lib/libSystem.B.dylib` is ok because we indeed want to link to the Sys lib on each computer, not anything installed by conda. Similarly `/usr/lib/libblas` or lapack if they ocurred b/c after much link following, they end up at Accelerate. The `libgcc_s.1.dylib` is bizarre – will investigate.

**Comment by rmcgibbo** [comment]
Right. It's just the `/Users/ray/.../placeholder/placeholder` that seems wrong.

**Comment by loriab** [comment]
Ok, new pkgs at https://anaconda.org/psi4/dkh/files (and gdma and erd) that should have a sane linkage listing. I get the following. Should be obtainable through `conda update dkh erd gdma -c psi4`. Those are the only ones I could see, and that's reasonable since I usually build the three pure fortran ones together.

```
/Users/github/builds/conda-builds/dkh_1498680189814/_t_env/lib/libdkh.dylib:
	@rpath/libdkh.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	@rpath/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by loriab** [comment]
Thanks for the alert. All should be fixed now, so will close if don't hear otherwise from you.
