### ISSUE TITLE
Something weird with PES scan: SCF suddenly not converging

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#759]
So here's another weird issue with PES scans in Psi4. Namely, it looks like the scan crashes in the SCF cycle every 4 or 5 points, even when I'm not feeding in the previous scf solution. If you try a new calculation in the point where it failed to converge, there's no problem.

Test input
```
molecule mol {
0 1
symmetry c1
H 0.0 0.0 0.0
H 0.0 0.0 R1
H 0.0 0.0 R2
H 0.0 0.0 R3
}   
    
set basis STO-3G
set ci_maxiter 100

# This crashes at R=0.68
#for ir in range(60, 80, 2):
# This crashes at R=0.74
for ir in range(68, 80, 2):
    mol.R1 = 1*(ir/100)
    mol.R2 = 2*(ir/100)
    mol.R3 = 3*(ir/100)
    ci_e=energy('fci')
```

**Comment by fevangelista** [comment]
Can confirm it, but had to fiddle with the input to see the error because coordinates were returning all 0s (integer rounding). This input work on my machine:
```
molecule mol {
0 1
symmetry c1
H 0.0 0.0 0.0
H 0.0 0.0 R1
H 0.0 0.0 R2
H 0.0 0.0 R3
}

set basis STO-3G
set ci_maxiter 100

# This crashes at R=0.68
#for ir in range(60, 80, 2):
# This crashes at R=0.74
for ir in range(68, 80, 2):
    mol.R1 = 1.*(float(ir)/100.)
    mol.R2 = 2.*(float(ir)/100.)
    mol.R3 = 3.*(float(ir)/100.)
    ci_e=energy('fci')
```

**Comment by dgasmith** [comment]
Pretty easy answer, if you look at the results you see pure nonsense in the molecule geometry. Each time you update a variable the molecule geometry is updated, since you do not have `no_com` set the molecule is moving around on you quite a bit and you're not building the geometry you think you are building.

If you set `no_com`, everything works fine. This kind of variable setting really only should be used with a z-matrix. I wonder if we should enforce this.
