### ISSUE TITLE
How can I match conda package to source code and release notes?

### ISSUE THREAD

**Issue by tzyii** [psi4/psi4#763]
For example, there seems no tag that corresponding to the dev package "linux-64/psi4-1.2a1.dev419+809f363-py36_0.tar.bz2". How can I find the code, commits or release notes? Thank you.

**Comment by loriab** [comment]
The `809f363` is the commit hash, which is the latest commit "Merge pull request 743" on the main GH page. The `dev419` just means 419 commits beyond the latest tag, which you probably saw is "v1.1". The conda dev package version is computed from a [git describe](https://github.com/psi4/psi4/blob/master/psi4/versioner.py#L105) command so that there's always a sortable version for every commit but it can also be linked back to the git record via the hash. Last set of release notes will be for 1.1.

**Comment by tzyii** [comment]
Get it. Thank you for your reply.
