### ISSUE TITLE
Analytic RHF Hessian incorrect with d functions

### ISSUE THREAD

**Issue by berquist** [psi4/psi4#791]
The degenerate bending mode of carbon dioxide is incorrect using the analytic Hessian at the HF/Def2-SVP level, but correct at the HF/STO-3G.

STO-3G (analytic)

      1: 566.2461745
      2: 566.2461746
      3: 1435.2209003
      4: 2535.7035140

Def2-SVP (numerical)

      1: 758.2796976
      2: 758.2797814
      3: 1540.0254807
      4: 2631.1290692

Def2-SVP (analytic)

      1: 762.2335574
      2: 960.1013244
      3: 1538.9589455
      4: 2628.8341889
      
This occurs for both the DF and exact Hessian, either 1 or 4 threads, and `scf_type {direct, pk}`. It's correct for 6-31G but incorrect for 6-31G*, so this screams d-function problem.

---

Input file to reproduce:

```
molecule {
C         0.0000000000    0.0000000000    0.0000000000
O         0.0000000000    0.0000000000    1.1369750000
O         0.0000000000    0.0000000000   -1.1369750000
}

set {
    basis def2-svp
    df_scf_guess false
    scf_type direct
}

frequencies('hf')
```

Version: using both v1.1 ([`add49b9`](https://github.com/psi4/psi4/commit/add49b9)) from conda and [`90e1da2`](https://github.com/psi4/psi4/commit/90e1da2) compiled locally.

Here is the HF/STO-3G (no DF) geometry I used:

```
3

C         0.0000000000    0.0000000000    0.0000000000
O         0.0000000000    0.0000000000    1.1879706068
O         0.0000000000    0.0000000000   -1.1879706068
```

**Comment by andysim** [comment]
Thanks a lot for the detailed bug report.  I can reproduce your error and will look into it when I get time (probably not until next week, I'm afraid).  The problem seems to occur when d functions are present as you indicated, but it's independent of whether spherical or Cartesian basis functions are used.  It's also only an issue for molecules with degenerate modes, based on my 30 seconds of testing; that explains why my tests all passed when I wrote the code.  I'll have to add a linear triatomic to the test suite when I get to the bottom of this mystery.
