### ISSUE TITLE
Bundled packages sholdn't be installed as part of psi4

### ISSUE THREAD

**Issue by yurivict** [psi4/psi4#854]
Currently, psi4 installs bin/xc-info, include/libxc/xc.h, lib/libxc.a that conflict with standalone libxc package.
It also installs include/libint/libint.h and lib/libint.a that conflict with standalone libint package.
Etc.

If psi4 needs those packages, it should either use bundled versions internally, during build, or use external versions. Installing bundled packages causes conflicts with standalone versions.

I suggest:
1. have USE_EXTERNAL_LIBXC, USE_EXTERNAL_LIBINT, etc, that will make build to use external packages
2. Bundled versions should only be used internally, and not installed

**Comment by loriab** [comment]
Are you building Psi4 for packaging or for single-deployment use?

Psi4 does check for external packages at CMake configure time and will find any you specify with the variables in "CMake Variables" section in http://psicode.org/psi4manual/master/libint.html#how-to-configure-libint-for-building-psi4 and similar variables for other packages. Note that the external packages must have been built to export a CMake target (that is, `LibintConfig.cmake`). The CMake config should be reporting a colored Found or Building for each package. When Psi4 itself is packaged, it always uses externally built packages of its dependencies so that none of other packages' files get installed (except pybind11 headers, just because it's safer to keep the right version internally).

For single-deployment Psi4 builds, it'll just build and install whatever's needed, as you observed, for the user's convenience.

Do you think the existing scheme can work for you? I'm glad to explain it further if you need.

**Comment by yurivict** [comment]
> Are you building Psi4 for packaging or for single-deployment use?

For packaging

> Psi4 does check for external packages 

If does, but it falls back on the bundled version when it doesn't find the external package for some reason when it actually exists. There should be a clear way to require to use external packages.

**Comment by yurivict** [comment]
@loriab For example, libxc project.

The version here http://www.tddft.org/programs/octopus/download/libxc/ doesn't even contain .cmake files. Why doesn't it and how can external libxc be found without .cmake? Your version here https://github.com/loriab/libxc has .cmake files in the tree, and its README claims that it installs them, but it really doesn't install them. So, again, how can the external libxc be found?

Why aren't .cmake files installed?

**Comment by loriab** [comment]
I can put in an `INSIST_FIND_PACKAGE` signal, but it'd probably be a universal one, as I'd rather not proliferate another set of variables.

On the Libxc front, their development moved to GitLab (https://gitlab.com/libxc/libxc). I've added CMake to their build system, but their only official release since its been in (4.0, a few weeks ago) isn't compatible with Psi4 yet). So you're right that it's GH:loriab/libxc for now. But that repo should absolutely be installing `share/cmake/Libxc/LibxcConfig.cmake` and similar files. Note that [this line](https://github.com/psi4/psi4/blob/master/external/upstream/libxc/CMakeLists.txt#L21) has to be in place for Psi to work. I'm glad to look at your build directive if that'd help. There's also a conda package for Libxc, but that won't much interest you for packaging purposes.

**Comment by yurivict** [comment]
> I can put in an INSIST_FIND_PACKAGE signal, but it'd probably be a universal one, as I'd rather not proliferate another set of variables.

IMO, it's best to have a set of variables per-bundled dependency, because some packages might be either missing, or have some problems on some platforms, and it's better to be able to turn them on/off individually.

Bundled ```pybind11``` also installs files
```
include/pybind11/attr.h
include/pybind11/cast.h
...
share/cmake/pybind11/pybind11Tools.cmake
```
```
that are in direct conflict with standalone package. Such files just can't be installed by psi4.

> I'm glad to look at your build directive if that'd help.

Thank you for your offer! I am ok for now, but I will ask you if I run into problems.

**Comment by loriab** [comment]
Yes, we're in a bad situation wrt pybind11. We use 2.0 (c. Jan 2017) that allows the resulting python `.so` to also be used as an ordinary Linux library for symbols for our plugins. Unfortunately, at 2.0 the pybind11 installations via `setup.py` and CMake had different directory structures, with the former being more common in packaging. So most detected pybind11 2.0's would be useless to psi. On the other hand, pybind11 2.2 restricts symbol usage, so can't be used with our plugin system. But the install directory structures have been reconciled, I believe.

Until we reform our symbol handling and plugin system and allow pybind11 updating, I think the current situation is best. You're welcome to delete the final offending pybind11 files; it will only break the psi4 plugin system, not psi4 itself. It would be [here](https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L234-L237) to change.

I may be not quite following the INSIST_FIND_PACKAGE reasoning. What you're after is readily achieved by `ENABLE_PkgName=ON`/`OFF` and inspecting the "Found"/"Building" labels of the initial CMake config. Is it because you want the CMake config to _fail_ when the desired Found/Build pattern is not achieved, rather than the run-successfully/inspect/delete/run process currently in place? I can see how in an automated workflow situation that would be preferable.

**Comment by yurivict** [comment]
> I may be not quite following the INSIST_FIND_PACKAGE reasoning.

ENABLE_PkgName=ON/OFF turns it off completely. And I would like to control bundling. I want cmake to fail when external package isn't found.

I am trying to create the FreeBSD port for psi4. Package build infrastructure is all automated, and is very rigorous. So if the package is chosen to be installed externally, there is no reason to even try to download it from github. It's besides the point here, but such downloads are also a security risk, because you don't check the downloaded file's fingerprints.

**Comment by amjames** [comment]
wrt to the security issues you brought up @yurivict I know that cmake's ExternalProject tools make it possible to check fingerprints after the download step, but this is usually done when some tarball is being downloaded. In our case we are actually using git to clone a repo with the source code, I don't know how you can check the fingerprint for a repo.

Now, if we do download any of the external projects as a tarball I completely agree with you that we should probably start checking the fingerprints.

**Comment by yurivict** [comment]
> I don't know how you can check the fingerprint for a repo.

Probably not for github. Github is fundamentally insecure as implemented by cmake.

Documentation says that hash can be set for URL downloads though.

**Comment by loriab** [comment]
Various `CMAKE_INSIST_FIND_PACKAGE_<Addon>` vars added (e.g., https://github.com/psi4/psi4/blob/master/external/upstream/gdma/CMakeLists.txt#L9). Also, since pybind11 bumped to 2.2.2 in psi, we can use any 2.2.2 pre-packaged pybind11 that includes the cmake files (not sure you get them if you build from `setup.py`), so that should remove the last unavoidable bundling of other packages' files.
