### ISSUE TITLE
SCF correlating molecular and wavefunction symmetry

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#875]
I believe we have had this problem in the past. Take a symmetric molecule who's optimal wavefunction should contain less symmetry:

```python
import numpy as np

mol = psi4.geometry("""
 0 1
C 0.0 0.0  0.673055
C 0.0 0.0 -0.673055
H 0.0  0.934981 1.246807
H 0.0 -0.934981 1.246807
H  0.934981 0.0 -1.246807
H -0.934981 0.0 -1.246807
symmetry c1
""")

# Set reference and guess.
psi4.set_options({
    "reference": "rhf",
    "guess": "sad",
    "basis": "DZP",
    "soscf": "true",
#    "sad_frac_occ": "true"
})

e_scf = energy('scf')
if np.allclose(e_scf, -77.87781349420317):
    print("Found non-symmetric minima! Success!")
elif np.allclose(e_scf, -77.84789770426966):
    print("Found symmetric minima... failure.")
else:
    print("You found something... wrong.")
```

The `-77.847` result should be found when the molecule is constrained to symmetry. However, without that constraint there is a lower SCF result to be found. The kicker is even without the symmetry restraint (computation in `c1`) we fairly consistently end up with a symmetric wavefunction. Any ideas on how to avoid this?

Note 1: The stability analysis is showing that it is indeed finding the wrong answer and there are negative eigenvalues present. We should be able to follow these once the py-scf iterations are finished.

Note 2: This is not deterministic for which result we land in (whoo!).

Note 3: Moving an atom out of place by 1e-14 or so seems to ensure we find the correct energy. Really any noise lets the diagonalizer break out of its self-imposed symmetry constraints.

**Comment by CDSherrill** [comment]
It's a feature not a bug?

Symmetric molecules are supposed to have symmetric wavefunctions (because
the Hamiltonian commutes with the symmetry operators).  Certainly, the
exact wavefunction does has the full point group symmetry.  Occasionally,
approximate QM methods can have lower-energy non-symmetric solutions.
Anytime the wavefunction has a lower symmetry than the molecule, this is
usually considered a bad thing and is often called "artifactual (spatial)
symmetry breaking."  Wes Allen and Daniel Crawford have some excellent
papers on this topic (I've made a couple contributions, also).

In most applications, generally the high symmetry wavefunction is the one
that is actually desired, although it depends on the situation whether the
symmetric or non-symmetric solutions will give better predictions of
molecular properties.

C2H4 is not a classic "symmetry breaking molecule" to my knowledge, so I'm
surprised that there is a symmetry-breaking solution to the SCF equations.

**Comment by tsexton** [comment]
The example C2H4 geometry isn't the global minimum of ethene.  The geometry given is for a rotation about the double bond, so maybe that's why its symmetry-breaking?

**Comment by CDSherrill** [comment]
Ah, yes, twisted ethylene starts to take on a diradical character, so that
could explain it.

If some advanced users really needed the artifactual symmetry broken
solution, sounds like the stability analysis would find it.

On Dec 5, 2017 6:19 PM, "tsexton" <notifications@github.com> wrote:

The example C2H4 geometry isn't the global minimum of ethene. The geometry
given is for a rotation about the double bond, so maybe that's why its
symmetry-breaking?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/psi4/psi4/issues/875#issuecomment-349474468>, or mute
the thread

**Comment by loriab** [comment]
FYI, @wadejong. Are you more concerned with accessing the symmetry-broken sol'n (perhaps through geometry tweaks or stability analysis) or with it being the default sol'n?

**Comment by wadejong** [comment]
Communicating with Daniel, the challenge is that the solver somehow was sticking to a symmetry solution inherent in the molecule, this while a no symmetry solution was requested. I would expect a symmetry broken solution if I tell the calculation to assume a symmetry lower than possible (assuming there is a lower energy solution in the symmetry broken case).

**Comment by CDSherrill** [comment]
@wadejong, the trick is that some of our codes can't handle symmetry, so
frequently users ask for C1 even though they really don't mean it, due to
parts of the code being C1 only (although maybe some recent code I added
fixes this?). Most of these users will want the symmetric solution because
it tends to be more free of unphysical values for properties like
vibrational frequencies.

The situation is analogous to running a closed shell molecule with UHF.  It
will always give the RHF solution, not a UHF solution, unless the user
intervenes and deliberately breaks the alpha / beta symmetry that is
naturally there.   Some programs have special keywords to do this.  Or do
you automatically mix alpha and beta in NWChem when a user asks for UHF on
a closed shell molecule?

On Dec 5, 2017 7:52 PM, "Bert de Jong" <notifications@github.com> wrote:

Communicating with Daniel, the challenge is that the solver somehow was
sticking to a symmetry solution inherent in the molecule, this while a no
symmetry solution was requested. I would expect a symmetry broken solution
if I tell the calculation to assume a symmetry lower than possible
(assuming there is a lower energy solution in the symmetry broken case).


> On Dec 5, 2017, at 4:46 PM, Lori A. Burns <notifications@github.com>
wrote:
>
> FYI, @wadejong. Are you more concerned with accessing the symmetry-broken
sol'n (perhaps through geometry tweaks or stability analysis) or with it
being the default sol'n?
>
> —
> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/psi4/psi4/issues/875#issuecomment-349492637>, or mute
the thread

**Comment by loriab** [comment]
One can form a distinction btwn cases, right?

##### User doing (or reinforcing) driver's job
* set `C1` on mixed EFP/QM calc
* set `C1` prior to symmetry-intolerant module

##### User actually wants calculation run w/o symmetry
* set lower-than-actual symm to influence thermochemical analysis
* set `C1` to enable symmetry-broken sol'ns, as here

As far as a sol'n to this issue, we can add infinitesimal user-symm jitter to the geometry. But your concern, @CDSherrill, is that users intending the former category (which they expect to be, at worst, harmless) will get caught up in the "fix" for the latter category?

**Comment by CDSherrill** [comment]
Indeed, that's my concern.  Users specifying "symmetry c1" expect it to be
harmless, whereas if jitter is added by default, they might get an
artifactual symmetry-broken solution that hardly anyone would ever actually
want, with possible concomitant crazy molecular properties.

Does c1 actually affect our thermochemistry computations?   In what way?

Maybe @wadejong can clarify why he wants artifactual symmetry broken
solutions. The only person I can think of who actually uses symmetry-broken
solutions regularly would be Gus Scuseria and his methods that break but
then re-impose symmetry.

**Comment by loriab** [comment]
Symmetry affects the rotational_symmetry_number in thermochem. But you're right, on second thought the way for users to influence the rsn is [via option](https://github.com/loriab/psi4/blob/pyvib2/tests/freq-isotope2/input.dat#L77) not Molecule symmetry.

**Comment by wadejong** [comment]
Well, Daniel’s sad_frac_occ true actually gives the lower RHF state that both MOLCAS and NWChem give (one C with px and one C with py). This is of course a very odd “multi-reference” case (ethylene rotation at 90 degrees).

**Comment by hokru** [comment]
I always get the non-sym solution with the given input, but I should not (technically) ?

Isnt the MOM procedure meant to calculate non-ground state SCF solutions? Does it avoid breaking the symmetry? The given twisted ethylene here is triplet?

**Comment by dgasmith** [comment]
@hokru It will depend quite a bit on your eigensolver. MKL seem pretty stable, your milage may vary.

@CDSherrill I think your latest work will fix most of the SCF `c1` symmetry issues as SCF is now always run with symmetry and then cast to `c1`.

What I really dont like about this is that it's non-deterministic. You can wind up in either minima with no real control over which you land in. Some proposals is something like `scf_density_shake 0.0` where we add a bit of noise to the density to knock it out of any starting symmetry.

**Comment by CDSherrill** [comment]
@hokru Mathematically speaking, you should never get a non-symmetric solution.  But, as @dgasmith says, it depends on the math library, whether or not there is tiny numerical noise introduced, etc.  Since the computer use finite precision arithmetic, there is always a chance that noise messes up things.  

I investigated this case a little today, since it captured my interest.  What's going on is actually even more tricky than has been suggested so far.

Normally, we don't like these symmetry-breaking solutions because they do bad things, like give unphysical dipole moments.  For example, the symmetry-breaking UHF solution for NO3 radical gives very unequal charges for the O atoms [-0.0867 -0.3789 -0.3789] compared to the symmetric UHF solution [-0.2990 -0.2990 -0.2990].  I think most people would agree the asymmetric solution is just wrong, even though it has a lower energy [-278.774 819 vs -278.757 840] (https://doi.org/10.1016/S0009-2614(99)00206-7).  

So, I looked at this 90 degrees twisted C2H4 example, expecting the lower-energy symmetry-broken solution to give an unphysical dipole moment.  What I found surprised me.  The problem here is that the "symmetric solution" that we've been discussing is actually a symmetry-broken solution.  At 90 degrees, the true symmetry of the molecule is D2d.  Since this is a non-Abelian group, Psi4 (and most codes) can't run it as D2d, so it gets run in a subgroup.  Here, there are 2 choices for subgroups, C2v and D2.  Psi4 picks C2v, very unfortunately, and in that subgroup, it finds a wavefunction that is very symmetry broken (compared to the full symmetry D2d), and it gets a really large, totally unphysical dipole moment of 3.2 debye.  

I haven't yet managed to convince Psi4 that D2 is an acceptable subgroup at the 90 degrees geometry, but if I set the torsion angle to just off of 90 degrees (say, 89.9 deg), the code correctly detects D2 symmetry, and gets a much lower energy solution of -77.87817, which is the same one Daniel and Bert are finding for their computations that turn symmetry off (difference is because of my slightly perturbed geometry).   And the dipole moment is pleasantly 0.000 debye, like it's supposed to be. 

So, you guys are actually finding a symmetric solution when you use C1 (which is what's supposed to happen), and it's the correct-symmetry solution, unlike the local minimum C2v solution that Psi4 is falling into at this geometry.  I take some small consolation in the fact that Q-Chem also finds the same C2v solution at 90 degrees, in my quick tests (with or without symmetry turned on).

I don't know of a general strategy to teach Psi4 that D2 is a better choice in this case than C2v, because both are legitimate subgroups.  And I don't think the idea of running everything in C1 is necessarily a good idea either, since then one is opened up to the possibility of getting unphysical symmetry breaking solutions like in the case of NO3.  But, in this case, using symmetry also got us an unphysical symmetry-broken solution because we used the wrong point group.  So, I'm not sure of a general strategy for all this, although I share the concern of @dgasmith that the behavior can be non-deterministic depending on small details that shouldn't matter.

**Comment by dgasmith** [comment]
Closing this down for now.

@wadejong Please open a new PR if you want a specific implementation to get around this issue such as introducing noise to the SCF guess.
