### ISSUE TITLE
different parameter versions for DFT functionals with "dash correction"

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#920]
Title is kept general, but this is especially relevant for the newer DSD double hybrids. Issue made from short discussion in slacks.

For example: http://onlinelibrary.wiley.com/doi/10.1002/jcc.23391/full 
Different functional compositions for the exchange, correlation, mp2 parts for (among others) -D2 and -D3BJ.

The dashparam.py functionality cannot handle these multiple versions, but
`energy('dsd-pbepbe')`,  `energy('dsd-pbepbe-d2') `or `energy('dsd-pbepbe-d3bj')` should provide the proposed parameters automatically. 

A possible workaround is to define everything, including the e.g. the -D parameters, in the superfunctional object and either avoid the "dash" in the method name or avoid invoking the dashparam functionality for specific names.

**Comment by PeterKraus** [comment]
The references for the dashparams are currently handled in ``empirical_dispersion.py``. It might be convenient to keep those as defaults, and pass overrides or supplements in the dashparam.py file.

There's already the case of "B97" and "B97-D" functionals, where B97 refers to the hybrid of Becke, and B97-D is just the GGA part + D2 dispersion correction of Grimme. Another weird case is "wPBE" and "LCwPBE"; it would be cool if we could support both variants (along with "M062X" and "M06-2X" etc). Perhaps the functional translator part needs expanding.

Is there a reason why the "functional parts" (HF/GGA X, MP2/SS/OS/GGA C) couldn't be overridden by contents of dashparam.py? We could check whether the dashparam contains the keys, and if yes, override the defaults using lines 186-203 in superfuncs.py...

**Comment by dgasmith** [comment]
I was thinking it might be nice to have a dictionary that can define functionals rather than a function. For example `PBE0` could be defined like:

```python
func_dict["PBE0"] = {
    "name": "PBE0",
    "citation": ...,
    "x_functionals": [("XC_GGA_X_PBE", 0.75), ]
     "c_functionals": [("XC_GGA_C_PBE", 1.0), ]
    "set_x_alpha": 0.25,
    }
```

Here it would be much easier to programmatically build functionals. We could have it so that any valid SuperFunctional setter (`x_omega`, `vv10_c`, etc) could be used. This would also be very useful for the `-NL` functionals.

**Comment by PeterKraus** [comment]
I had a bit more of a look and here's what I'd propose:

1) Introduce a new handler into `psi4.driver.dft_funcs.build_superfunctional` at line 175, that returns `sup = (func, False)` for non-dispersion funcs and `sup = (func, ("custom", dispersion_type, dispersion_params))`.

2) The new handler should apply default parameters (alpha, beta, omega, references) from LibXC, unless overridden in the functional definition:
```
func_dict["PBE0"] = {
    "name": "PBE0",
    "xc_functionals": {"HYB_GGA_XC_PBEH": {}}, # XC functional defined - all parameters should be in LibXC
    }
func_dict["MN15"] = {
    "name": "MN15",
    "c_functionals": {"MGGA_C_MN15": {}},
    "x_functionals": {"HYB_MGGA_X_MN15": {}}, # HYB without alpha, parameter sourced from LibXC
    }
func_dict["B2PLYP"] = {
    "name": "B2PLYP",
    "c_functionals": {"GGA_C_LYP": {"alpha": 0.73}}, # C alpha implies C_MP2 = 1 - C_GGA
    "x_functionals": {"GGA_X_B88": {"alpha": 0.47}}, # X alpha implies X_HF = 1 - X_GGA
    "citation": "...",
    }
func_dict["DSD-BLYP-D2"] = {
    "name": "DSD-BLYP-D2",
    "c_functionals": {
                     "GGA_C_LYP": {"alpha": 0.55}, 
                     "C_MP2": {"alpha": 1.0, "ss": 0.43, "os": 0.46}, # SS and OS tuned for -D2
                     },
    "x_functionals": {"GGA_X_B88": {"alpha": 0.29}},
    "citation": "...",
    "dispersion": {
                  "type": "-D2", 
                  "params": {"s6": 0.35},
                  "citation": "...", 
                  },
    }
```
3) The class `EmpiricalDispersion` will need to be adjusted to process the provided parameters accordingly. All possible parameters for the `dispersion_type` should be passed into `EmpiricalDispersion` from the handler above, so that `self.dash_params = dispersion_params`, with defaults already filled into `dispersion_params` for missing parameters (eg. `"s6": 1.0, "alpha6": 14.0` for `-d3zero`). Perhaps using a switch (such as `alias == "custom"` suggested above)?

**Comment by dgasmith** [comment]
A few notes:
1) Why does the dispersion string need to be expanded? Not opposed just curious.
2) Im not a fan of the transparent assumptions of what HF alpha and MP2 components should be. Would prefer if we specific them explicitly in other parts of the spec.

On this note it is a bit hard to pick up something like `HYB_MGGA_X_MN15` and auto detect the need to pull parameters from the underlying function. In addition, what happens if someone does a silly operation like mixing multiple HYB functionals? We likely want to specify *something* to indicate that we should pull exchange parameters from a given functional.

**Comment by PeterKraus** [comment]
> 1. Why does the dispersion string need to be expanded? Not opposed just curious.

I'm not sure how to handle the dispersion part, actually. It makes sense to keep current ``dashparams``, as the dict-based method seems inconvenient (but not impossible) for implementing functionals that require a lot of tweaks, such as `PWPB95`, and the old method uses dashparams. On the other hand, it makes sense to have the definition of a functional in one place - the dictionary - as opposed to splitting it across files. That means having the dashparams in the functional dictionary, and passing them into `EmpiricalDispersion`.

> 2. Im not a fan of the transparent assumptions of what HF alpha and MP2 components should be. Would prefer if we specific them explicitly in other parts of the spec.

The spec could (some might say should) simply be "use LibXC defaults, unless overridden".

> In addition, what happens if someone does a silly operation like mixing multiple HYB functionals?

Fair point. If somebody were to do:
```
junk = {
    "x_functionals": {{"HYB_MGGA_X_MN15": {}, "HYB_MGGA_M06": {}}
    ...
}
```
we should probably catch that and crash gracefully, as it's not clear which libxc-provided `ALPHA` should be used for `X_HF`. However, if somebody wants to do something like:

```
junk = {
    "x_functionals": {{"HYB_MGGA_X_MN15": {"alpha": 0.5}, "HYB_MGGA_M06": {"alpha":0.5}, "X_HF":{"alpha": 0.27}}
    ...
}
```
that should be allowed, and is quite clear: 50% MN15 GGA exchange + 50% M06 GGA exchange + 27% HF exchange. Perhaps we could simply enforce that if ``len(x_functionals) >= 2`` then ``"X_HF" in x_functionals`` must be true.

I'm not sure how this works with range separation. It should be, in theory, possible to combine two range-separated hybrids, with different ``OMEGA``'s.

**Comment by susilehtola** [comment]
> I'm not sure how this works with range separation. It should be, in theory, possible to combine two range-separated hybrids, with different OMEGA's.

There are also some rs hybrids that carry more than one omega. (Not supported at present in libxc.)

**Comment by dgasmith** [comment]
For dashparams I think it makes sense to leave these in place and we would build new dictionaries on the fly. For example B3LYP would look like the following:

```python
funcs = {...} # All of the normal functionals
for dash in dash_params:
    tmp = copy.deepcopy(funcs["B3LYP"])
    tmp["dispersion"] = ("D3", "Zero", param1, param2, ...)
    tmp["name"] = "B3LYP-D3"
    funcs[tmp["name"]] = tmp
```

Special D3 functionals could then be built by hand. This would also make all of the if logic in the building a functional simpler I think.

> The spec could (some might say should) simply be "use LibXC defaults, unless overridden".

I would prefer if we would just specify something like "use_xc_params" to make it clear that something like "HYB_GGA_X_MN15" has parameters that we can pull from to help setup the functional, but "GGA_C_PBE" does not. In this way something like:

```
junk = {
    "x_functionals": {{"HYB_MGGA_X_MN15": {"use_xc_params": True}, "HYB_MGGA_M06": {}}
    ...
}
```

would still work out.

**Comment by PeterKraus** [comment]
I believe this can now be closed.
