### ISSUE TITLE
SAPT(DFT) : Allow calculations without the asymptotic-correction (AC)

### ISSUE THREAD

**Issue by ajmisquitta** [psi4/psi4#939]
Hi Daniel, 
It would be a good idea to allow SAPT(DFT) calculations without the AC, but this does not seem to be a possibility at the moment as the GRAC shifts are needed and they need to be non-zero. 

GRAC should be an optional part of the SAPT(DFT) calculation. And all parameters in GRAC should be user accessible (this is normally the case in other codes) so the way the splicing is done can be altered if needed. At present only the shifts are user-defined.

This would allow range-separated functionals to be used in SAPT(DFT). Right now it does not seem like they can. 
Thanks!

**Comment by dgasmith** [comment]
Sure, I can expose the other GRAC terms to allow users to modify them.

For SAPT(DFT) requiring GRAC I was under the impression that some sort of check is (effectively) required so that users do not skip this in the input (and thus get very poor results). Do you have an idea of a clean way to check that the user has satisfied the asymptotic correction in *some* way.

**Comment by ajmisquitta** [comment]
Hi Daniel,
A simple way would be to force the presence of the GRAC shift commands, but switch it off if the shifts are negative. Or simply allow a new option: ASYMPTOTIC-CORRECTION True | False This may be a better approach as it will allow the possibility of negative shifts should there be *some* reason to use them.

By the way, the reason for my asking this is that I want to try the range-separated functionals with IP-tuning. Will the w-parameter be user-definable for a SAPT(DFT) calculation?

**Comment by dgasmith** [comment]
What if we change it so that if you ran `set SAPT_DFT_GRAC_SHIFT_A 0.0` that would satisfy the requirement? This would enforce users who want a 0 GRAC shift to be conscious of this act.

We could have a `SAPT_DFT_OMEGA_A/B` and either OMEGA or GRAC must be set? For range tuning, ultimately what I would like is the ability to do this automatically (I think we have automated tuning built-in already).

For advanced users we could also add the ability for you to simple give two monomer wave functions and it would compute SAPT(DFT) between the two. SAPT(DFT) is constructed internally that this is already how its called.

**Comment by ajmisquitta** [comment]
Try not to make things too automatic: self-consistent IP tuning is not always a good idea as there are functionals/systems for which no solution exists so you come close to self-consistency but never reach it. It is always good to have this as an option, but also always allow the user to override the settings. I prefer to fix the tuning as it is often nearly exactly what I need. Full self-consistency sometimes doesn't get you much more in accuracy but can take too long to achieve. 

On a related note: why duplicate DFT commands/options in the SAPT(DFT) section? Would it not be better to define the density functional and then simply use the defined settings in the SAPT(DFT) calculation?
